[package]
  edition = "2021"
  name    = "forgedb-http-server"
  version = "0.1.0"

[dependencies]
  axum               = "0.8"
  axum-server        = { version = "0.6", features = ["tls-rustls"] }
  dashmap            = "5.5"
  http               = "1.0"
  lazy_static        = "1.4"
  prometheus         = "0.13"
  rustls             = "0.23"
  serde              = { version = "1.0", features = ["derive"] }
  serde_json         = "1.0"
  tokio              = { version = "1", features = ["full"] }
  tokio-rustls       = "0.26"
  tower              = "0.4"
  tower-http         = { version = "0.5", features = ["cors", "limit", "timeout", "trace"] }
  tracing            = "0.1"
  tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
  uuid               = { version = "1.6", features = ["v4"] }
