[package]
name = "forgedb-watcher"
version = "0.2.0"
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "File watcher and schema regenerator for ForgeDB"
repository = "https://github.com/hoodiecollin/forgedb"
keywords = ["database", "watcher", "forgedb", "filesystem"]
categories = ["database", "filesystem"]

[dependencies]
notify = "8.2"
crossbeam-channel = "0.5"
forgedb-codegen = { path = "../codegen", version = "0.2.0" }
forgedb-parser = { path = "../parser", version = "0.2.0" }
tracing = "0.1"
