mod common;

use common::write;
use std::path::Path;
use std::process::{Command, Output};

const SCHEMA: &str = r#"
User {
  id: +uuid
  email: ^&string @email
  created_at: +timestamp
}

Post {
  id: +uuid
  title: string
  author: *User
}
"#;

fn project(dir: &Path, targets: &str) {
    std::fs::create_dir_all(dir).unwrap();
    write(&dir.join("schema.forge"), SCHEMA);
    write(
        &dir.join("forgedb.toml"),
        &format!(
            "[project]\nid = \"cliloop\"\nisolated = true\n\n\
             [generate]\noutput = \"generated\"\ntargets = [{targets}]\n"
        ),
    );
}

fn forgedb(dir: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_forgedb"))
        .args(args)
        .current_dir(dir)
        .env("FORGEDB_HOME", dir.join(".home"))
        .output()
        .expect("run forgedb")
}

fn ok(out: &Output, what: &str) {
    assert!(
        out.status.success(),
        "{what} exited {:?}\n--- stdout ---\n{}\n--- stderr ---\n{}",
        out.status.code(),
        String::from_utf8_lossy(&out.stdout),
        String::from_utf8_lossy(&out.stderr)
    );
}

#[test]
fn generate_runs_again_without_force() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    project(root, "\"rust\"");

    for run in 1..=3 {
        let out = forgedb(root, &["generate", "--schema", "schema.forge"]);
        ok(&out, &format!("generate run {run}"));
    }
}

#[test]
fn generate_rewrites_from_the_edited_schema() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    project(root, "\"rust\"");
    let db_rs = root.join("generated").join("database.rs");

    ok(
        &forgedb(root, &["generate", "--schema", "schema.forge"]),
        "first generate",
    );
    let first = std::fs::read_to_string(&db_rs).expect("database.rs after the first run");
    assert!(
        !first.contains("pub struct Comment"),
        "the fixture must not already carry the model the edit adds"
    );

    write(
        &root.join("schema.forge"),
        &format!("{SCHEMA}\nComment {{\n  id: +uuid\n  body: string\n}}\n"),
    );
    ok(
        &forgedb(root, &["generate", "--schema", "schema.forge"]),
        "generate after the edit",
    );

    let second = std::fs::read_to_string(&db_rs).expect("database.rs after the second run");
    assert!(
        second.contains("pub struct Comment"),
        "the second run did not pick up the edited schema — it exited 0 having \
         written nothing"
    );
}

#[test]
fn force_is_still_accepted_and_changes_nothing() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    project(root, "\"rust\"");

    ok(
        &forgedb(root, &["generate", "--schema", "schema.forge"]),
        "plain generate",
    );
    let plain = std::fs::read_to_string(root.join("generated").join("database.rs")).unwrap();
    ok(
        &forgedb(root, &["generate", "--schema", "schema.forge", "--force"]),
        "generate --force",
    );
    let forced = std::fs::read_to_string(root.join("generated").join("database.rs")).unwrap();
    assert_eq!(plain, forced, "`--force` must not change a generated byte");
}

#[test]
fn quiet_stdout_is_empty() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    project(root, "\"rust\"");

    for args in [
        vec!["--quiet", "validate", "--schema", "schema.forge"],
        vec!["--quiet", "generate", "--schema", "schema.forge"],
    ] {
        let out = forgedb(root, &args);
        ok(&out, &format!("{args:?}"));
        assert!(
            out.stdout.is_empty(),
            "`{args:?}` wrote {} byte(s) to a quiet stdout: {:?}",
            out.stdout.len(),
            String::from_utf8_lossy(&out.stdout)
        );
    }
}

#[test]
#[ignore = "tier 2: compiles a release cargo workspace"]
fn print_artifact_stdout_is_exactly_one_line() {
    let tmp = tempfile::tempdir().unwrap();
    let root = tmp.path();
    project(root, "\"rust\", \"api\"");

    let out = forgedb(
        root,
        &["build", "--print-artifact", "server"],
    );
    ok(&out, "build --print-artifact server");

    let stdout = String::from_utf8(out.stdout).expect("stdout is utf-8");
    let lines: Vec<&str> = stdout.lines().collect();
    assert_eq!(
        lines.len(),
        1,
        "stdout must carry the path and nothing else, got {} line(s): {stdout:?}",
        lines.len()
    );
    let path = Path::new(lines[0]);
    assert!(
        path.is_absolute() && path.exists(),
        "the printed path must name a real artifact: {}",
        lines[0]
    );
}
