//! Native FFI generator — the Layer-0 C-ABI **spine** (language-bindings #51/#52/#117).
//!
//! Emits, per schema, the schema-invariant *lifecycle + error* half of the fat
//! generated C-ABI described in `docs/proposals/language-bindings.md` ("ABI
//! symbol naming (pinned)"). This is the boundary every language binding
//! (PyO3 / NAPI-RS) hangs off: `forgedb_open`/`forgedb_close`,
//! `forgedb_commit`/`forgedb_checkpoint`/`forgedb_compact`, the error trio
//! (`forgedb_error_code`/`_message`/`_free`), `forgedb_free_buffer`, and
//! `forgedb_version`.
//!
//! **Identity (class-2 transport glue — the spirit of the old `crates/ffi`):**
//! like the wasm `Replica`, this file is *generated per schema* but its symbol
//! set is *schema-invariant* — it references only the generated `Database` type
//! and its lifecycle methods, never a model or field name, and it dispatches on
//! nothing. The per-model row ops + the per-column Arrow export (the
//! schema-tailored half) are a later phase and land in the SAME file; this phase
//! is the spine they attach to. There is deliberately **no** generic
//! `forgedb_query(model, predicate)` symbol — that shape is the removed-
//! `QueryBuilder` red line (acceptance constraint 1).
//!
//! **Panic discipline.** Every entry point that can run engine code wraps it in
//! `catch_unwind` and converts a panic into a `ForgeError` — an unwind across the
//! `extern "C"` boundary into a foreign caller is UB, so the spine refuses to let
//! one escape (e.g. `open_at`'s `DirLock` contention `expect`).

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use quote::quote;

/// Generates the native FFI spine (`ffi.rs`) for a schema.
pub struct FfiGenerator;

impl FfiGenerator {
    /// Generate the Layer-0 C-ABI lifecycle/error spine.
    ///
    /// The `schema` is taken for parity with the other generators (and so the
    /// per-model ops phase can extend this same entry point), but the spine's
    /// emitted symbols are schema-invariant.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let tokens = quote! {
            //! Generated by ForgeDB — native FFI, Layer-0 C-ABI spine.
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue for the native language bindings
            //! (#51 Python/PyO3, #52 Node + #117 Bun/NAPI-RS). Exposes the
            //! schema-invariant lifecycle + error surface over the generated
            //! `Database`. The tailored data logic lives in the generated
            //! `database.rs`; this file is the boundary the per-runtime wrappers
            //! bind. It invents no query API (the identity red line).
            #![allow(warnings)]

            mod database;

            use std::ffi::{CStr, CString, c_char};
            use std::panic::{AssertUnwindSafe, catch_unwind};
            use std::path::PathBuf;
            use std::ptr;
            use std::sync::OnceLock;

            use database::Database;

            /// Opaque database handle passed across the C-ABI as `*mut Db`. Owns
            /// the generated `Database` (including its single-writer `DirLock`);
            /// freed by `forgedb_close`.
            pub struct Db {
                inner: Database,
            }

            /// An error surfaced across the C-ABI as `*mut ForgeError`. Allocated
            /// by the engine when an entry point fails and freed by the caller via
            /// `forgedb_error_free` — never freed implicitly.
            pub struct ForgeError {
                code: i32,
                message: CString,
            }

            /// A null or non-UTF-8 argument reached an entry point.
            const FORGEDB_ERR_INVALID_ARG: i32 = 1;
            /// The engine returned an `io::Error` (e.g. a failed `commit` fsync).
            const FORGEDB_ERR_IO: i32 = 2;
            /// Engine code panicked; the unwind was caught at the boundary and
            /// converted here rather than crossing into the foreign caller (UB).
            const FORGEDB_ERR_PANIC: i32 = 3;

            /// Write a fresh boxed `ForgeError` through `err_out` when it is
            /// non-null. A nul byte in `message` is impossible from our sources,
            /// but is handled without panicking for total safety.
            unsafe fn set_error(err_out: *mut *mut ForgeError, code: i32, message: String) {
                if err_out.is_null() {
                    return;
                }
                let message = CString::new(message)
                    .unwrap_or_else(|_| CString::new("error").unwrap());
                *err_out = Box::into_raw(Box::new(ForgeError { code, message }));
            }

            /// Extract a human-readable message from a caught panic payload.
            fn panic_message(payload: Box<dyn std::any::Any + Send>) -> String {
                if let Some(s) = payload.downcast_ref::<&str>() {
                    (*s).to_string()
                } else if let Some(s) = payload.downcast_ref::<String>() {
                    s.clone()
                } else {
                    "unknown panic".to_string()
                }
            }

            /// The generated engine crate's version (`CARGO_PKG_VERSION`), as a
            /// stable NUL-terminated C string. Owned by the process — the caller
            /// must NOT free it.
            #[unsafe(no_mangle)]
            pub extern "C" fn forgedb_version() -> *const c_char {
                static VERSION: OnceLock<CString> = OnceLock::new();
                VERSION
                    .get_or_init(|| {
                        CString::new(env!("CARGO_PKG_VERSION")).unwrap_or_else(|_| {
                            CString::new("0.0.0").unwrap()
                        })
                    })
                    .as_ptr()
            }

            /// Open (or create) a database at `root`. Returns an owned `*mut Db`,
            /// or null with `*err_out` set. `flags` is reserved (must be 0).
            ///
            /// # Safety
            /// `root` must be a valid NUL-terminated C string; `err_out`, if
            /// non-null, must point to writable storage for one `*mut ForgeError`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_open(
                root: *const c_char,
                _flags: u32,
                err_out: *mut *mut ForgeError,
            ) -> *mut Db {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                if root.is_null() {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "root path is null".to_string());
                    return ptr::null_mut();
                }
                let root = match CStr::from_ptr(root).to_str() {
                    Ok(s) => PathBuf::from(s),
                    Err(_) => {
                        set_error(
                            err_out,
                            FORGEDB_ERR_INVALID_ARG,
                            "root path is not valid UTF-8".to_string(),
                        );
                        return ptr::null_mut();
                    }
                };
                // `open_at` can panic (e.g. `DirLock` contention — single-writer,
                // #89). Catch it here so it becomes an error instead of unwinding
                // into the foreign caller.
                match catch_unwind(AssertUnwindSafe(|| Database::open_at(root))) {
                    Ok(db) => Box::into_raw(Box::new(Db { inner: db })),
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        ptr::null_mut()
                    }
                }
            }

            /// Close a database opened by `forgedb_open`, releasing its lock.
            /// A null handle is a no-op. The handle is invalid afterward.
            ///
            /// # Safety
            /// `db` must be a handle from `forgedb_open` not already closed.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_close(db: *mut Db) {
                if db.is_null() {
                    return;
                }
                drop(Box::from_raw(db));
            }

            /// Flush every column to durable storage (fsync). Returns `true` on
            /// success; on failure returns `false` with `*err_out` set.
            ///
            /// # Safety
            /// `db` must be a live handle from `forgedb_open`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_commit(
                db: *mut Db,
                err_out: *mut *mut ForgeError,
            ) -> bool {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                let Some(db) = db.as_mut() else {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                    return false;
                };
                match catch_unwind(AssertUnwindSafe(|| db.inner.commit())) {
                    Ok(Ok(())) => true,
                    Ok(Err(e)) => {
                        set_error(err_out, FORGEDB_ERR_IO, e.to_string());
                        false
                    }
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        false
                    }
                }
            }

            /// Force a WAL checkpoint (fsync columns, then truncate the WAL).
            /// Returns `true` on success, `false` with `*err_out` set on panic.
            ///
            /// # Safety
            /// `db` must be a live handle from `forgedb_open`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_checkpoint(
                db: *mut Db,
                err_out: *mut *mut ForgeError,
            ) -> bool {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                let Some(db) = db.as_mut() else {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                    return false;
                };
                match catch_unwind(AssertUnwindSafe(|| db.inner.checkpoint())) {
                    Ok(()) => true,
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        false
                    }
                }
            }

            /// Explicitly compact the database (reclaim dead row versions).
            /// **Explicit only** — no read/convenience path reaches this
            /// (acceptance constraint 4). Returns `true` on success, `false` with
            /// `*err_out` set on panic.
            ///
            /// # Safety
            /// `db` must be a live handle from `forgedb_open`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_compact(
                db: *mut Db,
                err_out: *mut *mut ForgeError,
            ) -> bool {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                let Some(db) = db.as_mut() else {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                    return false;
                };
                match catch_unwind(AssertUnwindSafe(|| db.inner.compact())) {
                    Ok(()) => true,
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        false
                    }
                }
            }

            /// The numeric code of an error (see the `FORGEDB_ERR_*` constants).
            /// Returns 0 for a null pointer.
            ///
            /// # Safety
            /// `err`, if non-null, must be a `ForgeError` not yet freed.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_error_code(err: *const ForgeError) -> i32 {
                match err.as_ref() {
                    Some(e) => e.code,
                    None => 0,
                }
            }

            /// The message of an error as a borrowed NUL-terminated C string valid
            /// until `forgedb_error_free`. Returns null for a null pointer.
            ///
            /// # Safety
            /// `err`, if non-null, must be a `ForgeError` not yet freed.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_error_message(err: *const ForgeError) -> *const c_char {
                match err.as_ref() {
                    Some(e) => e.message.as_ptr(),
                    None => ptr::null(),
                }
            }

            /// Free an error produced by the engine. A null pointer is a no-op.
            ///
            /// # Safety
            /// `err` must be a `ForgeError` from an engine out-param, freed once.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_error_free(err: *mut ForgeError) {
                if err.is_null() {
                    return;
                }
                drop(Box::from_raw(err));
            }

            /// Free a byte buffer the engine handed out (the gathered-buffer half
            /// of the Arrow C-Data-Interface `release` path; an alias buffer is a
            /// no-op release, never this). A null pointer is a no-op.
            ///
            /// # Safety
            /// `ptr`/`len` must be a buffer produced by a ForgeDB engine call
            /// whose contract names `forgedb_free_buffer` as its releaser (length
            /// == capacity), freed once.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_free_buffer(ptr: *mut u8, len: usize) {
                if ptr.is_null() {
                    return;
                }
                drop(Vec::from_raw_parts(ptr, len, len));
            }
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!("Failed to parse generated ffi spine: {e}"))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!(
                "native FFI Layer-0 C-ABI spine ({} models)",
                schema.models.len()
            ),
        })
    }

    /// The `Cargo.toml` for the generated native FFI engine crate. User-editable
    /// config, so the CLI writes it ONLY when absent (like the wasm replica's
    /// `Cargo.toml` and the TS SDK's `package.json`).
    ///
    /// A `cdylib` (for the C-ABI `.so`/`.dylib`/`.dll` a binding `dlopen`s) plus
    /// an `rlib` (so a NAPI-RS/PyO3 wrapper crate can depend on it directly).
    /// `panic = "unwind"` is load-bearing: the entry points `catch_unwind` engine
    /// panics, so the profile must not be `panic = "abort"`.
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib: the C-ABI shared object a Python/Node/Bun binding loads.
# rlib:   so a NAPI-RS / PyO3 wrapper crate can link the engine directly.
crate-type = ["cdylib", "rlib"]

[dependencies]
forgedb-storage = "0.2"
forgedb-types = "0.2"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
forgedb-txn = "0.1"
forgedb-coordinator = "0.1"
forgedb-query-params = "0.1"
forgedb-auth = "0.1"
regex = "1"
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}

[profile.release]
# Load-bearing: the C-ABI entry points catch_unwind engine panics, so the
# release profile must unwind (not abort) for that boundary to hold.
panic = "unwind"
"#
        )
    }
}
