//! Native FFI generator — the Layer-0 C-ABI (language-bindings #51/#52/#117).
//!
//! Emits, per schema, the fat generated C-ABI described in
//! `docs/proposals/language-bindings.md` ("ABI symbol naming (pinned)"). Two
//! halves land in the SAME generated `ffi/src/lib.rs`:
//!
//! * the schema-**invariant** *lifecycle + error* spine (Phase 2) every binding
//!   (PyO3 / NAPI-RS) hangs off: `forgedb_open`/`forgedb_close`,
//!   `forgedb_commit`/`forgedb_checkpoint`/`forgedb_compact`, the error trio
//!   (`forgedb_error_code`/`_message`/`_free`), `forgedb_free_buffer`,
//!   `forgedb_version`;
//! * the schema-**tailored** per-model OLTP row ops (Phase 3): for each identity
//!   model `M` (snake name `m`), `forgedb_<m>_insert`/`_get`/`_count`/`_all`/
//!   `_update`/`_delete`, calling the generated `Database::create_<m>` /
//!   `update_<m>` / `delete_<m>` integrity wrappers + `<m>` storage reads.
//!
//! **Identity (class-2 transport glue — the spirit of the old `crates/ffi`):**
//! like the wasm `Replica`, this file is *generated per schema*. The spine's
//! symbols are schema-invariant; the per-model ops reference the generated
//! structs/wrappers by name (that IS the tailoring) but still invent **no**
//! generic query surface — rows and ids cross the C-ABI as OPAQUE JSON bytes
//! (the same opaque-bytes discipline as the WAL / broker / wasm-replica paths),
//! decoded into the generated type via serde at a compile-time-known type. There
//! is deliberately **no** generic `forgedb_query(model, predicate)` symbol and no
//! `match model` runtime dispatch — that shape is the removed-`QueryBuilder` red
//! line (acceptance constraint 1). The per-column Arrow/columnar export (the
//! zero-copy selling point) + the `_async` completion bridges are a later phase
//! and land in this same file.
//!
//! **Panic discipline.** Every entry point that can run engine code wraps it in
//! `catch_unwind` and converts a panic into a `ForgeError` — an unwind across the
//! `extern "C"` boundary into a foreign caller is UB, so the spine refuses to let
//! one escape (e.g. `open_at`'s `DirLock` contention `expect`).

use crate::RustGenerator;
use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use quote::{format_ident, quote};

/// Generates the native FFI spine (`ffi.rs`) for a schema.
pub struct FfiGenerator;

impl FfiGenerator {
    /// Generate the Layer-0 C-ABI lifecycle/error spine.
    ///
    /// The `schema` is taken for parity with the other generators (and so the
    /// per-model ops phase can extend this same entry point), but the spine's
    /// emitted symbols are schema-invariant.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let model_ops = Self::generate_model_ops(schema);
        let relation_ops = Self::generate_relation_ops(schema);
        let tokens = quote! {
            //! Generated by ForgeDB — native FFI, Layer-0 C-ABI spine.
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue for the native language bindings
            //! (#51 Python/PyO3, #52 Node + #117 Bun/NAPI-RS). Exposes the
            //! schema-invariant lifecycle + error surface over the generated
            //! `Database`. The tailored data logic lives in the generated
            //! `database.rs`; this file is the boundary the per-runtime wrappers
            //! bind. It invents no query API (the identity red line).
            #![allow(warnings)]

            mod database;

            use std::ffi::{CStr, CString, c_char};
            use std::panic::{AssertUnwindSafe, catch_unwind};
            use std::path::PathBuf;
            use std::ptr;
            use std::sync::OnceLock;

            use database::Database;
            // `Uuid` names the primary-key type of UUID-keyed models in the
            // per-model row ops below (integer-PK models use a primitive id type).
            use forgedb_types::Uuid;

            /// Opaque database handle passed across the C-ABI as `*mut Db`. Owns
            /// the generated `Database` (including its single-writer `DirLock`);
            /// freed by `forgedb_close`.
            pub struct Db {
                inner: Database,
            }

            /// An error surfaced across the C-ABI as `*mut ForgeError`. Allocated
            /// by the engine when an entry point fails and freed by the caller via
            /// `forgedb_error_free` — never freed implicitly.
            pub struct ForgeError {
                code: i32,
                message: CString,
            }

            /// A null or non-UTF-8 argument reached an entry point.
            const FORGEDB_ERR_INVALID_ARG: i32 = 1;
            /// The engine returned an `io::Error` (e.g. a failed `commit` fsync).
            const FORGEDB_ERR_IO: i32 = 2;
            /// Engine code panicked; the unwind was caught at the boundary and
            /// converted here rather than crossing into the foreign caller (UB).
            const FORGEDB_ERR_PANIC: i32 = 3;
            /// A write was refused by the generated data-integrity gate (#91):
            /// a field constraint (422), a `&unique` clash or a dangling/blocked
            /// foreign key (409).  The message carries the specifics.
            const FORGEDB_ERR_VALIDATION: i32 = 4;

            /// Write a fresh boxed `ForgeError` through `err_out` when it is
            /// non-null. A nul byte in `message` is impossible from our sources,
            /// but is handled without panicking for total safety.
            unsafe fn set_error(err_out: *mut *mut ForgeError, code: i32, message: String) {
                if err_out.is_null() {
                    return;
                }
                let message = CString::new(message)
                    .unwrap_or_else(|_| CString::new("error").unwrap());
                *err_out = Box::into_raw(Box::new(ForgeError { code, message }));
            }

            /// Extract a human-readable message from a caught panic payload.
            fn panic_message(payload: Box<dyn std::any::Any + Send>) -> String {
                if let Some(s) = payload.downcast_ref::<&str>() {
                    (*s).to_string()
                } else if let Some(s) = payload.downcast_ref::<String>() {
                    s.clone()
                } else {
                    "unknown panic".to_string()
                }
            }

            /// Clear a caller's error out-param at entry (so a success leaves it
            /// null).  A null `err_out` is a no-op.
            unsafe fn clear_err(err_out: *mut *mut ForgeError) {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
            }

            /// View a caller-owned `(ptr, len)` as a borrowed byte slice, or `None`
            /// for a null pointer.  The bytes are read (decoded) before the call
            /// returns, so the borrow never outlives the caller's buffer.
            ///
            /// # Safety
            /// `ptr`/`len`, if `ptr` is non-null, must describe a readable buffer.
            unsafe fn read_bytes<'a>(ptr: *const u8, len: usize) -> Option<&'a [u8]> {
                if ptr.is_null() {
                    None
                } else {
                    Some(std::slice::from_raw_parts(ptr, len))
                }
            }

            /// Hand an engine-owned byte buffer out through `(out, out_len)`,
            /// transferring ownership to the caller — who frees it with
            /// `forgedb_free_buffer` (capacity == length, so the boxed slice
            /// reconstructs exactly).  If either out-param is null the buffer is
            /// dropped rather than leaked.
            ///
            /// # Safety
            /// `out`/`out_len`, when non-null, must point to writable storage.
            unsafe fn emit_bytes(bytes: Vec<u8>, out: *mut *mut u8, out_len: *mut usize) {
                if out.is_null() || out_len.is_null() {
                    drop(bytes);
                    return;
                }
                let boxed = bytes.into_boxed_slice();
                let len = boxed.len();
                let ptr = Box::into_raw(boxed) as *mut u8;
                *out = ptr;
                *out_len = len;
            }

            /// The generated engine crate's version (`CARGO_PKG_VERSION`), as a
            /// stable NUL-terminated C string. Owned by the process — the caller
            /// must NOT free it.
            #[unsafe(no_mangle)]
            pub extern "C" fn forgedb_version() -> *const c_char {
                static VERSION: OnceLock<CString> = OnceLock::new();
                VERSION
                    .get_or_init(|| {
                        CString::new(env!("CARGO_PKG_VERSION")).unwrap_or_else(|_| {
                            CString::new("0.0.0").unwrap()
                        })
                    })
                    .as_ptr()
            }

            /// Open (or create) a database at `root`. Returns an owned `*mut Db`,
            /// or null with `*err_out` set. `flags` is reserved (must be 0).
            ///
            /// # Safety
            /// `root` must be a valid NUL-terminated C string; `err_out`, if
            /// non-null, must point to writable storage for one `*mut ForgeError`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_open(
                root: *const c_char,
                _flags: u32,
                err_out: *mut *mut ForgeError,
            ) -> *mut Db {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                if root.is_null() {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "root path is null".to_string());
                    return ptr::null_mut();
                }
                let root = match CStr::from_ptr(root).to_str() {
                    Ok(s) => PathBuf::from(s),
                    Err(_) => {
                        set_error(
                            err_out,
                            FORGEDB_ERR_INVALID_ARG,
                            "root path is not valid UTF-8".to_string(),
                        );
                        return ptr::null_mut();
                    }
                };
                // `open_at` can panic (e.g. `DirLock` contention — single-writer,
                // #89). Catch it here so it becomes an error instead of unwinding
                // into the foreign caller.
                match catch_unwind(AssertUnwindSafe(|| Database::open_at(root))) {
                    Ok(db) => Box::into_raw(Box::new(Db { inner: db })),
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        ptr::null_mut()
                    }
                }
            }

            /// Close a database opened by `forgedb_open`, releasing its lock.
            /// A null handle is a no-op. The handle is invalid afterward.
            ///
            /// # Safety
            /// `db` must be a handle from `forgedb_open` not already closed.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_close(db: *mut Db) {
                if db.is_null() {
                    return;
                }
                drop(Box::from_raw(db));
            }

            /// Flush every column to durable storage (fsync). Returns `true` on
            /// success; on failure returns `false` with `*err_out` set.
            ///
            /// # Safety
            /// `db` must be a live handle from `forgedb_open`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_commit(
                db: *mut Db,
                err_out: *mut *mut ForgeError,
            ) -> bool {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                let Some(db) = db.as_mut() else {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                    return false;
                };
                match catch_unwind(AssertUnwindSafe(|| db.inner.commit())) {
                    Ok(Ok(())) => true,
                    Ok(Err(e)) => {
                        set_error(err_out, FORGEDB_ERR_IO, e.to_string());
                        false
                    }
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        false
                    }
                }
            }

            /// Force a WAL checkpoint (fsync columns, then truncate the WAL).
            /// Returns `true` on success, `false` with `*err_out` set on panic.
            ///
            /// # Safety
            /// `db` must be a live handle from `forgedb_open`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_checkpoint(
                db: *mut Db,
                err_out: *mut *mut ForgeError,
            ) -> bool {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                let Some(db) = db.as_mut() else {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                    return false;
                };
                match catch_unwind(AssertUnwindSafe(|| db.inner.checkpoint())) {
                    Ok(()) => true,
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        false
                    }
                }
            }

            /// Explicitly compact the database (reclaim dead row versions).
            /// **Explicit only** — no read/convenience path reaches this
            /// (acceptance constraint 4). Returns `true` on success, `false` with
            /// `*err_out` set on panic.
            ///
            /// # Safety
            /// `db` must be a live handle from `forgedb_open`.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_compact(
                db: *mut Db,
                err_out: *mut *mut ForgeError,
            ) -> bool {
                if !err_out.is_null() {
                    *err_out = ptr::null_mut();
                }
                let Some(db) = db.as_mut() else {
                    set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                    return false;
                };
                match catch_unwind(AssertUnwindSafe(|| db.inner.compact())) {
                    Ok(()) => true,
                    Err(payload) => {
                        set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                        false
                    }
                }
            }

            /// The numeric code of an error (see the `FORGEDB_ERR_*` constants).
            /// Returns 0 for a null pointer.
            ///
            /// # Safety
            /// `err`, if non-null, must be a `ForgeError` not yet freed.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_error_code(err: *const ForgeError) -> i32 {
                match err.as_ref() {
                    Some(e) => e.code,
                    None => 0,
                }
            }

            /// The message of an error as a borrowed NUL-terminated C string valid
            /// until `forgedb_error_free`. Returns null for a null pointer.
            ///
            /// # Safety
            /// `err`, if non-null, must be a `ForgeError` not yet freed.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_error_message(err: *const ForgeError) -> *const c_char {
                match err.as_ref() {
                    Some(e) => e.message.as_ptr(),
                    None => ptr::null(),
                }
            }

            /// Free an error produced by the engine. A null pointer is a no-op.
            ///
            /// # Safety
            /// `err` must be a `ForgeError` from an engine out-param, freed once.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_error_free(err: *mut ForgeError) {
                if err.is_null() {
                    return;
                }
                drop(Box::from_raw(err));
            }

            /// Free a byte buffer the engine handed out — a JSON record/id buffer
            /// from a per-model row op, or (later) the gathered-buffer half of the
            /// Arrow C-Data-Interface `release` path (an alias buffer is a no-op
            /// release, never this). A null pointer is a no-op.
            ///
            /// # Safety
            /// `ptr`/`len` must be a buffer produced by a ForgeDB engine call
            /// whose contract names `forgedb_free_buffer` as its releaser (length
            /// == capacity), freed once.
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn forgedb_free_buffer(ptr: *mut u8, len: usize) {
                if ptr.is_null() {
                    return;
                }
                drop(Vec::from_raw_parts(ptr, len, len));
            }

            // --- Per-model row ops (the schema-tailored half of the fat ABI) ---
            // These reference the generated per-model structs + integrity wrappers
            // by name — they ARE tailored per schema (that is the point) — but they
            // still invent no generic query surface: rows and ids cross the C-ABI
            // as OPAQUE JSON bytes (the same opaque-bytes discipline as the WAL /
            // broker / wasm-replica paths), decoded into the generated struct via
            // serde at a compile-time-known type.  There is no `forgedb_query`,
            // no runtime predicate, no `match model` dispatch.
            #(#model_ops)*

            // --- Relation-traversal ops (forward FK / reverse 1:M / M2M) -------
            // These mirror the generated `Database` traversal getters one-for-one
            // (same names, derived from the same schema), calling them by name and
            // returning the resolved record(s) as opaque JSON.  Still no generic
            // query surface — each getter is a fixed, generated edge walk, never a
            // runtime predicate.
            #(#relation_ops)*
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!("Failed to parse generated ffi spine: {e}"))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!(
                "native FFI Layer-0 C-ABI spine ({} models)",
                schema.models.len()
            ),
        })
    }

    /// Generate the per-model row-op C-ABI functions (the schema-tailored half of
    /// the fat ABI): for each identity model `M` with snake name `m` and id type
    /// `IdT`, six OLTP entry points —
    ///   * `forgedb_<m>_insert(db, rec, rec_len, id_out, id_len_out, err)` →
    ///     decodes a full `M` record from JSON, inserts it through the generated
    ///     `Database::create_<m>` integrity wrapper (FKs must resolve, then field
    ///     constraints + `&unique`), and hands the new id back as JSON bytes;
    ///   * `forgedb_<m>_get(db, id, id_len, out, out_len, err)` → resolves the id
    ///     (JSON) and emits the record as JSON, or leaves `*out` null if absent;
    ///   * `forgedb_<m>_count(db, err)` → the live row count as `i64` (`-1` on err);
    ///   * `forgedb_<m>_all(db, out, out_len, err)` → every live record as a JSON
    ///     array (the always-correct fallback; the columnar/Arrow export is a
    ///     later phase);
    ///   * `forgedb_<m>_update(db, id, id_len, rec, rec_len, err)` → `i32`:
    ///     `1` updated / `0` absent / `-1` error;
    ///   * `forgedb_<m>_delete(db, id, id_len, err)` → `i32`: `1` deleted /
    ///     `0` absent / `-1` error, through the referential-integrity
    ///     `Database::delete_<m>` wrapper.
    ///
    /// Rows/ids cross as opaque JSON bytes and are decoded into the generated
    /// struct / id type via serde — schema-tailored at a compile-time-known type,
    /// never a runtime schema read.  Every engine call is `catch_unwind`-guarded
    /// (an unwind across `extern "C"` is UB), and a rejected write becomes a
    /// `FORGEDB_ERR_VALIDATION` error rather than a panic.
    fn generate_model_ops(schema: &Schema) -> Vec<proc_macro2::TokenStream> {
        schema
            .models
            .iter()
            .filter(|m| m.fields.iter().any(|f| f.name == "id" || f.auto_generate))
            .map(|model| {
                let snake = RustGenerator::to_snake_case(&model.name);
                let model_ident = format_ident!("{}", model.name);
                let storage = format_ident!("{}", snake);
                let id_ty = RustGenerator::id_type_tokens(model);
                let create_fn = format_ident!("create_{}", snake);
                let update_fn = format_ident!("update_{}", snake);
                let delete_fn = format_ident!("delete_{}", snake);

                let insert_sym = format_ident!("forgedb_{}_insert", snake);
                let get_sym = format_ident!("forgedb_{}_get", snake);
                let count_sym = format_ident!("forgedb_{}_count", snake);
                let all_sym = format_ident!("forgedb_{}_all", snake);
                let update_sym = format_ident!("forgedb_{}_update", snake);
                let delete_sym = format_ident!("forgedb_{}_delete", snake);

                let insert_doc =
                    format!("Insert a `{}` (JSON record → new id JSON) via the integrity wrapper.", model.name);
                let get_doc =
                    format!("Fetch a `{}` by id (JSON → record JSON; `*out` null if absent).", model.name);
                let count_doc = format!("Live `{}` row count (`-1` on error).", model.name);
                let all_doc = format!("Every live `{}` as a JSON array.", model.name);
                let update_doc =
                    format!("Update a `{}` by id (1 updated / 0 absent / -1 error).", model.name);
                let delete_doc =
                    format!("Delete a `{}` by id with referential integrity (1 / 0 / -1).", model.name);

                quote! {
                    #[doc = #insert_doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `record`/`record_len` a readable JSON
                    /// buffer; `id_out`/`id_len_out`/`err_out`, when non-null,
                    /// writable.  On success `*id_out` is a buffer freed with
                    /// `forgedb_free_buffer`.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #insert_sym(
                        db: *mut Db,
                        record: *const u8,
                        record_len: usize,
                        id_out: *mut *mut u8,
                        id_len_out: *mut usize,
                        err_out: *mut *mut ForgeError,
                    ) -> bool {
                        clear_err(err_out);
                        if !id_out.is_null() { *id_out = ptr::null_mut(); }
                        if !id_len_out.is_null() { *id_len_out = 0; }
                        let Some(db) = db.as_mut() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return false;
                        };
                        let Some(bytes) = read_bytes(record, record_len) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "record buffer is null".to_string());
                            return false;
                        };
                        let record: database::#model_ident = match serde_json::from_slice(bytes) {
                            Ok(r) => r,
                            Err(e) => {
                                set_error(err_out, FORGEDB_ERR_INVALID_ARG, format!("invalid record JSON: {e}"));
                                return false;
                            }
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#create_fn(record))) {
                            Ok(Ok(id)) => match serde_json::to_vec(&id) {
                                Ok(json) => {
                                    emit_bytes(json, id_out, id_len_out);
                                    true
                                }
                                Err(e) => {
                                    set_error(err_out, FORGEDB_ERR_IO, format!("id serialize: {e}"));
                                    false
                                }
                            },
                            Ok(Err(e)) => {
                                set_error(err_out, FORGEDB_ERR_VALIDATION, e.to_string());
                                false
                            }
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                false
                            }
                        }
                    }

                    #[doc = #get_doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `id`/`id_len` a readable JSON id
                    /// buffer; `out`/`out_len`/`err_out`, when non-null, writable.
                    /// On a hit `*out` is a buffer freed with `forgedb_free_buffer`.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #get_sym(
                        db: *mut Db,
                        id: *const u8,
                        id_len: usize,
                        out: *mut *mut u8,
                        out_len: *mut usize,
                        err_out: *mut *mut ForgeError,
                    ) -> bool {
                        clear_err(err_out);
                        if !out.is_null() { *out = ptr::null_mut(); }
                        if !out_len.is_null() { *out_len = 0; }
                        let Some(db) = db.as_ref() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return false;
                        };
                        let Some(id_bytes) = read_bytes(id, id_len) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "id buffer is null".to_string());
                            return false;
                        };
                        let id: #id_ty = match serde_json::from_slice(id_bytes) {
                            Ok(v) => v,
                            Err(e) => {
                                set_error(err_out, FORGEDB_ERR_INVALID_ARG, format!("invalid id JSON: {e}"));
                                return false;
                            }
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#storage.get(id))) {
                            Ok(Some(record)) => match serde_json::to_vec(&record) {
                                Ok(json) => {
                                    emit_bytes(json, out, out_len);
                                    true
                                }
                                Err(e) => {
                                    set_error(err_out, FORGEDB_ERR_IO, format!("record serialize: {e}"));
                                    false
                                }
                            },
                            // Absent: success with `*out` left null (not an error).
                            Ok(None) => true,
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                false
                            }
                        }
                    }

                    #[doc = #count_doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `err_out`, when non-null, writable.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #count_sym(
                        db: *mut Db,
                        err_out: *mut *mut ForgeError,
                    ) -> i64 {
                        clear_err(err_out);
                        let Some(db) = db.as_ref() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return -1;
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#storage.row_count())) {
                            Ok(n) => n as i64,
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                -1
                            }
                        }
                    }

                    #[doc = #all_doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `out`/`out_len`/`err_out`, when
                    /// non-null, writable.  On success `*out` is a buffer freed
                    /// with `forgedb_free_buffer`.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #all_sym(
                        db: *mut Db,
                        out: *mut *mut u8,
                        out_len: *mut usize,
                        err_out: *mut *mut ForgeError,
                    ) -> bool {
                        clear_err(err_out);
                        if !out.is_null() { *out = ptr::null_mut(); }
                        if !out_len.is_null() { *out_len = 0; }
                        let Some(db) = db.as_ref() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return false;
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#storage.all())) {
                            Ok(records) => match serde_json::to_vec(&records) {
                                Ok(json) => {
                                    emit_bytes(json, out, out_len);
                                    true
                                }
                                Err(e) => {
                                    set_error(err_out, FORGEDB_ERR_IO, format!("records serialize: {e}"));
                                    false
                                }
                            },
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                false
                            }
                        }
                    }

                    #[doc = #update_doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `id`/`id_len` + `record`/`record_len`
                    /// readable JSON buffers; `err_out`, when non-null, writable.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #update_sym(
                        db: *mut Db,
                        id: *const u8,
                        id_len: usize,
                        record: *const u8,
                        record_len: usize,
                        err_out: *mut *mut ForgeError,
                    ) -> i32 {
                        clear_err(err_out);
                        let Some(db) = db.as_mut() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return -1;
                        };
                        let Some(id_bytes) = read_bytes(id, id_len) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "id buffer is null".to_string());
                            return -1;
                        };
                        let id: #id_ty = match serde_json::from_slice(id_bytes) {
                            Ok(v) => v,
                            Err(e) => {
                                set_error(err_out, FORGEDB_ERR_INVALID_ARG, format!("invalid id JSON: {e}"));
                                return -1;
                            }
                        };
                        let Some(rec_bytes) = read_bytes(record, record_len) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "record buffer is null".to_string());
                            return -1;
                        };
                        let record: database::#model_ident = match serde_json::from_slice(rec_bytes) {
                            Ok(r) => r,
                            Err(e) => {
                                set_error(err_out, FORGEDB_ERR_INVALID_ARG, format!("invalid record JSON: {e}"));
                                return -1;
                            }
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#update_fn(id, record))) {
                            Ok(Ok(true)) => 1,
                            Ok(Ok(false)) => 0,
                            Ok(Err(e)) => {
                                set_error(err_out, FORGEDB_ERR_VALIDATION, e.to_string());
                                -1
                            }
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                -1
                            }
                        }
                    }

                    #[doc = #delete_doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `id`/`id_len` a readable JSON id
                    /// buffer; `err_out`, when non-null, writable.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #delete_sym(
                        db: *mut Db,
                        id: *const u8,
                        id_len: usize,
                        err_out: *mut *mut ForgeError,
                    ) -> i32 {
                        clear_err(err_out);
                        let Some(db) = db.as_mut() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return -1;
                        };
                        let Some(id_bytes) = read_bytes(id, id_len) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "id buffer is null".to_string());
                            return -1;
                        };
                        let id: #id_ty = match serde_json::from_slice(id_bytes) {
                            Ok(v) => v,
                            Err(e) => {
                                set_error(err_out, FORGEDB_ERR_INVALID_ARG, format!("invalid id JSON: {e}"));
                                return -1;
                            }
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#delete_fn(id))) {
                            Ok(Ok(true)) => 1,
                            Ok(Ok(false)) => 0,
                            Ok(Err(e)) => {
                                set_error(err_out, FORGEDB_ERR_VALIDATION, e.to_string());
                                -1
                            }
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                -1
                            }
                        }
                    }
                }
            })
            .collect()
    }

    /// Generate the relation-traversal C-ABI getters.  Each one mirrors a
    /// generated `Database` traversal method **one-for-one** — same name, derived
    /// from the same schema in the same order (so the shared `seen` dedup here
    /// tracks `RustGenerator::generate_traversal_impl` exactly and we never emit a
    /// wrapper for a method that was deduped away).  Three families, all keyed on
    /// an id (never a runtime predicate — a fixed generated edge walk):
    ///   * **Forward FK** `forgedb_<model>_<field>(db, id, id_len, out, out_len, err)`
    ///     — fetch the source record by its id, resolve the `*Target`/`?Target` FK,
    ///     emit `Option<Target>` as JSON (`*out` null only if the source is absent);
    ///   * **Reverse 1:M** `forgedb_<parent>_<field>[_by_<child_field>](db, id, ...)`
    ///     — every child whose FK references the (UUID) parent id, as a JSON array;
    ///   * **M2M** `forgedb_link_<a>_<b>` / `forgedb_unlink_<a>_<b>` (both UUID ids)
    ///     + the query getters `forgedb_<a>_<field1>` / `forgedb_<b>_<field2>`
    ///     (linked records as a JSON array).
    ///
    /// The snapshot-scoped `_at` traversal + eager-load bundles are deferred to a
    /// later phase (they land here too).
    fn generate_relation_ops(schema: &Schema) -> Vec<proc_macro2::TokenStream> {
        use std::collections::{HashMap, HashSet};

        let mut ops = Vec::new();
        // ONE `seen` set spanning all three families, inserted in the SAME order
        // as `generate_traversal_impl`, so first-occurrence-wins agrees exactly.
        let mut seen: HashSet<String> = HashSet::new();

        // A `Vec`-returning getter over a decoded id: `forgedb_<name>(db, id, ...)`.
        let vec_getter = |sym: &proc_macro2::Ident,
                          id_ty: &proc_macro2::TokenStream,
                          call: proc_macro2::TokenStream,
                          doc: &str| {
            quote! {
                #[doc = #doc]
                ///
                /// # Safety
                /// `db` is a live handle; `id`/`id_len` a readable JSON id buffer;
                /// `out`/`out_len`/`err_out`, when non-null, writable.  On success
                /// `*out` is a JSON buffer freed with `forgedb_free_buffer`.
                #[unsafe(no_mangle)]
                pub unsafe extern "C" fn #sym(
                    db: *mut Db,
                    id: *const u8,
                    id_len: usize,
                    out: *mut *mut u8,
                    out_len: *mut usize,
                    err_out: *mut *mut ForgeError,
                ) -> bool {
                    clear_err(err_out);
                    if !out.is_null() { *out = ptr::null_mut(); }
                    if !out_len.is_null() { *out_len = 0; }
                    let Some(db) = db.as_ref() else {
                        set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                        return false;
                    };
                    let Some(id_bytes) = read_bytes(id, id_len) else {
                        set_error(err_out, FORGEDB_ERR_INVALID_ARG, "id buffer is null".to_string());
                        return false;
                    };
                    let id: #id_ty = match serde_json::from_slice(id_bytes) {
                        Ok(v) => v,
                        Err(e) => {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, format!("invalid id JSON: {e}"));
                            return false;
                        }
                    };
                    match catch_unwind(AssertUnwindSafe(|| #call)) {
                        Ok(value) => match serde_json::to_vec(&value) {
                            Ok(json) => { emit_bytes(json, out, out_len); true }
                            Err(e) => {
                                set_error(err_out, FORGEDB_ERR_IO, format!("serialize: {e}"));
                                false
                            }
                        },
                        Err(payload) => {
                            set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                            false
                        }
                    }
                }
            }
        };

        // --- A. Forward FK getters (`*Target` / `?Target`) --------------------
        for model in &schema.models {
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_has_id = model.fields.iter().any(|f| f.name == "id" || f.auto_generate);
            let id_ty = RustGenerator::id_type_tokens(model);
            let storage = format_ident!("{}", model_snake);
            for field in &model.fields {
                let target_name = match &field.field_type {
                    forgedb_parser::FieldType::Relation(
                        forgedb_parser::RelationType::RequiredReference(t),
                    )
                    | forgedb_parser::FieldType::Relation(
                        forgedb_parser::RelationType::OptionalReference(t),
                    ) => t,
                    _ => continue,
                };
                let Some(target) = schema.find_model(target_name) else { continue };
                if !RustGenerator::is_uuid_pk(target) {
                    continue;
                }
                let method_name = format!("{model_snake}_{}", field.name);
                if !seen.insert(method_name.clone()) {
                    continue;
                }
                // The FFI wrapper must fetch the source record by id, so it needs
                // the source model to be id-addressable.  A source without an
                // identity field still HAS the (record-by-ref) getter on Database,
                // but no C-ABI id path — skip its wrapper (seen already consumed,
                // matching the impl).
                if !model_has_id {
                    continue;
                }
                let method_ident = format_ident!("{}", method_name);
                let sym = format_ident!("forgedb_{}", method_name);
                let doc = format!(
                    "Resolve the `{}` foreign key of a `{}` (by id) to its record (JSON `Option`).",
                    field.name, model.name
                );
                ops.push(quote! {
                    #[doc = #doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `id`/`id_len` a readable JSON id
                    /// buffer; `out`/`out_len`/`err_out`, when non-null, writable.
                    /// `*out` is null iff the source record is absent; otherwise a
                    /// JSON buffer (`null` or the target) freed with
                    /// `forgedb_free_buffer`.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #sym(
                        db: *mut Db,
                        id: *const u8,
                        id_len: usize,
                        out: *mut *mut u8,
                        out_len: *mut usize,
                        err_out: *mut *mut ForgeError,
                    ) -> bool {
                        clear_err(err_out);
                        if !out.is_null() { *out = ptr::null_mut(); }
                        if !out_len.is_null() { *out_len = 0; }
                        let Some(db) = db.as_ref() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return false;
                        };
                        let Some(id_bytes) = read_bytes(id, id_len) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "id buffer is null".to_string());
                            return false;
                        };
                        let id: #id_ty = match serde_json::from_slice(id_bytes) {
                            Ok(v) => v,
                            Err(e) => {
                                set_error(err_out, FORGEDB_ERR_INVALID_ARG, format!("invalid id JSON: {e}"));
                                return false;
                            }
                        };
                        // Outer `Option` = source record present?  Inner (the
                        // getter's `Option<Target>`) = FK resolved?
                        match catch_unwind(AssertUnwindSafe(|| {
                            db.inner.#storage.get(id).map(|__rec| db.inner.#method_ident(&__rec))
                        })) {
                            Ok(Some(resolved)) => match serde_json::to_vec(&resolved) {
                                Ok(json) => { emit_bytes(json, out, out_len); true }
                                Err(e) => {
                                    set_error(err_out, FORGEDB_ERR_IO, format!("serialize: {e}"));
                                    false
                                }
                            },
                            // Source record absent: success with `*out` left null.
                            Ok(None) => true,
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                false
                            }
                        }
                    }
                });
            }
        }

        // --- B. Reverse one-to-many collection getters ------------------------
        let pairs = schema.detect_relations();
        let mut group_counts: HashMap<(String, String), usize> = HashMap::new();
        for p in &pairs {
            *group_counts
                .entry((p.parent_model.clone(), p.parent_field.clone()))
                .or_default() += 1;
        }
        for p in &pairs {
            let Some(parent) = schema.find_model(&p.parent_model) else { continue };
            if !RustGenerator::is_uuid_pk(parent) {
                continue;
            }
            let ambiguous = group_counts
                .get(&(p.parent_model.clone(), p.parent_field.clone()))
                .is_some_and(|&c| c > 1);
            let method_name = if ambiguous {
                format!(
                    "{}_{}_by_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field,
                    p.child_field
                )
            } else {
                format!("{}_{}", RustGenerator::to_snake_case(&p.parent_model), p.parent_field)
            };
            if !seen.insert(method_name.clone()) {
                continue;
            }
            let method_ident = format_ident!("{}", method_name);
            let sym = format_ident!("forgedb_{}", method_name);
            let id_ty = quote! { Uuid };
            let doc = format!(
                "All `{}` whose `{}` references the given `{}` id (JSON array).",
                p.child_model, p.child_field, p.parent_model
            );
            ops.push(vec_getter(&sym, &id_ty, quote! { db.inner.#method_ident(id) }, &doc));
        }

        // --- C. Many-to-many link / unlink + query getters --------------------
        for m in RustGenerator::valid_m2m(schema) {
            let snake1 = RustGenerator::to_snake_case(&m.model1);
            let snake2 = RustGenerator::to_snake_case(&m.model2);

            // link_<a>_<b>
            let link_name = format!("link_{snake1}_{snake2}");
            if seen.insert(link_name.clone()) {
                let link_ident = format_ident!("{}", link_name);
                let sym = format_ident!("forgedb_{}", link_name);
                let doc = format!("Link a `{}` (left) and a `{}` (right) in the junction.", m.model1, m.model2);
                ops.push(quote! {
                    #[doc = #doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `left`/`right` (+ their lens) readable
                    /// JSON UUID buffers; `err_out`, when non-null, writable.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #sym(
                        db: *mut Db,
                        left: *const u8,
                        left_len: usize,
                        right: *const u8,
                        right_len: usize,
                        err_out: *mut *mut ForgeError,
                    ) -> bool {
                        clear_err(err_out);
                        let Some(db) = db.as_mut() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return false;
                        };
                        let (Some(lb), Some(rb)) = (read_bytes(left, left_len), read_bytes(right, right_len)) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "left/right buffer is null".to_string());
                            return false;
                        };
                        let (Ok(left), Ok(right)) = (
                            serde_json::from_slice::<Uuid>(lb),
                            serde_json::from_slice::<Uuid>(rb),
                        ) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "invalid UUID JSON".to_string());
                            return false;
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#link_ident(left, right))) {
                            Ok(()) => true,
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                false
                            }
                        }
                    }
                });
            }

            // unlink_<a>_<b>
            let unlink_name = format!("unlink_{snake1}_{snake2}");
            if seen.insert(unlink_name.clone()) {
                let unlink_ident = format_ident!("{}", unlink_name);
                let sym = format_ident!("forgedb_{}", unlink_name);
                let doc = format!("Unlink a `{}` (left) / `{}` (right): 1 removed / 0 no-op / -1 error.", m.model1, m.model2);
                ops.push(quote! {
                    #[doc = #doc]
                    ///
                    /// # Safety
                    /// `db` is a live handle; `left`/`right` (+ their lens) readable
                    /// JSON UUID buffers; `err_out`, when non-null, writable.
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #sym(
                        db: *mut Db,
                        left: *const u8,
                        left_len: usize,
                        right: *const u8,
                        right_len: usize,
                        err_out: *mut *mut ForgeError,
                    ) -> i32 {
                        clear_err(err_out);
                        let Some(db) = db.as_mut() else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "db handle is null".to_string());
                            return -1;
                        };
                        let (Some(lb), Some(rb)) = (read_bytes(left, left_len), read_bytes(right, right_len)) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "left/right buffer is null".to_string());
                            return -1;
                        };
                        let (Ok(left), Ok(right)) = (
                            serde_json::from_slice::<Uuid>(lb),
                            serde_json::from_slice::<Uuid>(rb),
                        ) else {
                            set_error(err_out, FORGEDB_ERR_INVALID_ARG, "invalid UUID JSON".to_string());
                            return -1;
                        };
                        match catch_unwind(AssertUnwindSafe(|| db.inner.#unlink_ident(left, right))) {
                            Ok(true) => 1,
                            Ok(false) => 0,
                            Err(payload) => {
                                set_error(err_out, FORGEDB_ERR_PANIC, panic_message(payload));
                                -1
                            }
                        }
                    }
                });
            }

            // model1.field1 -> Vec<model2>  (forward M2M query)
            let fwd_name = format!("{snake1}_{}", m.field1);
            if seen.insert(fwd_name.clone()) {
                let fwd_ident = format_ident!("{}", fwd_name);
                let sym = format_ident!("forgedb_{}", fwd_name);
                let id_ty = quote! { Uuid };
                let doc = format!("All linked `{}` for the given `{}` id (JSON array).", m.model2, m.model1);
                ops.push(vec_getter(&sym, &id_ty, quote! { db.inner.#fwd_ident(id) }, &doc));

                // Mirror the impl's `_at` insert so subsequent `seen` state agrees
                // (the snapshot-scoped variant itself is deferred — not emitted).
                seen.insert(format!("{snake1}_{}_at", m.field1));
            }

            // model2.field2 -> Vec<model1>  (reverse M2M query)
            let rev_name = format!("{snake2}_{}", m.field2);
            if seen.insert(rev_name.clone()) {
                let rev_ident = format_ident!("{}", rev_name);
                let sym = format_ident!("forgedb_{}", rev_name);
                let id_ty = quote! { Uuid };
                let doc = format!("All linked `{}` for the given `{}` id (JSON array).", m.model1, m.model2);
                ops.push(vec_getter(&sym, &id_ty, quote! { db.inner.#rev_ident(id) }, &doc));
            }
        }

        ops
    }

    /// The `Cargo.toml` for the generated native FFI engine crate. User-editable
    /// config, so the CLI writes it ONLY when absent (like the wasm replica's
    /// `Cargo.toml` and the TS SDK's `package.json`).
    ///
    /// A `cdylib` (for the C-ABI `.so`/`.dylib`/`.dll` a binding `dlopen`s) plus
    /// an `rlib` (so a NAPI-RS/PyO3 wrapper crate can depend on it directly).
    /// `panic = "unwind"` is load-bearing: the entry points `catch_unwind` engine
    /// panics, so the profile must not be `panic = "abort"`.
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib: the C-ABI shared object a Python/Node/Bun binding loads.
# rlib:   so a NAPI-RS / PyO3 wrapper crate can link the engine directly.
crate-type = ["cdylib", "rlib"]

[dependencies]
forgedb-storage = "0.2"
forgedb-types = "0.2"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
forgedb-txn = "0.1"
forgedb-coordinator = "0.1"
forgedb-query-params = "0.1"
forgedb-auth = "0.1"
regex = "1"
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}

[profile.release]
# Load-bearing: the C-ABI entry points catch_unwind engine panics, so the
# release profile must unwind (not abort) for that boundary to hold.
panic = "unwind"
"#
        )
    }
}
