//! NAPI-RS language-binding generator (#52 Node / #117 Bun) — the ergonomic
//! JavaScript-runtime wrapper over the SAME generated `database.rs`, a sibling of
//! the PyO3 wrapper (`pyo3.rs`), the native FFI spine (`ffi.rs`), and the wasm
//! replica (`wasm.rs`).
//!
//! **Option A (Node + Bun unified).** Node and Bun both run Node-API, so a SINGLE
//! NAPI-RS crate → one `.node` artifact serves both (`generate node --runtime` and
//! `generate bun --runtime` emit identical code — any Node-vs-Bun difference is
//! packaging/loader glue, not a second binding). This is why there is one emitter,
//! not two.
//!
//! It emits a per-schema `#[napi]` surface: a `ForgeDb` class whose methods mirror
//! the generated `Database` CRUD **1:1**, calling the integrity wrappers
//! (`create_<m>`/`update_<m>`/`delete_<m>`) and storage reads (`get`/`row_count`/
//! `all`) by name.
//!
//! **Typed row structs (Phase 5b/6b follow-up).** Each identity model gets a
//! `#[napi(object)]` struct (`Napi<Model>`) with typed `pub` fields so napi-rs
//! auto-emits a fully-typed TypeScript interface in the `.d.ts`. Row-returning
//! methods (`get_<m>`, `all_<m>`, relation getters) return the typed struct (or
//! `Vec<struct>` / `Option<struct>`) instead of `JsUnknown`. Input methods
//! (`create_<m>`, `update_<m>`) continue to accept `JsUnknown` via the serde
//! bridge (`from_js_value`) — the existing single marshalling contract for input.
//!
//! Field-type mapping for `#[napi(object)]` matches the serde JSON wire shape so
//! values are identical whether reached through the typed or serde path:
//! `uuid`/`timestamp`→`i64`/`decimal`/`enum` serialize as strings in serde and are
//! typed `String` in the napi struct; `bool`/`f64`/`i32`/`i64`/`u32` are native;
//! `u64` is mapped to `i64` (serde emits a JSON number, napi `u64` would emit
//! `BigInt` — incompatible shapes); `json` uses `serde_json::Value`; `char(N)` uses
//! `Vec<u8>`. Virtual relation fields (`OneToMany`/`ManyToMany`) carry no stored
//! value and are excluded from the napi object.
//!
//! Identity: every schema-specific surface is generated per-model (constraint 2);
//! there is **no** generic `query`/`filter`/`predicate` entry point and no
//! `match model` dispatch (constraint 1). `Env::to_js_value` is schema-agnostic
//! (like `serde_json` in the FFI / `pythonize` in PyO3). The methods are named
//! from the schema, which IS the tailoring.

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::rust::RustGenerator;

pub struct NapiGenerator;

impl NapiGenerator {
    /// Generate the NAPI-RS wrapper (`napi/src/lib.rs`) for a schema.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let row_structs = Self::generate_row_structs(schema);
        let db_methods = Self::generate_db_methods(schema);
        let relation_methods = Self::generate_relation_methods(schema);
        let arrow_methods = Self::generate_arrow_methods(schema);

        let tokens = quote! {
            //! Generated by ForgeDB — Node/Bun binding (NAPI-RS, #52/#117).
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue: the ergonomic JavaScript surface over the
            //! generated `Database`. A `ForgeDb` whose methods mirror the generated
            //! CRUD 1:1. The tailored data logic lives in the generated
            //! `database.rs`; this file binds it. It invents no query API (the
            //! identity red line). Node and Bun share this ONE `.node` (Option A).
            #![allow(warnings)]

            mod database;

            use napi::bindgen_prelude::*;
            use napi::{Env, JsUnknown, Task};
            use napi_derive::napi;
            use std::panic::{AssertUnwindSafe, catch_unwind};
            use std::sync::{Arc, RwLock};

            use database::Database;
            // Names the primary-key type of UUID-keyed models (`id_type_tokens`
            // emits a bare `Uuid`); integer-PK models use std types.
            use forgedb_types::Uuid;

            /// Map any engine error (`ValidationError`, `io::Error`, …) to the
            /// JS-visible `napi::Error` (thrown as a JS `Error`).
            fn to_napi_err<E: std::fmt::Display>(e: E) -> Error {
                Error::from_reason(e.to_string())
            }

            /// Convert a caught panic payload into a `napi::Error` so an engine
            /// panic (e.g. the single-writer `DirLock`) never unwinds across the
            /// Node-API boundary as a raw abort.
            fn panic_to_napi_err(payload: Box<dyn std::any::Any + Send>) -> Error {
                let msg = payload
                    .downcast_ref::<&str>()
                    .map(|s| s.to_string())
                    .or_else(|| payload.downcast_ref::<String>().cloned())
                    .unwrap_or_else(|| "engine panic".to_string());
                Error::from_reason(msg)
            }

            /// A generic asynchronous engine op run on the libuv thread-pool.
            ///
            /// Holds a boxed closure that locks the shared `Arc<RwLock<Database>>`,
            /// runs exactly one engine call (panic-guarded), and yields its result
            /// as a `serde_json::Value` — all on the pool thread, so a slow op never
            /// blocks the JS event loop. `resolve` marshals that value to JS on the
            /// JS thread. Ops serialize on the single `RwLock`: read ops take a
            /// shared guard (concurrent), write ops the exclusive guard — the
            /// single-writer contract lives in the engine, not here (the async layer
            /// only avoids event-loop stalls and lets reads run in parallel; it never
            /// conjures write concurrency). Returned as an `AsyncTask` → a JS Promise.
            pub struct AsyncOp {
                op: Option<Box<dyn FnOnce() -> std::result::Result<serde_json::Value, String> + Send>>,
            }

            impl AsyncOp {
                fn new(
                    op: impl FnOnce() -> std::result::Result<serde_json::Value, String> + Send + 'static,
                ) -> Self {
                    Self { op: Some(Box::new(op)) }
                }
            }

            impl Task for AsyncOp {
                type Output = serde_json::Value;
                type JsValue = JsUnknown;

                fn compute(&mut self) -> Result<serde_json::Value> {
                    let op = self.op.take().expect("AsyncOp computed exactly once");
                    match catch_unwind(AssertUnwindSafe(move || op())) {
                        Ok(Ok(v)) => Ok(v),
                        Ok(Err(e)) => Err(Error::from_reason(e)),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                fn resolve(&mut self, env: Env, output: serde_json::Value) -> Result<JsUnknown> {
                    env.to_js_value(&output).map_err(to_napi_err)
                }
            }

            #(#row_structs)*

            /// A ForgeDB database handle — one single-writer process over a data
            /// directory. Methods mirror the generated `Database` surface 1:1.
            #[napi(js_name = "ForgeDb")]
            pub struct ForgeDb {
                // Shared behind an `RwLock` so async ops (which run on a libuv
                // pool thread) can hold the SAME single engine handle: read ops
                // take a shared guard and run concurrently, write ops the exclusive
                // guard. `Arc` lets each `AsyncOp` clone the handle onto its thread.
                inner: Arc<RwLock<Database>>,
            }

            #[napi]
            impl ForgeDb {
                /// Open (or create) the database at `root`. Holds the single-writer
                /// lock; a second writer throws rather than aborting the runtime.
                #[napi(factory)]
                pub fn open(root: String) -> Result<Self> {
                    let root = std::path::PathBuf::from(root);
                    match catch_unwind(AssertUnwindSafe(|| Database::open_at(root))) {
                        Ok(inner) => Ok(Self { inner: Arc::new(RwLock::new(inner)) }),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                /// Flush every column to disk (fsync on native).
                #[napi]
                pub fn commit(&self) -> Result<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.write().commit())) {
                        Ok(r) => r.map_err(to_napi_err),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                /// Force a WAL checkpoint (fsync columns, then truncate the WAL).
                #[napi]
                pub fn checkpoint(&self) -> Result<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.write().checkpoint())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                /// Reclaim dead (superseded/tombstoned) row versions in-process.
                /// Explicit only — never reached from a read path (constraint 4).
                #[napi]
                pub fn compact(&self) -> Result<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.write().compact())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                /// Flush every column to disk asynchronously (resolves to `null`).
                #[napi(js_name = "commitAsync")]
                pub fn commit_async(&self) -> AsyncTask<AsyncOp> {
                    let inner = self.inner.clone();
                    AsyncTask::new(AsyncOp::new(move || {
                        let mut db = inner.write().unwrap_or_else(|e| e.into_inner());
                        db.commit().map_err(|e| e.to_string())?;
                        Ok(serde_json::Value::Null)
                    }))
                }

                #(#db_methods)*

                #(#relation_methods)*

                #(#arrow_methods)*
            }

            impl ForgeDb {
                /// A shared (concurrent) read guard over the engine, recovering from
                /// a poisoned lock (a caught panic still poisons on unwind — every
                /// engine call is `catch_unwind`-wrapped, so the state is intact).
                fn read(&self) -> std::sync::RwLockReadGuard<'_, Database> {
                    self.inner.read().unwrap_or_else(|e| e.into_inner())
                }

                /// The exclusive write guard over the engine, with the same poison
                /// recovery as [`read`].
                fn write(&self) -> std::sync::RwLockWriteGuard<'_, Database> {
                    self.inner.write().unwrap_or_else(|e| e.into_inner())
                }
            }
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!(
                "Failed to parse generated NAPI-RS binding: {e}"
            ))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!("Node/Bun binding (NAPI-RS) ({} models)", schema.models.len()),
        })
    }

    /// The identity models a binding surface is generated for — those with an
    /// `id` field or an auto-generated PK (same filter as the FFI / PyO3 spines).
    fn identity_models(schema: &Schema) -> impl Iterator<Item = &forgedb_parser::Model> {
        schema
            .models
            .iter()
            .filter(|m| m.fields.iter().any(|f| f.name == "id" || f.auto_generate))
    }

    /// Whether a field type is a virtual relation (no stored column).
    fn is_virtual_relation(field_type: &forgedb_parser::FieldType) -> bool {
        use forgedb_parser::{FieldType, RelationType};
        matches!(
            field_type,
            FieldType::Relation(RelationType::OneToMany(_))
                | FieldType::Relation(RelationType::ManyToMany(_))
        )
    }

    /// The napi-object field type for a `.forge` field type, matching the serde
    /// JSON wire shape so values are identical through the typed and serde paths.
    ///
    /// * `uuid` → `String` (serde: hyphenated UUID string)
    /// * `timestamp` → `i64`  (serde: i64 seconds since epoch)
    /// * `decimal` → `String` (serde: decimal string via `serde-with-str`)
    /// * `enum(X)` → `String` (serde: variant name string)
    /// * `u64` → `i64`        (serde: JSON number — napi `u64` maps to `BigInt`,
    ///                          incompatible with the serde JSON-number wire shape)
    /// * `json` → `serde_json::Value` (napi serde-json feature handles the mapping)
    /// * `char(N)` → `Vec<u8>` (serde: array of u8; napi maps Vec<u8> → Buffer)
    /// * `struct` / complex → `serde_json::Value` (inline structs lack a
    ///    `#[napi(object)]` peer; marshal via the serde bridge as before)
    /// * Nullable/optional → `Option<inner_napi_type>`
    ///
    /// Returns `None` for virtual relation fields (no stored column → excluded).
    fn napi_field_type(schema: &Schema, field_type: &forgedb_parser::FieldType) -> Option<TokenStream> {
        use forgedb_parser::{FieldType, RelationType};
        match field_type {
            // Virtual relation fields carry no stored value.
            FieldType::Relation(RelationType::OneToMany(_))
            | FieldType::Relation(RelationType::ManyToMany(_)) => None,

            // Primitive numerics — native napi types.
            FieldType::U32 => Some(quote! { u32 }),
            // u64: serde emits a JSON number; napi `u64` maps to BigInt (different
            // wire shape). Map to i64 to stay wire-compatible.
            FieldType::U64 => Some(quote! { i64 }),
            FieldType::I32 => Some(quote! { i32 }),
            FieldType::I64 => Some(quote! { i64 }),
            FieldType::F64 => Some(quote! { f64 }),
            FieldType::Bool => Some(quote! { bool }),

            // String-typed fields. #238: an inline `string(N)` is a `String` in
            // the generated record and a string on every wire.
            FieldType::String | FieldType::StringN { .. } => Some(quote! { String }),

            // uuid serializes as a hyphenated string in serde.
            FieldType::Uuid => Some(quote! { String }),

            // timestamp (`forgedb_types::Timestamp` newtype over i64) serializes
            // as i64 in serde.
            FieldType::Timestamp => Some(quote! { i64 }),

            // decimal serializes as a string (serde-with-str feature).
            FieldType::Decimal => Some(quote! { String }),

            // enum serializes as its variant-name string in serde.
            FieldType::Enum(_) => Some(quote! { String }),

            // json is serde_json::Value — napi's serde-json feature handles it.
            FieldType::Json => Some(quote! { serde_json::Value }),

            // char(N) is [u8; N] in the generated struct; serde serializes as an
            // array of u8 integers; napi maps Vec<u8> to a JS Buffer.
            FieldType::Bytes(_) => Some(quote! { Vec<u8> }),

            // FixedArray — map element type recursively.
            FieldType::FixedArray(inner, _) => {
                let inner_ty = Self::napi_field_type(schema, inner)?;
                Some(quote! { Vec<#inner_ty> })
            }

            // Inline struct types — marshal via serde_json::Value (the struct
            // itself is not a `#[napi(object)]`; using Value preserves the serde
            // contract without requiring a parallel napi struct per embedded type).
            FieldType::StructType(_) | FieldType::OptionalStructType(_) => {
                Some(quote! { serde_json::Value })
            }

            // #266: an FK surfaces with the SAME JS type as the target's own
            // `id`. Hardcoding `String` compiled for a `u64` key and shipped an
            // object whose `post` was `"42"` beside a `Post.id` of `42`.
            FieldType::Relation(
                RelationType::RequiredReference(_) | RelationType::OptionalReference(_),
            ) => Self::napi_field_type(schema, &RustGenerator::resolved_type(schema, field_type)),

            // Nullable wraps the inner mapped type.
            FieldType::Nullable(inner) => {
                let inner_ty = Self::napi_field_type(schema, inner)?;
                Some(quote! { Option<#inner_ty> })
            }

            // Fallback — should not be reached for stored fields.
            _ => Some(quote! { serde_json::Value }),
        }
    }

    /// Generate the conversion expression from a `database::<Model>` field
    /// (`source.#field_name`) to the corresponding napi object field value.
    fn napi_field_conv(schema: &Schema, 
        field_type: &forgedb_parser::FieldType,
        field_name: &proc_macro2::Ident,
    ) -> TokenStream {
        use forgedb_parser::{FieldType, RelationType};
        match field_type {
            // Virtual relations have no column — excluded by the caller.
            FieldType::Relation(RelationType::OneToMany(_))
            | FieldType::Relation(RelationType::ManyToMany(_)) => quote! { () },

            // Native primitives — copy directly.
            FieldType::U32 | FieldType::I32 | FieldType::I64 | FieldType::F64 | FieldType::Bool => {
                quote! { __src.#field_name }
            }

            // u64 is mapped to i64 — cast (wrapping, but safe for realistic row
            // counts; the serde path also truncates via JSON number).
            FieldType::U64 => quote! { __src.#field_name as i64 },

            // String — clone (String → String). `string(N)` too (#238).
            FieldType::String | FieldType::StringN { .. } => {
                quote! { __src.#field_name.clone() }
            }

            // uuid → hyphenated string (matches serde's `Serialize for Uuid`).
            FieldType::Uuid => quote! { __src.#field_name.to_string() },

            // timestamp → i64 (the `Timestamp` newtype wraps i64; `From<Timestamp> for i64`).
            FieldType::Timestamp => quote! { i64::from(__src.#field_name) },

            // decimal → string (matches serde-with-str).
            FieldType::Decimal => quote! { __src.#field_name.to_string() },

            // enum → variant-name string (matches serde's default string repr).
            FieldType::Enum(_) => {
                quote! { serde_json::to_value(&__src.#field_name).unwrap_or_default().as_str().unwrap_or_default().to_string() }
            }

            // json → serde_json::Value (already that type in the generated struct).
            FieldType::Json => quote! { __src.#field_name.clone() },

            // char(N): [u8; N] → Vec<u8>.
            FieldType::Bytes(_) => quote! { __src.#field_name.to_vec() },

            // FixedArray: [T; N] → Vec<napi_type(T)>.
            FieldType::FixedArray(inner, _) => {
                let elem_conv = Self::napi_scalar_conv(inner, &quote! { __e });
                quote! { __src.#field_name.iter().map(|__e| #elem_conv).collect() }
            }

            // Inline struct → serde_json::Value via serde.
            FieldType::StructType(_) | FieldType::OptionalStructType(_) => {
                quote! { serde_json::to_value(&__src.#field_name).unwrap_or_default() }
            }

            // #266: convert through the target key's own arm, so the FK and the
            // target's `id` can never disagree.
            FieldType::Relation(
                RelationType::RequiredReference(_) | RelationType::OptionalReference(_),
            ) => Self::napi_field_conv(
                schema,
                &RustGenerator::resolved_type(schema, field_type),
                field_name,
            ),

            // Nullable(inner) → Option<inner_conv>.
            FieldType::Nullable(inner) => {
                let inner_conv = Self::napi_nullable_inner_conv(inner, field_name);
                quote! { #inner_conv }
            }

            _ => quote! { serde_json::to_value(&__src.#field_name).unwrap_or_default() },
        }
    }

    /// Conversion for the inner type of a nullable field expression
    /// (`__src.#field_name` is `Option<InnerType>`).
    fn napi_nullable_inner_conv(
        inner: &forgedb_parser::FieldType,
        field_name: &proc_macro2::Ident,
    ) -> TokenStream {
        use forgedb_parser::FieldType;
        match inner {
            FieldType::String | FieldType::StringN { .. } => {
                quote! { __src.#field_name.clone() }
            }
            FieldType::U32 | FieldType::I32 | FieldType::I64 | FieldType::F64 | FieldType::Bool => {
                quote! { __src.#field_name }
            }
            FieldType::U64 => quote! { __src.#field_name.map(|__v| __v as i64) },
            FieldType::Uuid => quote! { __src.#field_name.map(|__u| __u.to_string()) },
            FieldType::Timestamp => quote! { __src.#field_name.map(|__t| i64::from(__t)) },
            FieldType::Decimal => quote! { __src.#field_name.map(|__d| __d.to_string()) },
            FieldType::Enum(_) => {
                quote! {
                    __src.#field_name.as_ref().and_then(|__e|
                        serde_json::to_value(__e).ok()
                            .and_then(|__v| __v.as_str().map(|__s| __s.to_string()))
                    )
                }
            }
            FieldType::Json => quote! { __src.#field_name.clone() },
            FieldType::Bytes(_) => quote! { __src.#field_name.map(|__b| __b.to_vec()) },
            FieldType::StructType(_) | FieldType::OptionalStructType(_) => {
                quote! { __src.#field_name.as_ref().map(|__s| serde_json::to_value(__s).unwrap_or_default()) }
            }
            _ => quote! { __src.#field_name.as_ref().map(|__v| serde_json::to_value(__v).unwrap_or_default()) },
        }
    }

    /// Conversion for an element in a FixedArray (value expression `elem_expr`).
    fn napi_scalar_conv(inner: &forgedb_parser::FieldType, elem_expr: &TokenStream) -> TokenStream {
        use forgedb_parser::FieldType;
        match inner {
            FieldType::U32 | FieldType::I32 | FieldType::I64 | FieldType::F64 | FieldType::Bool => {
                quote! { *#elem_expr }
            }
            FieldType::U64 => quote! { *#elem_expr as i64 },
            FieldType::Uuid => quote! { #elem_expr.to_string() },
            _ => quote! { serde_json::to_value(#elem_expr).unwrap_or_default() },
        }
    }

    /// Per-identity-model `#[napi(object)]` typed row structs (`Napi<Model>`).
    ///
    /// Each struct has one `pub` field per stored model field (virtual relation
    /// fields are excluded — they carry no stored value). Field types match the
    /// serde JSON wire shape (see `napi_field_type` for the mapping). A
    /// `from_record` constructor converts `database::<Model>` → `Napi<Model>`.
    fn generate_row_structs(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let model_ident = format_ident!("{}", model.name);
                let napi_ident = format_ident!("Napi{}", model.name);
                let napi_name_str = model.name.as_str();
                let doc = format!("Typed `{}` row returned by `ForgeDb` read methods.", model.name);

                // Stored fields with their napi types.
                let fields: Vec<_> = model
                    .fields
                    .iter()
                    .filter(|f| !Self::is_virtual_relation(&f.field_type))
                    .filter_map(|f| {
                        let fname = format_ident!("{}", f.name);
                        let ty = Self::napi_field_type(schema, &f.field_type)?;
                        // Pin the JS key to the exact `.forge` field name. Without this,
                        // `#[napi(object)]` camelCases multi-word fields (`view_count` ->
                        // `viewCount`), which would diverge from the serde snake_case wire
                        // shape used by `create`/`update` input, REST, and the TS SDK.
                        let js_key = f.name.as_str();
                        Some(quote! {
                            #[napi(js_name = #js_key)]
                            pub #fname: #ty
                        })
                    })
                    .collect();

                // Conversion expressions from a `database::<Model>` value (__src).
                let conv_exprs: Vec<_> = model
                    .fields
                    .iter()
                    .filter(|f| !Self::is_virtual_relation(&f.field_type))
                    .filter_map(|f| {
                        let fname = format_ident!("{}", f.name);
                        let _ = Self::napi_field_type(schema, &f.field_type)?; // skip excluded
                        let conv = Self::napi_field_conv(schema, &f.field_type, &fname);
                        Some(quote! { #fname: #conv })
                    })
                    .collect();

                quote! {
                    #[doc = #doc]
                    #[napi(object, js_name = #napi_name_str)]
                    pub struct #napi_ident {
                        #(#fields),*
                    }

                    impl #napi_ident {
                        /// Convert a generated `database::<Model>` record into the
                        /// typed napi row struct, matching the serde JSON wire shape.
                        fn from_record(__src: &database::#model_ident) -> Self {
                            Self {
                                #(#conv_exprs),*
                            }
                        }
                    }
                }
            })
            .collect()
    }

    /// The per-model CRUD methods on `ForgeDb`, mirroring the generated `Database`
    /// integrity wrappers + storage reads 1:1.
    ///
    /// `get_<m>` and `all_<m>` return the typed `Napi<Model>` struct (or
    /// `Option<Napi<Model>>` / `Vec<Napi<Model>>`). `create_<m>` and `update_<m>`
    /// continue to accept `JsUnknown` via the serde bridge — one marshalling contract
    /// for input, typed output.
    fn generate_db_methods(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let snake = RustGenerator::to_snake_case(&model.name);
                let model_ident = format_ident!("{}", model.name);
                let napi_ident = format_ident!("Napi{}", model.name);
                let storage = format_ident!("{}", snake);
                let id_ty = RustGenerator::id_type_tokens(schema, model);

                let create_fn = format_ident!("create_{}", snake);
                let update_fn = format_ident!("update_{}", snake);
                let delete_fn = format_ident!("delete_{}", snake);

                let create_m = format_ident!("create_{}", snake);
                let get_m = format_ident!("get_{}", snake);
                let all_m = format_ident!("all_{}", snake);
                let count_m = format_ident!("count_{}", snake);
                let update_m = format_ident!("update_{}", snake);
                let delete_m = format_ident!("delete_{}", snake);

                // Async (Promise-returning) variants. `js_name` gives them a camelCase
                // JS name (`createUserAsync`); the Rust ident stays snake for clarity.
                let create_async_m = format_ident!("create_{}_async", snake);
                let get_async_m = format_ident!("get_{}_async", snake);
                let all_async_m = format_ident!("all_{}_async", snake);
                let update_async_m = format_ident!("update_{}_async", snake);
                let delete_async_m = format_ident!("delete_{}_async", snake);
                let create_async_js = format!("create{}Async", model.name);
                let get_async_js = format!("get{}Async", model.name);
                let all_async_js = format!("all{}Async", model.name);
                let update_async_js = format!("update{}Async", model.name);
                let delete_async_js = format!("delete{}Async", model.name);

                let create_doc = format!(
                    "Insert a `{}` (FK-checked + validated); returns the new id.",
                    model.name
                );
                let get_doc =
                    format!("Fetch a `{}` by id, or `null` if absent.", model.name);
                let all_doc = format!("Every live `{}`.", model.name);
                let count_doc = format!("Physical `{}` row-count watermark.", model.name);
                let update_doc = format!(
                    "Update a `{}` by id; `true` if present, `false` if absent.",
                    model.name
                );
                let delete_doc = format!(
                    "Delete a `{}` by id (referential integrity enforced); `true`/`false`.",
                    model.name
                );

                quote! {
                    #[doc = #create_doc]
                    #[napi]
                    pub fn #create_m(&self, env: Env, record: JsUnknown) -> Result<JsUnknown> {
                        let record: database::#model_ident =
                            env.from_js_value(record).map_err(to_napi_err)?;
                        let id = match catch_unwind(AssertUnwindSafe(|| self.write().#create_fn(record))) {
                            Ok(r) => r.map_err(to_napi_err)?,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        env.to_js_value(&id).map_err(to_napi_err)
                    }

                    #[doc = #get_doc]
                    #[napi]
                    pub fn #get_m(&self, env: Env, id: JsUnknown) -> Result<Option<#napi_ident>> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let opt = match catch_unwind(AssertUnwindSafe(|| self.read().#storage.get(id))) {
                            Ok(opt) => opt,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        Ok(opt.as_ref().map(#napi_ident::from_record))
                    }

                    #[doc = #all_doc]
                    #[napi]
                    pub fn #all_m(&self) -> Result<Vec<#napi_ident>> {
                        let rows = match catch_unwind(AssertUnwindSafe(|| self.read().#storage.all())) {
                            Ok(rows) => rows,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        Ok(rows.iter().map(#napi_ident::from_record).collect())
                    }

                    #[doc = #count_doc]
                    #[napi]
                    pub fn #count_m(&self) -> Result<i64> {
                        match catch_unwind(AssertUnwindSafe(|| self.read().#storage.row_count())) {
                            Ok(n) => Ok(n as i64),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }

                    #[doc = #update_doc]
                    #[napi]
                    pub fn #update_m(
                        &self,
                        env: Env,
                        id: JsUnknown,
                        record: JsUnknown,
                    ) -> Result<bool> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let record: database::#model_ident =
                            env.from_js_value(record).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.write().#update_fn(id, record))) {
                            Ok(r) => r.map_err(to_napi_err),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }

                    #[doc = #delete_doc]
                    #[napi]
                    pub fn #delete_m(&self, env: Env, id: JsUnknown) -> Result<bool> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.write().#delete_fn(id))) {
                            Ok(r) => r.map_err(to_napi_err),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }

                    // --- Async (Promise-returning) CRUD variants ------------------
                    // Args decode on the JS thread; the engine call runs on a libuv
                    // pool thread under the shared lock (reads concurrent, writes
                    // exclusive) and yields serde JSON, so a slow op never stalls the
                    // event loop. These resolve to the JSON shape (snake_case, same as
                    // the sync serde bridge) — typed async structs are a follow-up.
                    #[doc = "Async insert; resolves to the new id."]
                    #[napi(js_name = #create_async_js)]
                    pub fn #create_async_m(&self, env: Env, record: JsUnknown) -> Result<AsyncTask<AsyncOp>> {
                        let record: database::#model_ident =
                            env.from_js_value(record).map_err(to_napi_err)?;
                        let inner = self.inner.clone();
                        Ok(AsyncTask::new(AsyncOp::new(move || {
                            let mut db = inner.write().unwrap_or_else(|e| e.into_inner());
                            let id = db.#create_fn(record).map_err(|e| e.to_string())?;
                            serde_json::to_value(&id).map_err(|e| e.to_string())
                        })))
                    }

                    #[doc = "Async fetch by id; resolves to the row or `null`."]
                    #[napi(js_name = #get_async_js)]
                    pub fn #get_async_m(&self, env: Env, id: JsUnknown) -> Result<AsyncTask<AsyncOp>> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let inner = self.inner.clone();
                        Ok(AsyncTask::new(AsyncOp::new(move || {
                            let db = inner.read().unwrap_or_else(|e| e.into_inner());
                            let opt = db.#storage.get(id);
                            serde_json::to_value(&opt).map_err(|e| e.to_string())
                        })))
                    }

                    #[doc = "Async list of every live row."]
                    #[napi(js_name = #all_async_js)]
                    pub fn #all_async_m(&self) -> AsyncTask<AsyncOp> {
                        let inner = self.inner.clone();
                        AsyncTask::new(AsyncOp::new(move || {
                            let db = inner.read().unwrap_or_else(|e| e.into_inner());
                            let rows = db.#storage.all();
                            serde_json::to_value(&rows).map_err(|e| e.to_string())
                        }))
                    }

                    #[doc = "Async update by id; resolves to `true`/`false`."]
                    #[napi(js_name = #update_async_js)]
                    pub fn #update_async_m(&self, env: Env, id: JsUnknown, record: JsUnknown) -> Result<AsyncTask<AsyncOp>> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let record: database::#model_ident =
                            env.from_js_value(record).map_err(to_napi_err)?;
                        let inner = self.inner.clone();
                        Ok(AsyncTask::new(AsyncOp::new(move || {
                            let mut db = inner.write().unwrap_or_else(|e| e.into_inner());
                            let ok = db.#update_fn(id, record).map_err(|e| e.to_string())?;
                            serde_json::to_value(ok).map_err(|e| e.to_string())
                        })))
                    }

                    #[doc = "Async delete by id; resolves to `true`/`false`."]
                    #[napi(js_name = #delete_async_js)]
                    pub fn #delete_async_m(&self, env: Env, id: JsUnknown) -> Result<AsyncTask<AsyncOp>> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let inner = self.inner.clone();
                        Ok(AsyncTask::new(AsyncOp::new(move || {
                            let mut db = inner.write().unwrap_or_else(|e| e.into_inner());
                            let ok = db.#delete_fn(id).map_err(|e| e.to_string())?;
                            serde_json::to_value(ok).map_err(|e| e.to_string())
                        })))
                    }
                }
            })
            .collect()
    }

    /// The relation-traversal methods on `ForgeDb`, mirroring the generated
    /// `Database` traversal getters **one-for-one** — same names, derived from the
    /// same schema in the same order, sharing a `seen` dedup set that tracks
    /// `RustGenerator::generate_traversal_impl` exactly (so a method is never
    /// emitted for a getter that was deduped away). Three families, all id-keyed
    /// (a fixed generated edge walk, never a runtime predicate):
    ///   * **Forward FK** `<model>_<field>(id) -> Option<Napi<Target>>`;
    ///   * **Reverse 1:M** `<parent>_<field>[_by_<child_field>](id) -> Vec<Napi<Child>>`;
    ///   * **M2M** `link_<a>_<b>(l, r)` / `unlink_<a>_<b>(l, r) -> bool` + the query
    ///     getters `<a>_<field1>(id) -> Vec<Napi<B>>` / `<b>_<field2>(id) -> Vec<Napi<A>>`.
    ///
    /// Row-returning methods return typed `Napi<Model>` structs. Identity: no generic
    /// query surface — each getter is a fixed, generated edge walk by name.
    fn generate_relation_methods(schema: &Schema) -> Vec<TokenStream> {
        use forgedb_parser::{FieldType, RelationType};
        use std::collections::{HashMap, HashSet};

        let mut methods = Vec::new();
        // ONE `seen` set spanning all three families, inserted in the SAME order as
        // `generate_traversal_impl`, so first-occurrence-wins agrees exactly.
        let mut seen: HashSet<String> = HashSet::new();

        // --- A. Forward FK getters (`*Target` / `?Target`) --------------------
        for model in &schema.models {
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_has_id = model.fields.iter().any(|f| f.name == "id" || f.auto_generate);
            let source_id_ty = RustGenerator::id_type_tokens(schema, model);
            let storage = format_ident!("{}", model_snake);
            for field in &model.fields {
                let target_name = match &field.field_type {
                    FieldType::Relation(RelationType::RequiredReference(t))
                    | FieldType::Relation(RelationType::OptionalReference(t)) => t,
                    _ => continue,
                };
                let Some(target) = schema.find_model(target_name) else {
                    continue;
                };
                let method_name = format!("{model_snake}_{}", field.name);
                if !seen.insert(method_name.clone()) {
                    continue;
                }
                // Needs the source id-addressable (to `get` it before resolving the
                // FK); the target marshals via the typed napi struct. The `seen` slot
                // is consumed either way, matching the impl's ordering.
                if !model_has_id {
                    continue;
                }
                let method_ident = format_ident!("{}", method_name);
                let napi_target = format_ident!("Napi{}", target.name);
                let doc = format!(
                    "Resolve the `{}` foreign key of a `{}` (by id) to its record, or `null`.",
                    field.name, model.name
                );
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #method_ident(&self, env: Env, id: JsUnknown) -> Result<Option<#napi_target>> {
                        let id: #source_id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let resolved = match catch_unwind(AssertUnwindSafe(|| {
                            // ONE read guard for both hops — two `self.read()` calls
                            // in a single expression could same-thread deadlock.
                            let __db = self.read();
                            __db.#storage.get(id).and_then(|__rec| __db.#method_ident(&__rec))
                        })) {
                            Ok(opt) => opt,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        Ok(resolved.as_ref().map(#napi_target::from_record))
                    }
                });
            }
        }

        // --- B. Reverse one-to-many collection getters ------------------------
        let pairs = schema.detect_relations();
        let mut group_counts: HashMap<(String, String), usize> = HashMap::new();
        for p in &pairs {
            *group_counts
                .entry((p.parent_model.clone(), p.parent_field.clone()))
                .or_default() += 1;
        }
        for p in &pairs {
            let Some(parent) = schema.find_model(&p.parent_model) else {
                continue;
            };
            let ambiguous = group_counts
                .get(&(p.parent_model.clone(), p.parent_field.clone()))
                .is_some_and(|&c| c > 1);
            let method_name = if ambiguous {
                format!(
                    "{}_{}_by_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field,
                    p.child_field
                )
            } else {
                format!("{}_{}", RustGenerator::to_snake_case(&p.parent_model), p.parent_field)
            };
            if !seen.insert(method_name.clone()) {
                continue;
            }
            let Some(child) = schema.find_model(&p.child_model) else {
                continue;
            };
            let method_ident = format_ident!("{}", method_name);
            let napi_child = format_ident!("Napi{}", child.name);
            // #266: the id arrives as the PARENT's own key type.
            let parent_id_ty = RustGenerator::id_type_tokens(schema, parent);
            let doc = format!(
                "All `{}` whose `{}` references the given `{}` id.",
                p.child_model, p.child_field, p.parent_model
            );
            methods.push(quote! {
                #[doc = #doc]
                #[napi]
                pub fn #method_ident(&self, env: Env, id: JsUnknown) -> Result<Vec<#napi_child>> {
                    let id: #parent_id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                    let rows = match catch_unwind(AssertUnwindSafe(|| self.read().#method_ident(id))) {
                        Ok(rows) => rows,
                        Err(p) => return Err(panic_to_napi_err(p)),
                    };
                    Ok(rows.iter().map(#napi_child::from_record).collect())
                }
            });
        }

        // --- C. Many-to-many link / unlink + query getters --------------------
        for m in RustGenerator::valid_m2m(schema) {
            let snake1 = RustGenerator::to_snake_case(&m.model1);
            let snake2 = RustGenerator::to_snake_case(&m.model2);

            // link_<a>_<b>
            let link_name = format!("link_{snake1}_{snake2}");
            if seen.insert(link_name.clone()) {
                let link_ident = format_ident!("{}", link_name);
                let doc = format!("Link a `{}` (left) and a `{}` (right) in the junction.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #link_ident(&self, env: Env, left: JsUnknown, right: JsUnknown) -> Result<()> {
                        let left: Uuid = env.from_js_value(left).map_err(to_napi_err)?;
                        let right: Uuid = env.from_js_value(right).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.write().#link_ident(left, right))) {
                            Ok(()) => Ok(()),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }
                });
            }

            // unlink_<a>_<b>
            let unlink_name = format!("unlink_{snake1}_{snake2}");
            if seen.insert(unlink_name.clone()) {
                let unlink_ident = format_ident!("{}", unlink_name);
                let doc = format!("Unlink a `{}` (left) / `{}` (right); `true` if a pair was removed.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #unlink_ident(&self, env: Env, left: JsUnknown, right: JsUnknown) -> Result<bool> {
                        let left: Uuid = env.from_js_value(left).map_err(to_napi_err)?;
                        let right: Uuid = env.from_js_value(right).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.write().#unlink_ident(left, right))) {
                            Ok(removed) => Ok(removed),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }
                });
            }

            // model1.field1 -> Vec<Napi<model2>>  (forward M2M query)
            let fwd_name = format!("{snake1}_{}", m.field1);
            if seen.insert(fwd_name.clone()) {
                let fwd_ident = format_ident!("{}", fwd_name);
                let napi_b = format_ident!("Napi{}", m.model2);
                let doc = format!("All linked `{}` for the given `{}` id.", m.model2, m.model1);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #fwd_ident(&self, env: Env, id: JsUnknown) -> Result<Vec<#napi_b>> {
                        let id: Uuid = env.from_js_value(id).map_err(to_napi_err)?;
                        let rows = match catch_unwind(AssertUnwindSafe(|| self.read().#fwd_ident(id))) {
                            Ok(rows) => rows,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        Ok(rows.iter().map(#napi_b::from_record).collect())
                    }
                });
            }

            // model2.field2 -> Vec<Napi<model1>>  (reverse M2M query)
            let rev_name = format!("{snake2}_{}", m.field2);
            if seen.insert(rev_name.clone()) {
                let rev_ident = format_ident!("{}", rev_name);
                let napi_a = format_ident!("Napi{}", m.model1);
                let doc = format!("All linked `{}` for the given `{}` id.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #rev_ident(&self, env: Env, id: JsUnknown) -> Result<Vec<#napi_a>> {
                        let id: Uuid = env.from_js_value(id).map_err(to_napi_err)?;
                        let rows = match catch_unwind(AssertUnwindSafe(|| self.read().#rev_ident(id))) {
                            Ok(rows) => rows,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        Ok(rows.iter().map(#napi_a::from_record).collect())
                    }
                });
            }
        }

        methods
    }

    /// The per-(model, exportable-column) Arrow export methods on `ForgeDb` — the
    /// zero-copy selling point (#52/#117). `<m>_<col>_arrow() -> { buffer, format,
    /// length }` where `buffer` is an **external `ArrayBuffer`** aliasing the live
    /// column bytes zero-copy (`napi_create_external_arraybuffer` over the private
    /// column's `ColumnExport` — an `mmap` alias of the on-disk column when the
    /// live rows are a dense prefix, a gathered copy otherwise; transparent). The
    /// backing is freed when the `ArrayBuffer` is GC'd (the finalize drops the
    /// `ColumnExport`). `format` is the Arrow C-Data format string (`l`/`g`/`I`/…),
    /// `length` the row count — so a thin JS helper builds an `arrow-js` `Vector`
    /// (`new Int64Array(buffer)` etc.) with no per-row copy.
    ///
    /// The exportable set + format come from `RustGenerator::arrow_export_format`
    /// (the SAME source of truth as `export_col_<f>` and the FFI Arrow op), so they
    /// can never drift. Identity: the set is fixed by the schema at codegen time
    /// (never a runtime column list); the export takes opaque row indices.
    fn generate_arrow_methods(schema: &Schema) -> Vec<TokenStream> {
        let mut methods = Vec::new();
        for model in Self::identity_models(schema) {
            let snake = RustGenerator::to_snake_case(&model.name);
            let storage = format_ident!("{}", snake);
            for field in &model.fields {
                let Some(fmt) = RustGenerator::arrow_export_format(schema, &field.field_type) else {
                    continue;
                };
                let method_ident = format_ident!("{}_{}_arrow", snake, field.name);
                let export_method = format_ident!("export_col_{}", field.name);
                let doc = format!(
                    "Export the live `{}.{}` column as a zero-copy Arrow buffer (`{}`) — \
                     `{{ buffer: ArrayBuffer, format, length }}`.",
                    model.name, field.name, fmt
                );
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #method_ident(&self, env: Env) -> Result<JsUnknown> {
                        let (export, length) = match catch_unwind(AssertUnwindSafe(|| {
                            let __db = self.read();
                            let live = __db.#storage.export_live_indices();
                            let n = live.len();
                            __db.#storage.#export_method(&live).map(|e| (e, n))
                        })) {
                            Ok(Ok(pair)) => pair,
                            Ok(Err(e)) => return Err(to_napi_err(e)),
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        // Zero-copy: alias the export's backing into an external
                        // ArrayBuffer; the finalize drops the `ColumnExport` (freeing
                        // the copy or `munmap`ing the alias) when the buffer is GC'd.
                        let data_ptr = export.as_ptr() as *mut u8;
                        let byte_len = export.len();
                        let ab = unsafe {
                            env.create_arraybuffer_with_borrowed_data(
                                data_ptr,
                                byte_len,
                                export,
                                |_export: forgedb_storage::ColumnExport, _env: Env| {},
                            )
                        }.map_err(to_napi_err)?;
                        let mut obj = env.create_object().map_err(to_napi_err)?;
                        obj.set_named_property("buffer", ab.into_raw()).map_err(to_napi_err)?;
                        obj.set_named_property("format", #fmt).map_err(to_napi_err)?;
                        obj.set_named_property("length", length as u32).map_err(to_napi_err)?;
                        Ok(obj.into_unknown())
                    }
                });
            }
        }
        methods
    }

    /// The NAPI-RS crate's `Cargo.toml`. User-editable config — written only when
    /// absent, mirroring the FFI / PyO3 / wasm scaffolds. A `cdylib` (the `.node`
    /// addon `require()`d by both Node and Bun); `napi`'s `serde-json` feature
    /// drives the `Env::to_js_value`/`from_js_value` marshalling; `panic = "unwind"`
    /// is load-bearing (the methods `catch_unwind` engine panics).
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib: the Node-API addon (`.node`) both Node and Bun load (Option A).
name = "forgedb"
crate-type = ["cdylib"]

[dependencies]
forgedb-storage = "0.2"
forgedb-types = "0.2"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
forgedb-txn = "0.1"
forgedb-coordinator = "0.2"
forgedb-query-params = "0.1"
regex = "1"
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}
napi = {{ version = "2", default-features = false, features = ["napi8", "serde-json"] }}
napi-derive = "2"

[build-dependencies]
napi-build = "2"

[profile.release]
# Load-bearing: the Node-API entry points catch_unwind engine panics, so the
# release profile must unwind (not abort) for that boundary to hold.
panic = "unwind"
"#
        )
    }

    /// The NAPI-RS `build.rs` (schema-invariant). `napi_build::setup()` wires the
    /// platform linker args (incl. macOS `-undefined dynamic_lookup` so the
    /// `.node` resolves Node-API symbols at load time), so a plain `cargo build`
    /// links standalone — the compile-test path.
    pub fn build_rs_scaffold() -> &'static str {
        "// Generated by ForgeDB — NAPI-RS build script (schema-invariant).\n\
         fn main() {\n    \
         napi_build::setup();\n\
         }\n"
    }

    /// The `package.json` for the generated binding — makes `@napi-rs/cli` the
    /// blessed build path (`napi build` → the `.node` + a generated `index.js`
    /// loader + `index.d.ts`). User-editable — written only when absent.
    pub fn package_json_scaffold() -> &'static str {
        r#"{
  "name": "forgedb",
  "version": "0.1.0",
  "description": "Generated ForgeDB Node/Bun binding (NAPI-RS)",
  "main": "index.js",
  "types": "index.d.ts",
  "napi": {
    "name": "forgedb"
  },
  "scripts": {
    "build": "napi build --platform --release",
    "build:debug": "napi build --platform"
  },
  "devDependencies": {
    "@napi-rs/cli": "^2.18.0"
  }
}
"#
    }
}
