//! NAPI-RS language-binding generator (#52 Node / #117 Bun) — the ergonomic
//! JavaScript-runtime wrapper over the SAME generated `database.rs`, a sibling of
//! the PyO3 wrapper (`pyo3.rs`), the native FFI spine (`ffi.rs`), and the wasm
//! replica (`wasm.rs`).
//!
//! **Option A (Node + Bun unified).** Node and Bun both run Node-API, so a SINGLE
//! NAPI-RS crate → one `.node` artifact serves both (`generate node --runtime` and
//! `generate bun --runtime` emit identical code — any Node-vs-Bun difference is
//! packaging/loader glue, not a second binding). This is why there is one emitter,
//! not two.
//!
//! It emits a per-schema `#[napi]` surface: a `ForgeDb` class whose methods mirror
//! the generated `Database` CRUD **1:1**, calling the integrity wrappers
//! (`create_<m>`/`update_<m>`/`delete_<m>`) and storage reads (`get`/`row_count`/
//! `all`) by name.
//!
//! **Marshalling (design deviation, documented — mirrors the PyO3 wrapper).** The
//! design pinned `#[napi(object)]` typed row structs ("native marshalling, no
//! serialization"); v1 instead marshals rows/ids through the generated struct's
//! **own serde impl via `Env::to_js_value`/`from_js_value`** (the napi `serde-json`
//! feature — serde↔JS value, *not* a JSON string). The caller gets native JS
//! objects, and there is exactly ONE marshalling contract (the same serde the
//! WAL / broker / FFI / PyO3 paths use), so no second per-field matrix can drift.
//! Typed `#[napi(object)]` rows (per-field native marshalling + a fully-typed
//! `.d.ts` for row shapes) are a strict ergonomic follow-up, exactly like the
//! typed-field `#[pyclass]` follow-up on the Python side.
//!
//! Identity: every schema-specific surface is generated per-model (constraint 2);
//! there is **no** generic `query`/`filter`/`predicate` entry point and no
//! `match model` dispatch (constraint 1). `Env::to_js_value` is schema-agnostic
//! (like `serde_json` in the FFI / `pythonize` in PyO3). The methods are named
//! from the schema, which IS the tailoring.

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::rust::RustGenerator;

pub struct NapiGenerator;

impl NapiGenerator {
    /// Generate the NAPI-RS wrapper (`napi/src/lib.rs`) for a schema.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let db_methods = Self::generate_db_methods(schema);
        let relation_methods = Self::generate_relation_methods(schema);

        let tokens = quote! {
            //! Generated by ForgeDB — Node/Bun binding (NAPI-RS, #52/#117).
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue: the ergonomic JavaScript surface over the
            //! generated `Database`. A `ForgeDb` whose methods mirror the generated
            //! CRUD 1:1. The tailored data logic lives in the generated
            //! `database.rs`; this file binds it. It invents no query API (the
            //! identity red line). Node and Bun share this ONE `.node` (Option A).
            #![allow(warnings)]

            mod database;

            use napi::bindgen_prelude::*;
            use napi::{Env, JsUnknown};
            use napi_derive::napi;
            use std::panic::{AssertUnwindSafe, catch_unwind};

            use database::Database;
            // Names the primary-key type of UUID-keyed models (`id_type_tokens`
            // emits a bare `Uuid`); integer-PK models use std types.
            use forgedb_types::Uuid;

            /// Map any engine error (`ValidationError`, `io::Error`, …) to the
            /// JS-visible `napi::Error` (thrown as a JS `Error`).
            fn to_napi_err<E: std::fmt::Display>(e: E) -> Error {
                Error::from_reason(e.to_string())
            }

            /// Convert a caught panic payload into a `napi::Error` so an engine
            /// panic (e.g. the single-writer `DirLock`) never unwinds across the
            /// Node-API boundary as a raw abort.
            fn panic_to_napi_err(payload: Box<dyn std::any::Any + Send>) -> Error {
                let msg = payload
                    .downcast_ref::<&str>()
                    .map(|s| s.to_string())
                    .or_else(|| payload.downcast_ref::<String>().cloned())
                    .unwrap_or_else(|| "engine panic".to_string());
                Error::from_reason(msg)
            }

            /// A ForgeDB database handle — one single-writer process over a data
            /// directory. Methods mirror the generated `Database` surface 1:1.
            #[napi(js_name = "ForgeDb")]
            pub struct ForgeDb {
                inner: Database,
            }

            #[napi]
            impl ForgeDb {
                /// Open (or create) the database at `root`. Holds the single-writer
                /// lock; a second writer throws rather than aborting the runtime.
                #[napi(factory)]
                pub fn open(root: String) -> Result<Self> {
                    let root = std::path::PathBuf::from(root);
                    match catch_unwind(AssertUnwindSafe(|| Database::open_at(root))) {
                        Ok(inner) => Ok(Self { inner }),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                /// Flush every column to disk (fsync on native).
                #[napi]
                pub fn commit(&mut self) -> Result<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.commit())) {
                        Ok(r) => r.map_err(to_napi_err),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                /// Force a WAL checkpoint (fsync columns, then truncate the WAL).
                #[napi]
                pub fn checkpoint(&mut self) -> Result<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.checkpoint())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                /// Reclaim dead (superseded/tombstoned) row versions in-process.
                /// Explicit only — never reached from a read path (constraint 4).
                #[napi]
                pub fn compact(&mut self) -> Result<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.compact())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_napi_err(p)),
                    }
                }

                #(#db_methods)*

                #(#relation_methods)*
            }
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!(
                "Failed to parse generated NAPI-RS binding: {e}"
            ))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!("Node/Bun binding (NAPI-RS) ({} models)", schema.models.len()),
        })
    }

    /// The identity models a binding surface is generated for — those with an
    /// `id` field or an auto-generated PK (same filter as the FFI / PyO3 spines).
    fn identity_models(schema: &Schema) -> impl Iterator<Item = &forgedb_parser::Model> {
        schema
            .models
            .iter()
            .filter(|m| m.fields.iter().any(|f| f.name == "id" || f.auto_generate))
    }

    /// The per-model CRUD methods on `ForgeDb`, mirroring the generated `Database`
    /// integrity wrappers + storage reads 1:1. Rows/ids marshal through the
    /// generated struct's serde via `Env::to_js_value`/`from_js_value` (native JS
    /// objects, one source of truth — no second per-field matrix).
    fn generate_db_methods(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let snake = RustGenerator::to_snake_case(&model.name);
                let model_ident = format_ident!("{}", model.name);
                let storage = format_ident!("{}", snake);
                let id_ty = RustGenerator::id_type_tokens(model);

                let create_fn = format_ident!("create_{}", snake);
                let update_fn = format_ident!("update_{}", snake);
                let delete_fn = format_ident!("delete_{}", snake);

                let create_m = format_ident!("create_{}", snake);
                let get_m = format_ident!("get_{}", snake);
                let all_m = format_ident!("all_{}", snake);
                let count_m = format_ident!("count_{}", snake);
                let update_m = format_ident!("update_{}", snake);
                let delete_m = format_ident!("delete_{}", snake);

                let create_doc = format!(
                    "Insert a `{}` (FK-checked + validated); returns the new id.",
                    model.name
                );
                let get_doc =
                    format!("Fetch a `{}` by id, or `null` if absent.", model.name);
                let all_doc = format!("Every live `{}`.", model.name);
                let count_doc = format!("Physical `{}` row-count watermark.", model.name);
                let update_doc = format!(
                    "Update a `{}` by id; `true` if present, `false` if absent.",
                    model.name
                );
                let delete_doc = format!(
                    "Delete a `{}` by id (referential integrity enforced); `true`/`false`.",
                    model.name
                );

                quote! {
                    #[doc = #create_doc]
                    #[napi]
                    pub fn #create_m(&mut self, env: Env, record: JsUnknown) -> Result<JsUnknown> {
                        let record: database::#model_ident =
                            env.from_js_value(record).map_err(to_napi_err)?;
                        let id = match catch_unwind(AssertUnwindSafe(|| self.inner.#create_fn(record))) {
                            Ok(r) => r.map_err(to_napi_err)?,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        env.to_js_value(&id).map_err(to_napi_err)
                    }

                    #[doc = #get_doc]
                    #[napi]
                    pub fn #get_m(&self, env: Env, id: JsUnknown) -> Result<JsUnknown> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let opt = match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.get(id))) {
                            Ok(opt) => opt,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        env.to_js_value(&opt).map_err(to_napi_err)
                    }

                    #[doc = #all_doc]
                    #[napi]
                    pub fn #all_m(&self, env: Env) -> Result<JsUnknown> {
                        let rows = match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.all())) {
                            Ok(rows) => rows,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        env.to_js_value(&rows).map_err(to_napi_err)
                    }

                    #[doc = #count_doc]
                    #[napi]
                    pub fn #count_m(&self) -> Result<i64> {
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.row_count())) {
                            Ok(n) => Ok(n as i64),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }

                    #[doc = #update_doc]
                    #[napi]
                    pub fn #update_m(
                        &mut self,
                        env: Env,
                        id: JsUnknown,
                        record: JsUnknown,
                    ) -> Result<bool> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let record: database::#model_ident =
                            env.from_js_value(record).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#update_fn(id, record))) {
                            Ok(r) => r.map_err(to_napi_err),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }

                    #[doc = #delete_doc]
                    #[napi]
                    pub fn #delete_m(&mut self, env: Env, id: JsUnknown) -> Result<bool> {
                        let id: #id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#delete_fn(id))) {
                            Ok(r) => r.map_err(to_napi_err),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }
                }
            })
            .collect()
    }

    /// The relation-traversal methods on `ForgeDb`, mirroring the generated
    /// `Database` traversal getters **one-for-one** — same names, derived from the
    /// same schema in the same order, sharing a `seen` dedup set that tracks
    /// `RustGenerator::generate_traversal_impl` exactly (so a method is never
    /// emitted for a getter that was deduped away). Three families, all id-keyed
    /// (a fixed generated edge walk, never a runtime predicate):
    ///   * **Forward FK** `<model>_<field>(id) -> Option<Target>` (flattened: null
    ///     if the source is absent OR the FK is unset);
    ///   * **Reverse 1:M** `<parent>_<field>[_by_<child_field>](id) -> [Child]`;
    ///   * **M2M** `link_<a>_<b>(l, r)` / `unlink_<a>_<b>(l, r) -> bool` + the query
    ///     getters `<a>_<field1>(id) -> [B]` / `<b>_<field2>(id) -> [A]`.
    ///
    /// Rows marshal through the generated struct's serde via `Env::to_js_value`
    /// (native JS objects — no row-class constraint, unlike the PyO3 wrapper). The
    /// one snapshot-scoped M2M `_at` traversal is deferred (no `Snapshot` handle on
    /// the ergonomic wrapper yet). Identity: no generic query surface — each getter
    /// is a fixed, generated edge walk by name; the napi serde bridge is
    /// schema-agnostic.
    fn generate_relation_methods(schema: &Schema) -> Vec<TokenStream> {
        use forgedb_parser::{FieldType, RelationType};
        use std::collections::{HashMap, HashSet};

        let mut methods = Vec::new();
        // ONE `seen` set spanning all three families, inserted in the SAME order as
        // `generate_traversal_impl`, so first-occurrence-wins agrees exactly.
        let mut seen: HashSet<String> = HashSet::new();

        // --- A. Forward FK getters (`*Target` / `?Target`) --------------------
        for model in &schema.models {
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_has_id = model.fields.iter().any(|f| f.name == "id" || f.auto_generate);
            let source_id_ty = RustGenerator::id_type_tokens(model);
            let storage = format_ident!("{}", model_snake);
            for field in &model.fields {
                let target_name = match &field.field_type {
                    FieldType::Relation(RelationType::RequiredReference(t))
                    | FieldType::Relation(RelationType::OptionalReference(t)) => t,
                    _ => continue,
                };
                let Some(target) = schema.find_model(target_name) else {
                    continue;
                };
                if !RustGenerator::is_uuid_pk(target) {
                    continue;
                }
                let method_name = format!("{model_snake}_{}", field.name);
                if !seen.insert(method_name.clone()) {
                    continue;
                }
                // Needs the source id-addressable (to `get` it before resolving the
                // FK); the target marshals via serde regardless of its PK kind. The
                // `seen` slot is consumed either way, matching the impl's ordering.
                if !model_has_id {
                    continue;
                }
                let method_ident = format_ident!("{}", method_name);
                let doc = format!(
                    "Resolve the `{}` foreign key of a `{}` (by id) to its record, or `null`.",
                    field.name, model.name
                );
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #method_ident(&self, env: Env, id: JsUnknown) -> Result<JsUnknown> {
                        let id: #source_id_ty = env.from_js_value(id).map_err(to_napi_err)?;
                        let resolved = match catch_unwind(AssertUnwindSafe(|| {
                            self.inner.#storage.get(id).and_then(|__rec| self.inner.#method_ident(&__rec))
                        })) {
                            Ok(opt) => opt,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        env.to_js_value(&resolved).map_err(to_napi_err)
                    }
                });
            }
        }

        // --- B. Reverse one-to-many collection getters ------------------------
        let pairs = schema.detect_relations();
        let mut group_counts: HashMap<(String, String), usize> = HashMap::new();
        for p in &pairs {
            *group_counts
                .entry((p.parent_model.clone(), p.parent_field.clone()))
                .or_default() += 1;
        }
        for p in &pairs {
            let Some(parent) = schema.find_model(&p.parent_model) else {
                continue;
            };
            if !RustGenerator::is_uuid_pk(parent) {
                continue;
            }
            let ambiguous = group_counts
                .get(&(p.parent_model.clone(), p.parent_field.clone()))
                .is_some_and(|&c| c > 1);
            let method_name = if ambiguous {
                format!(
                    "{}_{}_by_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field,
                    p.child_field
                )
            } else {
                format!("{}_{}", RustGenerator::to_snake_case(&p.parent_model), p.parent_field)
            };
            if !seen.insert(method_name.clone()) {
                continue;
            }
            let method_ident = format_ident!("{}", method_name);
            let doc = format!(
                "All `{}` whose `{}` references the given `{}` id.",
                p.child_model, p.child_field, p.parent_model
            );
            methods.push(quote! {
                #[doc = #doc]
                #[napi]
                pub fn #method_ident(&self, env: Env, id: JsUnknown) -> Result<JsUnknown> {
                    let id: Uuid = env.from_js_value(id).map_err(to_napi_err)?;
                    let rows = match catch_unwind(AssertUnwindSafe(|| self.inner.#method_ident(id))) {
                        Ok(rows) => rows,
                        Err(p) => return Err(panic_to_napi_err(p)),
                    };
                    env.to_js_value(&rows).map_err(to_napi_err)
                }
            });
        }

        // --- C. Many-to-many link / unlink + query getters --------------------
        for m in RustGenerator::valid_m2m(schema) {
            let snake1 = RustGenerator::to_snake_case(&m.model1);
            let snake2 = RustGenerator::to_snake_case(&m.model2);

            // link_<a>_<b>
            let link_name = format!("link_{snake1}_{snake2}");
            if seen.insert(link_name.clone()) {
                let link_ident = format_ident!("{}", link_name);
                let doc = format!("Link a `{}` (left) and a `{}` (right) in the junction.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #link_ident(&mut self, env: Env, left: JsUnknown, right: JsUnknown) -> Result<()> {
                        let left: Uuid = env.from_js_value(left).map_err(to_napi_err)?;
                        let right: Uuid = env.from_js_value(right).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#link_ident(left, right))) {
                            Ok(()) => Ok(()),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }
                });
            }

            // unlink_<a>_<b>
            let unlink_name = format!("unlink_{snake1}_{snake2}");
            if seen.insert(unlink_name.clone()) {
                let unlink_ident = format_ident!("{}", unlink_name);
                let doc = format!("Unlink a `{}` (left) / `{}` (right); `true` if a pair was removed.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #unlink_ident(&mut self, env: Env, left: JsUnknown, right: JsUnknown) -> Result<bool> {
                        let left: Uuid = env.from_js_value(left).map_err(to_napi_err)?;
                        let right: Uuid = env.from_js_value(right).map_err(to_napi_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#unlink_ident(left, right))) {
                            Ok(removed) => Ok(removed),
                            Err(p) => Err(panic_to_napi_err(p)),
                        }
                    }
                });
            }

            // model1.field1 -> Vec<model2>  (forward M2M query)
            let fwd_name = format!("{snake1}_{}", m.field1);
            if seen.insert(fwd_name.clone()) {
                let fwd_ident = format_ident!("{}", fwd_name);
                let doc = format!("All linked `{}` for the given `{}` id.", m.model2, m.model1);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #fwd_ident(&self, env: Env, id: JsUnknown) -> Result<JsUnknown> {
                        let id: Uuid = env.from_js_value(id).map_err(to_napi_err)?;
                        let rows = match catch_unwind(AssertUnwindSafe(|| self.inner.#fwd_ident(id))) {
                            Ok(rows) => rows,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        env.to_js_value(&rows).map_err(to_napi_err)
                    }
                });
            }

            // model2.field2 -> Vec<model1>  (reverse M2M query)
            let rev_name = format!("{snake2}_{}", m.field2);
            if seen.insert(rev_name.clone()) {
                let rev_ident = format_ident!("{}", rev_name);
                let doc = format!("All linked `{}` for the given `{}` id.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    #[napi]
                    pub fn #rev_ident(&self, env: Env, id: JsUnknown) -> Result<JsUnknown> {
                        let id: Uuid = env.from_js_value(id).map_err(to_napi_err)?;
                        let rows = match catch_unwind(AssertUnwindSafe(|| self.inner.#rev_ident(id))) {
                            Ok(rows) => rows,
                            Err(p) => return Err(panic_to_napi_err(p)),
                        };
                        env.to_js_value(&rows).map_err(to_napi_err)
                    }
                });
            }
        }

        methods
    }

    /// The NAPI-RS crate's `Cargo.toml`. User-editable config — written only when
    /// absent, mirroring the FFI / PyO3 / wasm scaffolds. A `cdylib` (the `.node`
    /// addon `require()`d by both Node and Bun); `napi`'s `serde-json` feature
    /// drives the `Env::to_js_value`/`from_js_value` marshalling; `panic = "unwind"`
    /// is load-bearing (the methods `catch_unwind` engine panics).
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib: the Node-API addon (`.node`) both Node and Bun load (Option A).
name = "forgedb"
crate-type = ["cdylib"]

[dependencies]
forgedb-storage = "0.2"
forgedb-types = "0.2"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
forgedb-txn = "0.1"
forgedb-coordinator = "0.1"
forgedb-query-params = "0.1"
forgedb-auth = "0.1"
regex = "1"
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}
napi = {{ version = "2", default-features = false, features = ["napi8", "serde-json"] }}
napi-derive = "2"

[build-dependencies]
napi-build = "2"

[profile.release]
# Load-bearing: the Node-API entry points catch_unwind engine panics, so the
# release profile must unwind (not abort) for that boundary to hold.
panic = "unwind"
"#
        )
    }

    /// The NAPI-RS `build.rs` (schema-invariant). `napi_build::setup()` wires the
    /// platform linker args (incl. macOS `-undefined dynamic_lookup` so the
    /// `.node` resolves Node-API symbols at load time), so a plain `cargo build`
    /// links standalone — the compile-test path.
    pub fn build_rs_scaffold() -> &'static str {
        "// Generated by ForgeDB — NAPI-RS build script (schema-invariant).\n\
         fn main() {\n    \
         napi_build::setup();\n\
         }\n"
    }

    /// The `package.json` for the generated binding — makes `@napi-rs/cli` the
    /// blessed build path (`napi build` → the `.node` + a generated `index.js`
    /// loader + `index.d.ts`). User-editable — written only when absent.
    pub fn package_json_scaffold() -> &'static str {
        r#"{
  "name": "forgedb",
  "version": "0.1.0",
  "description": "Generated ForgeDB Node/Bun binding (NAPI-RS)",
  "main": "index.js",
  "types": "index.d.ts",
  "napi": {
    "name": "forgedb"
  },
  "scripts": {
    "build": "napi build --platform --release",
    "build:debug": "napi build --platform"
  },
  "devDependencies": {
    "@napi-rs/cli": "^2.18.0"
  }
}
"#
    }
}
