//! PyO3 language-binding generator (#51) — the ergonomic Python wrapper over the
//! SAME generated `database.rs`, a sibling of the native FFI spine (`ffi.rs`) and
//! the wasm replica (`wasm.rs`).
//!
//! It emits a per-schema `#[pyclass]` surface: one row class per identity model
//! (native marshalling through the generated struct's own serde contract via
//! `pythonize` — the same single source of truth the WAL / broker / FFI use, so
//! there is no second per-field matrix to drift) plus a `ForgeDb` class whose
//! methods mirror the generated `Database` CRUD **1:1**, calling the integrity
//! wrappers (`create_<m>`/`update_<m>`/`delete_<m>`) and storage reads by name.
//!
//! **Typed field getters (Phase 5b follow-up).** Each `#[pyclass]` already has a
//! `#[getter]` per stored field.  This release makes those getters return native
//! Python-typed values rather than `Bound<'py, PyAny>` wherever a clean Rust↔Python
//! type mapping exists:
//!
//! | `.forge` type            | Getter return type  | Notes                               |
//! |--------------------------|---------------------|-------------------------------------|
//! | `u32`                    | `u32`               | Python `int`                        |
//! | `u64`                    | `u64`               | Python `int`                        |
//! | `i32`                    | `i32`               | Python `int`                        |
//! | `i64`                    | `i64`               | Python `int`                        |
//! | `f64`                    | `f64`               | Python `float`                      |
//! | `bool`                   | `bool`              | Python `bool`                       |
//! | `string`                 | `String`            | Python `str`                        |
//! | `uuid`                   | `String`            | Hyphenated UUID string              |
//! | `timestamp`              | `i64`               | Seconds since epoch (`i64::from`)   |
//! | `decimal`                | `String`            | Decimal string (serde-with-str)     |
//! | `enum(X)`                | `String`            | Variant-name string (serde default) |
//! | `*Target` (req. FK)      | `String`            | UUID string                         |
//! | `?Target` (opt. FK)      | `Option<String>`    | UUID string or None                 |
//! | Nullable(T)              | `Option<inner>`     | None when absent                    |
//! | `json`, `char(N)`, struct | `Bound<'py, PyAny>` | pythonize (no single-type mapping) |
//!
//! The `to_dict` / `__repr__` / `__init__` paths are unchanged (still use
//! `pythonize`/`depythonize`), so existing callers that relied on the dict API
//! remain unaffected.
//!
//! Identity: every schema-specific surface is generated per-model (constraint 2);
//! there is **no** generic `query`/`filter`/`predicate` entry point and no
//! `match model` dispatch (constraint 1). The row types and methods are named
//! from the schema, which IS the tailoring.

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::rust::RustGenerator;

pub struct PyO3Generator;

impl PyO3Generator {
    /// Generate the PyO3 wrapper (`pyo3/src/lib.rs`) for a schema.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let row_classes = Self::generate_row_classes(schema);
        let db_methods = Self::generate_db_methods(schema);
        let relation_methods = Self::generate_relation_methods(schema);
        let arrow_methods = Self::generate_arrow_methods(schema);
        let arrow_spine = Self::generate_arrow_spine(schema);
        let registrations = Self::generate_registrations(schema);
        let arrow_registration = Self::generate_arrow_registration(schema);

        let tokens = quote! {
            //! Generated by ForgeDB — Python binding (PyO3, #51).
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue: the ergonomic Python surface over the
            //! generated `Database`. One `#[pyclass]` per identity model + a
            //! `ForgeDb` whose methods mirror the generated CRUD 1:1. The tailored
            //! data logic lives in the generated `database.rs`; this file binds it.
            //! It invents no query API (the identity red line).
            #![allow(warnings)]

            mod database;

            use pyo3::prelude::*;
            use pyo3::exceptions::PyException;
            use pyo3::types::PyCapsule;
            use std::ffi::{CString, c_char, c_void};
            use std::panic::{AssertUnwindSafe, catch_unwind};
            use std::ptr;

            use database::Database;
            // Names the primary-key type of UUID-keyed models (`id_type_tokens`
            // emits a bare `Uuid`); integer-PK models use std types.
            use forgedb_types::Uuid;

            pyo3::create_exception!(
                forgedb,
                ForgeDbError,
                PyException,
                "Raised on any ForgeDB engine or validation error."
            );

            /// Map any engine error (`ValidationError`, `io::Error`, …) to the
            /// Python-visible `ForgeDbError`.
            fn to_py_err<E: std::fmt::Display>(e: E) -> PyErr {
                ForgeDbError::new_err(e.to_string())
            }

            /// Convert a caught panic payload into a `ForgeDbError` so an engine
            /// panic (e.g. the single-writer `DirLock`) never unwinds into the
            /// interpreter as a raw abort.
            fn panic_to_py_err(payload: Box<dyn std::any::Any + Send>) -> PyErr {
                let msg = payload
                    .downcast_ref::<&str>()
                    .map(|s| s.to_string())
                    .or_else(|| payload.downcast_ref::<String>().cloned())
                    .unwrap_or_else(|| "engine panic".to_string());
                ForgeDbError::new_err(msg)
            }

            #(#row_classes)*

            #arrow_spine

            /// A ForgeDB database handle — one single-writer process over a data
            /// directory. Methods mirror the generated `Database` surface 1:1.
            #[pyclass]
            pub struct ForgeDb {
                inner: Database,
            }

            #[pymethods]
            impl ForgeDb {
                /// Open (or create) the database at `root`. Holds the single-writer
                /// lock; a second writer raises `ForgeDbError` rather than aborting.
                #[staticmethod]
                fn open(root: String) -> PyResult<Self> {
                    let root = std::path::PathBuf::from(root);
                    match catch_unwind(AssertUnwindSafe(|| Database::open_at(root))) {
                        Ok(inner) => Ok(Self { inner }),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                /// Flush every column to disk (fsync on native).
                fn commit(&mut self) -> PyResult<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.commit())) {
                        Ok(r) => r.map_err(to_py_err),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                /// Force a WAL checkpoint (fsync columns, then truncate the WAL).
                fn checkpoint(&mut self) -> PyResult<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.checkpoint())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                /// Reclaim dead (superseded/tombstoned) row versions in-process.
                /// Explicit only — never reached from a read path (constraint 4).
                fn compact(&mut self) -> PyResult<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.compact())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                #(#db_methods)*

                #(#relation_methods)*

                #(#arrow_methods)*
            }

            /// The generated Python module — registers the row classes, `ForgeDb`,
            /// and `ForgeDbError`.
            #[pymodule]
            fn forgedb(m: &Bound<'_, PyModule>) -> PyResult<()> {
                m.add_class::<ForgeDb>()?;
                #(#registrations)*
                #arrow_registration
                m.add("ForgeDbError", m.py().get_type::<ForgeDbError>())?;
                Ok(())
            }
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!(
                "Failed to parse generated PyO3 binding: {e}"
            ))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!("Python binding (PyO3) ({} models)", schema.models.len()),
        })
    }

    /// The identity models a binding surface is generated for — those with an
    /// `id` field or an auto-generated PK (same filter as the FFI spine).
    fn identity_models(schema: &Schema) -> impl Iterator<Item = &forgedb_parser::Model> {
        schema
            .models
            .iter()
            .filter(|m| m.fields.iter().any(|f| f.name == "id" || f.auto_generate))
    }

    /// The PyO3 getter return type and body for a given `.forge` field type.
    ///
    /// Returns `(return_type_tokens, body_tokens)` where `body_tokens` is the
    /// expression returned from `fn #fname(&self, py: Python<'py>) -> PyResult<...>`.
    /// For types with a clean Rust↔Python mapping (primitives, string, uuid,
    /// timestamp, decimal, enum, FK scalars, nullable variants) we return a concrete
    /// type so PyO3 emits typed Python stubs.  For types without a natural single
    /// Python type (`json`, `char(N)`, inline `struct`) we fall back to pythonize
    /// and return `Bound<'py, PyAny>`.
    fn pyo3_getter(
        field_type: &forgedb_parser::FieldType,
        field_name: &proc_macro2::Ident,
    ) -> (TokenStream, TokenStream) {
        use forgedb_parser::{FieldType, RelationType};
        match field_type {
            // Primitives — returned as native Rust types; PyO3 converts to Python int/float/bool.
            FieldType::U32 => (
                quote! { u32 },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::U64 => (
                quote! { u64 },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::I32 => (
                quote! { i32 },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::I64 => (
                quote! { i64 },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::F64 => (
                quote! { f64 },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::Bool => (
                quote! { bool },
                quote! { Ok(self.inner.#field_name) },
            ),

            // String — clone; Python `str`. `string(N)` too (#238): it is a
            // `String` in the generated record.
            FieldType::String | FieldType::StringN { .. } => (
                quote! { String },
                quote! { Ok(self.inner.#field_name.clone()) },
            ),

            // uuid → hyphenated string (matches serde and the REST wire shape).
            FieldType::Uuid => (
                quote! { String },
                quote! { Ok(self.inner.#field_name.to_string()) },
            ),

            // timestamp (forgedb_types::Timestamp, newtype over i64) → i64.
            FieldType::Timestamp => (
                quote! { i64 },
                quote! { Ok(i64::from(self.inner.#field_name)) },
            ),

            // decimal → string (serde-with-str produces a decimal string).
            FieldType::Decimal => (
                quote! { String },
                quote! { Ok(self.inner.#field_name.to_string()) },
            ),

            // enum → variant-name string (serde default serialization).
            FieldType::Enum(_) => (
                quote! { String },
                quote! {
                    serde_json::to_value(&self.inner.#field_name)
                        .map_err(to_py_err)
                        .map(|__v| __v.as_str().unwrap_or_default().to_string())
                },
            ),

            // Required FK (Uuid) → hyphenated string.
            FieldType::Relation(RelationType::RequiredReference(_)) => (
                quote! { String },
                quote! { Ok(self.inner.#field_name.to_string()) },
            ),

            // Optional FK (Option<Uuid>) → Option<String>.
            FieldType::Relation(RelationType::OptionalReference(_)) => (
                quote! { Option<String> },
                quote! { Ok(self.inner.#field_name.map(|__u| __u.to_string())) },
            ),

            // Nullable(inner) — recurse; the outer getter wraps in Option.
            FieldType::Nullable(inner) => {
                let (inner_ret, inner_body) = Self::pyo3_nullable_getter(inner, field_name);
                (inner_ret, inner_body)
            }

            // Complex types: json, char(N), inline struct — fall back to pythonize.
            // These have no single clean Python type; the Bound<'py, PyAny> from
            // pythonize is the correct ergonomic choice.
            _ => (
                quote! { Bound<'py, PyAny> },
                quote! { pythonize::pythonize(py, &self.inner.#field_name).map_err(to_py_err) },
            ),
        }
    }

    /// Typed getter for a nullable field; `self.inner.#field_name` is `Option<T>`.
    fn pyo3_nullable_getter(
        inner: &forgedb_parser::FieldType,
        field_name: &proc_macro2::Ident,
    ) -> (TokenStream, TokenStream) {
        use forgedb_parser::FieldType;
        match inner {
            FieldType::U32 => (
                quote! { Option<u32> },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::U64 => (
                quote! { Option<u64> },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::I32 => (
                quote! { Option<i32> },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::I64 => (
                quote! { Option<i64> },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::F64 => (
                quote! { Option<f64> },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::Bool => (
                quote! { Option<bool> },
                quote! { Ok(self.inner.#field_name) },
            ),
            FieldType::String | FieldType::StringN { .. } => (
                quote! { Option<String> },
                quote! { Ok(self.inner.#field_name.clone()) },
            ),
            FieldType::Uuid => (
                quote! { Option<String> },
                quote! { Ok(self.inner.#field_name.map(|__u| __u.to_string())) },
            ),
            FieldType::Timestamp => (
                quote! { Option<i64> },
                quote! { Ok(self.inner.#field_name.map(i64::from)) },
            ),
            FieldType::Decimal => (
                quote! { Option<String> },
                quote! { Ok(self.inner.#field_name.map(|__d| __d.to_string())) },
            ),
            FieldType::Enum(_) => (
                quote! { Option<String> },
                quote! {
                    self.inner.#field_name.as_ref()
                        .map(|__e| serde_json::to_value(__e)
                            .map(|__v| __v.as_str().unwrap_or_default().to_string())
                            .map_err(to_py_err))
                        .transpose()
                },
            ),
            // Fallback for nullable complex types.
            _ => (
                quote! { Bound<'py, PyAny> },
                quote! { pythonize::pythonize(py, &self.inner.#field_name).map_err(to_py_err) },
            ),
        }
    }

    /// One `#[pyclass]` per identity model: a newtype over the generated struct
    /// with a dict/mapping `__init__`, `to_dict`, `__repr__`, and per-field
    /// typed getters. Virtual relation collections (`OneToMany`/`ManyToMany`)
    /// carry no data and are excluded.
    ///
    /// Getter return types are concrete Python-typed values wherever a clean
    /// mapping exists (see `pyo3_getter`); complex types fall back to pythonize
    /// and return `Bound<'py, PyAny>`.
    fn generate_row_classes(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let model_ident = format_ident!("{}", model.name);
                let py_ident = format_ident!("Py{}", model.name);
                let name_str = model.name.as_str();

                // Per-field typed getters. Virtual relation collections are skipped.
                let getters: Vec<TokenStream> = model
                    .fields
                    .iter()
                    .filter(|f| !Self::is_virtual_relation(&f.field_type))
                    .map(|f| {
                        let fname = format_ident!("{}", f.name);
                        let doc = format!("The `{}` field.", f.name);
                        let (ret_ty, body) = Self::pyo3_getter(&f.field_type, &fname);
                        // Whether the return type references the `'py` lifetime
                        // (only for the pythonize fallback path).
                        let needs_py_lifetime = matches!(
                            f.field_type,
                            forgedb_parser::FieldType::Json
                            | forgedb_parser::FieldType::Bytes(_)
                            | forgedb_parser::FieldType::StructType(_)
                            | forgedb_parser::FieldType::OptionalStructType(_)
                            | forgedb_parser::FieldType::FixedArray(_, _)
                        ) || (matches!(&f.field_type, forgedb_parser::FieldType::Nullable(inner)
                            if matches!(inner.as_ref(),
                                forgedb_parser::FieldType::Json
                                | forgedb_parser::FieldType::Bytes(_)
                                | forgedb_parser::FieldType::StructType(_)
                                | forgedb_parser::FieldType::OptionalStructType(_)
                            )
                        ));
                        if needs_py_lifetime {
                            quote! {
                                #[doc = #doc]
                                #[getter]
                                fn #fname<'py>(&self, py: Python<'py>) -> PyResult<#ret_ty> {
                                    #body
                                }
                            }
                        } else {
                            quote! {
                                #[doc = #doc]
                                #[getter]
                                fn #fname(&self) -> PyResult<#ret_ty> {
                                    #body
                                }
                            }
                        }
                    })
                    .collect();

                let new_doc = format!(
                    "Construct a `{}` from a Python mapping (dict) matching the schema fields.",
                    model.name
                );
                let dict_doc = format!("Return this `{}` as a native Python dict.", model.name);

                quote! {
                    #[doc = #new_doc]
                    #[pyclass(name = #name_str)]
                    #[derive(Clone)]
                    pub struct #py_ident {
                        inner: database::#model_ident,
                    }

                    #[pymethods]
                    impl #py_ident {
                        #[new]
                        fn new(data: &Bound<'_, PyAny>) -> PyResult<Self> {
                            let inner: database::#model_ident =
                                pythonize::depythonize(data).map_err(to_py_err)?;
                            Ok(Self { inner })
                        }

                        #[doc = #dict_doc]
                        fn to_dict<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
                            pythonize::pythonize(py, &self.inner).map_err(to_py_err)
                        }

                        fn __repr__(&self) -> String {
                            format!("{:?}", self.inner)
                        }

                        #(#getters)*
                    }

                    impl #py_ident {
                        fn from_record(inner: database::#model_ident) -> Self {
                            Self { inner }
                        }
                    }
                }
            })
            .collect()
    }

    /// The per-model CRUD methods on `ForgeDb`, mirroring the generated `Database`
    /// integrity wrappers + storage reads 1:1.
    fn generate_db_methods(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let snake = RustGenerator::to_snake_case(&model.name);
                let model_ident = format_ident!("{}", model.name);
                let py_ident = format_ident!("Py{}", model.name);
                let storage = format_ident!("{}", snake);
                let id_ty = RustGenerator::id_type_tokens(model);

                let create_fn = format_ident!("create_{}", snake);
                let update_fn = format_ident!("update_{}", snake);
                let delete_fn = format_ident!("delete_{}", snake);

                let create_m = format_ident!("create_{}", snake);
                let get_m = format_ident!("get_{}", snake);
                let all_m = format_ident!("all_{}", snake);
                let count_m = format_ident!("count_{}", snake);
                let update_m = format_ident!("update_{}", snake);
                let delete_m = format_ident!("delete_{}", snake);

                let create_doc = format!(
                    "Insert a `{}` (FK-checked + validated); returns the new id.",
                    model.name
                );
                let get_doc =
                    format!("Fetch a `{}` by id, or `None` if absent.", model.name);
                let all_doc = format!("Every live `{}`.", model.name);
                let count_doc = format!("Live `{}` row count.", model.name);
                let update_doc = format!(
                    "Update a `{}` by id; `True` if present, `False` if absent.",
                    model.name
                );
                let delete_doc = format!(
                    "Delete a `{}` by id (referential integrity enforced); `True`/`False`.",
                    model.name
                );

                quote! {
                    #[doc = #create_doc]
                    fn #create_m<'py>(
                        &mut self,
                        record: &Bound<'py, PyAny>,
                    ) -> PyResult<Bound<'py, PyAny>> {
                        let py = record.py();
                        let record: database::#model_ident =
                            pythonize::depythonize(record).map_err(to_py_err)?;
                        let id = match catch_unwind(AssertUnwindSafe(|| self.inner.#create_fn(record))) {
                            Ok(r) => r.map_err(to_py_err)?,
                            Err(p) => return Err(panic_to_py_err(p)),
                        };
                        pythonize::pythonize(py, &id).map_err(to_py_err)
                    }

                    #[doc = #get_doc]
                    fn #get_m(&self, id: &Bound<'_, PyAny>) -> PyResult<Option<#py_ident>> {
                        let id: #id_ty = pythonize::depythonize(id).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.get(id))) {
                            Ok(opt) => Ok(opt.map(#py_ident::from_record)),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #all_doc]
                    fn #all_m(&self) -> PyResult<Vec<#py_ident>> {
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.all())) {
                            Ok(rows) => Ok(rows.into_iter().map(#py_ident::from_record).collect()),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #count_doc]
                    fn #count_m(&self) -> PyResult<usize> {
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.row_count())) {
                            Ok(n) => Ok(n),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #update_doc]
                    fn #update_m(
                        &mut self,
                        id: &Bound<'_, PyAny>,
                        record: &Bound<'_, PyAny>,
                    ) -> PyResult<bool> {
                        let id: #id_ty = pythonize::depythonize(id).map_err(to_py_err)?;
                        let record: database::#model_ident =
                            pythonize::depythonize(record).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#update_fn(id, record))) {
                            Ok(r) => r.map_err(to_py_err),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #delete_doc]
                    fn #delete_m(&mut self, id: &Bound<'_, PyAny>) -> PyResult<bool> {
                        let id: #id_ty = pythonize::depythonize(id).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#delete_fn(id))) {
                            Ok(r) => r.map_err(to_py_err),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }
                }
            })
            .collect()
    }

    /// Whether a model has a materialized identity (an `id` field or an
    /// auto-generated PK) — hence a generated row class (`Py<Model>`) and an
    /// id-addressable storage read. A traversal that would return / start from a
    /// model without one is skipped (there is no row class to marshal into).
    fn is_identity_model(model: &forgedb_parser::Model) -> bool {
        model.fields.iter().any(|f| f.name == "id" || f.auto_generate)
    }

    /// The relation-traversal methods on `ForgeDb`, mirroring the generated
    /// `Database` traversal getters **one-for-one** — same names, derived from the
    /// same schema in the same order, sharing a `seen` dedup set that tracks
    /// `RustGenerator::generate_traversal_impl` exactly (so a method is never
    /// emitted for a getter that was deduped away). Three families, all id-keyed
    /// (a fixed generated edge walk, never a runtime predicate):
    ///   * **Forward FK** `<model>_<field>(id) -> Option<Py<Target>>` — fetch the
    ///     source by id, resolve the `*Target`/`?Target` FK (flattened: `None` if
    ///     the source is absent OR the FK is unset);
    ///   * **Reverse 1:M** `<parent>_<field>[_by_<child_field>](id) -> [Py<Child>]`
    ///     — every child whose FK references the (UUID) parent id;
    ///   * **M2M** `link_<a>_<b>(l, r)` / `unlink_<a>_<b>(l, r) -> bool` + the
    ///     query getters `<a>_<field1>(id) -> [Py<B>]` / `<b>_<field2>(id) ->
    ///     [Py<A>]`.
    ///
    /// Rows marshal through the generated Py row classes (`Py<Model>::from_record`);
    /// a traversal to/from a **non-identity** model (no row class) is skipped — an
    /// honest limit, not a drift (the `seen` slot is still consumed so ordering is
    /// unchanged). The one snapshot-scoped M2M `_at` traversal is deferred (there
    /// is no `Snapshot` class on the ergonomic wrapper yet). Identity: no generic
    /// query surface — each getter is a fixed, generated edge walk by name.
    fn generate_relation_methods(schema: &Schema) -> Vec<TokenStream> {
        use forgedb_parser::{FieldType, RelationType};
        use std::collections::{HashMap, HashSet};

        let mut methods = Vec::new();
        // ONE `seen` set spanning all three families, inserted in the SAME order as
        // `generate_traversal_impl`, so first-occurrence-wins agrees exactly.
        let mut seen: HashSet<String> = HashSet::new();

        // --- A. Forward FK getters (`*Target` / `?Target`) --------------------
        for model in &schema.models {
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_has_id = Self::is_identity_model(model);
            let source_id_ty = RustGenerator::id_type_tokens(model);
            let storage = format_ident!("{}", model_snake);
            for field in &model.fields {
                let target_name = match &field.field_type {
                    FieldType::Relation(RelationType::RequiredReference(t))
                    | FieldType::Relation(RelationType::OptionalReference(t)) => t,
                    _ => continue,
                };
                let Some(target) = schema.find_model(target_name) else {
                    continue;
                };
                if !RustGenerator::is_uuid_pk(target) {
                    continue;
                }
                let method_name = format!("{model_snake}_{}", field.name);
                if !seen.insert(method_name.clone()) {
                    continue;
                }
                // Needs the source id-addressable (to `get` it) and the target to
                // have a row class (identity). Either missing → skip emission; the
                // `seen` slot is already consumed, matching the impl's ordering.
                if !model_has_id || !Self::is_identity_model(target) {
                    continue;
                }
                let method_ident = format_ident!("{}", method_name);
                let py_target = format_ident!("Py{}", target.name);
                let doc = format!(
                    "Resolve the `{}` foreign key of a `{}` (by id) to its record, or `None`.",
                    field.name, model.name
                );
                methods.push(quote! {
                    #[doc = #doc]
                    fn #method_ident(&self, id: &Bound<'_, PyAny>) -> PyResult<Option<#py_target>> {
                        let id: #source_id_ty = pythonize::depythonize(id).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| {
                            self.inner.#storage.get(id).and_then(|__rec| self.inner.#method_ident(&__rec))
                        })) {
                            Ok(opt) => Ok(opt.map(#py_target::from_record)),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }
                });
            }
        }

        // --- B. Reverse one-to-many collection getters ------------------------
        let pairs = schema.detect_relations();
        let mut group_counts: HashMap<(String, String), usize> = HashMap::new();
        for p in &pairs {
            *group_counts
                .entry((p.parent_model.clone(), p.parent_field.clone()))
                .or_default() += 1;
        }
        for p in &pairs {
            let Some(parent) = schema.find_model(&p.parent_model) else {
                continue;
            };
            if !RustGenerator::is_uuid_pk(parent) {
                continue;
            }
            let ambiguous = group_counts
                .get(&(p.parent_model.clone(), p.parent_field.clone()))
                .is_some_and(|&c| c > 1);
            let method_name = if ambiguous {
                format!(
                    "{}_{}_by_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field,
                    p.child_field
                )
            } else {
                format!("{}_{}", RustGenerator::to_snake_case(&p.parent_model), p.parent_field)
            };
            if !seen.insert(method_name.clone()) {
                continue;
            }
            // The child needs a row class to marshal into (identity).
            let Some(child) = schema.find_model(&p.child_model) else {
                continue;
            };
            if !Self::is_identity_model(child) {
                continue;
            }
            let method_ident = format_ident!("{}", method_name);
            let py_child = format_ident!("Py{}", child.name);
            let doc = format!(
                "All `{}` whose `{}` references the given `{}` id.",
                p.child_model, p.child_field, p.parent_model
            );
            methods.push(quote! {
                #[doc = #doc]
                fn #method_ident(&self, id: &Bound<'_, PyAny>) -> PyResult<Vec<#py_child>> {
                    let id: Uuid = pythonize::depythonize(id).map_err(to_py_err)?;
                    match catch_unwind(AssertUnwindSafe(|| self.inner.#method_ident(id))) {
                        Ok(rows) => Ok(rows.into_iter().map(#py_child::from_record).collect()),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }
            });
        }

        // --- C. Many-to-many link / unlink + query getters --------------------
        for m in RustGenerator::valid_m2m(schema) {
            let snake1 = RustGenerator::to_snake_case(&m.model1);
            let snake2 = RustGenerator::to_snake_case(&m.model2);
            let model1 = schema.find_model(&m.model1);
            let model2 = schema.find_model(&m.model2);

            // link_<a>_<b> — no row class needed (UUID ids in, unit out).
            let link_name = format!("link_{snake1}_{snake2}");
            if seen.insert(link_name.clone()) {
                let link_ident = format_ident!("{}", link_name);
                let doc = format!("Link a `{}` (left) and a `{}` (right) in the junction.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    fn #link_ident(&mut self, left: &Bound<'_, PyAny>, right: &Bound<'_, PyAny>) -> PyResult<()> {
                        let left: Uuid = pythonize::depythonize(left).map_err(to_py_err)?;
                        let right: Uuid = pythonize::depythonize(right).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#link_ident(left, right))) {
                            Ok(()) => Ok(()),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }
                });
            }

            // unlink_<a>_<b> — no row class needed (UUID ids in, bool out).
            let unlink_name = format!("unlink_{snake1}_{snake2}");
            if seen.insert(unlink_name.clone()) {
                let unlink_ident = format_ident!("{}", unlink_name);
                let doc = format!("Unlink a `{}` (left) / `{}` (right); `True` if a pair was removed.", m.model1, m.model2);
                methods.push(quote! {
                    #[doc = #doc]
                    fn #unlink_ident(&mut self, left: &Bound<'_, PyAny>, right: &Bound<'_, PyAny>) -> PyResult<bool> {
                        let left: Uuid = pythonize::depythonize(left).map_err(to_py_err)?;
                        let right: Uuid = pythonize::depythonize(right).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#unlink_ident(left, right))) {
                            Ok(removed) => Ok(removed),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }
                });
            }

            // model1.field1 -> Vec<model2>  (forward M2M query)
            let fwd_name = format!("{snake1}_{}", m.field1);
            if seen.insert(fwd_name.clone()) {
                if let Some(model2) = model2 {
                    if Self::is_identity_model(model2) {
                        let fwd_ident = format_ident!("{}", fwd_name);
                        let py_b = format_ident!("Py{}", model2.name);
                        let doc = format!("All linked `{}` for the given `{}` id.", m.model2, m.model1);
                        methods.push(quote! {
                            #[doc = #doc]
                            fn #fwd_ident(&self, id: &Bound<'_, PyAny>) -> PyResult<Vec<#py_b>> {
                                let id: Uuid = pythonize::depythonize(id).map_err(to_py_err)?;
                                match catch_unwind(AssertUnwindSafe(|| self.inner.#fwd_ident(id))) {
                                    Ok(rows) => Ok(rows.into_iter().map(#py_b::from_record).collect()),
                                    Err(p) => Err(panic_to_py_err(p)),
                                }
                            }
                        });
                    }
                }
            }

            // model2.field2 -> Vec<model1>  (reverse M2M query)
            let rev_name = format!("{snake2}_{}", m.field2);
            if seen.insert(rev_name.clone()) {
                if let Some(model1) = model1 {
                    if Self::is_identity_model(model1) {
                        let rev_ident = format_ident!("{}", rev_name);
                        let py_a = format_ident!("Py{}", model1.name);
                        let doc = format!("All linked `{}` for the given `{}` id.", m.model1, m.model2);
                        methods.push(quote! {
                            #[doc = #doc]
                            fn #rev_ident(&self, id: &Bound<'_, PyAny>) -> PyResult<Vec<#py_a>> {
                                let id: Uuid = pythonize::depythonize(id).map_err(to_py_err)?;
                                match catch_unwind(AssertUnwindSafe(|| self.inner.#rev_ident(id))) {
                                    Ok(rows) => Ok(rows.into_iter().map(#py_a::from_record).collect()),
                                    Err(p) => Err(panic_to_py_err(p)),
                                }
                            }
                        });
                    }
                }
            }
        }

        methods
    }

    /// The Arrow columnar-export spine — the zero-copy selling point (#51). A
    /// schema-invariant `ArrowColumn` `#[pyclass]` that implements the Arrow
    /// **PyCapsule interface** (`__arrow_c_array__`), so `pyarrow.array(col)`
    /// imports a whole live column **zero-copy** (an `mmap` alias of the on-disk
    /// column when the live rows are a dense prefix, a gathered copy otherwise —
    /// transparent, via `forgedb_storage::ColumnExport`). Emitted only when the
    /// schema has at least one Arrow-exportable column (else an empty stream, so no
    /// unused `#[pyclass]` is generated).
    ///
    /// Identity clean: `ArrowColumn` holds an opaque `ColumnExport` + a fixed Arrow
    /// format string chosen by the schema at codegen time; it reads no field/type
    /// at runtime and exposes no query surface. The C Data Interface structs mirror
    /// the FFI Arrow spine verbatim; the capsule destructor honors the Arrow
    /// release protocol (release-if-not-consumed, no-op after a consumer moved it).
    fn generate_arrow_spine(schema: &Schema) -> TokenStream {
        if !Self::has_arrow_columns(schema) {
            return quote! {};
        }
        quote! {
            /// Arrow C Data Interface schema struct (`struct ArrowSchema`).
            #[repr(C)]
            pub struct ArrowSchema {
                format: *const c_char,
                name: *const c_char,
                metadata: *const c_char,
                flags: i64,
                n_children: i64,
                children: *mut *mut ArrowSchema,
                dictionary: *mut ArrowSchema,
                release: Option<unsafe extern "C" fn(*mut ArrowSchema)>,
                private_data: *mut c_void,
            }
            // The capsule may be finalized on any thread; the raw pointers are
            // managed by the Arrow release protocol, not shared mutably.
            unsafe impl Send for ArrowSchema {}

            /// Arrow C Data Interface array struct (`struct ArrowArray`).
            #[repr(C)]
            pub struct ArrowArray {
                length: i64,
                null_count: i64,
                offset: i64,
                n_buffers: i64,
                n_children: i64,
                buffers: *mut *const c_void,
                children: *mut *mut ArrowArray,
                dictionary: *mut ArrowArray,
                release: Option<unsafe extern "C" fn(*mut ArrowArray)>,
                private_data: *mut c_void,
            }
            unsafe impl Send for ArrowArray {}

            /// Owns everything an exported `ArrowArray` points at: the column export
            /// (`mmap` alias or gathered `Vec`, transparent) backing `buffers[1]`,
            /// and the two-element buffer pointer array. Dropped by the Arrow
            /// `release` — freeing the copy or `munmap`ing the alias.
            struct ArrowArrayOwner {
                _export: forgedb_storage::ColumnExport,
                _buffers: Vec<*const c_void>,
            }

            /// Arrow `release` for an exported array: reclaim + drop the owner box,
            /// then null `release` (the Arrow released marker).
            unsafe extern "C" fn arrow_array_release(array: *mut ArrowArray) {
                if array.is_null() { return; }
                let a = &mut *array;
                if a.release.is_none() { return; }
                if !a.private_data.is_null() {
                    drop(Box::from_raw(a.private_data as *mut ArrowArrayOwner));
                }
                a.private_data = ptr::null_mut();
                a.release = None;
            }

            /// Arrow `release` for the schema: `format` is a `'static` C-string and
            /// `name`/`metadata` are null, so there is nothing to free — just null
            /// `release`.
            unsafe extern "C" fn arrow_schema_release(schema: *mut ArrowSchema) {
                if schema.is_null() { return; }
                let s = &mut *schema;
                s.release = None;
            }

            /// Build the Arrow C Data Interface pair for a non-null fixed-width
            /// primitive column: two buffers (null validity + the exported data),
            /// `length` values, no children.  `format` is a `'static` Arrow format
            /// C-string; `export`'s buffer backs `buffers[1]` and outlives the pair
            /// inside the owner box.
            fn arrow_build_primitive(
                format: *const c_char,
                export: forgedb_storage::ColumnExport,
                length: usize,
            ) -> (ArrowSchema, ArrowArray) {
                let data_ptr = export.as_ptr() as *const c_void;
                let buffers: Vec<*const c_void> = vec![ptr::null(), data_ptr];
                let buffers_ptr = buffers.as_ptr() as *mut *const c_void;
                let owner = Box::new(ArrowArrayOwner { _export: export, _buffers: buffers });
                let array = ArrowArray {
                    length: length as i64,
                    null_count: 0,
                    offset: 0,
                    n_buffers: 2,
                    n_children: 0,
                    buffers: buffers_ptr,
                    children: ptr::null_mut(),
                    dictionary: ptr::null_mut(),
                    release: Some(arrow_array_release),
                    private_data: Box::into_raw(owner) as *mut c_void,
                };
                let schema = ArrowSchema {
                    format,
                    name: ptr::null(),
                    metadata: ptr::null(),
                    flags: 0,
                    n_children: 0,
                    children: ptr::null_mut(),
                    dictionary: ptr::null_mut(),
                    release: Some(arrow_schema_release),
                    private_data: ptr::null_mut(),
                };
                (schema, array)
            }

            /// Map a schema-chosen Arrow format string to its `'static`
            /// nul-terminated C string (the exportable set is closed at codegen
            /// time — `RustGenerator::arrow_export_format`).
            fn arrow_format_cstr(fmt: &str) -> *const c_char {
                match fmt {
                    "i" => b"i\0".as_ptr() as *const c_char,
                    "l" => b"l\0".as_ptr() as *const c_char,
                    "I" => b"I\0".as_ptr() as *const c_char,
                    "L" => b"L\0".as_ptr() as *const c_char,
                    "g" => b"g\0".as_ptr() as *const c_char,
                    "w:16" => b"w:16\0".as_ptr() as *const c_char,
                    // Unreachable: the format is one of the closed exportable set.
                    _ => b"l\0".as_ptr() as *const c_char,
                }
            }

            /// A single exported live column, importable **zero-copy** by pyarrow /
            /// polars via the Arrow PyCapsule interface: `pyarrow.array(col)` (or
            /// `pa.table({"c": col}).to_pandas()`). Single-shot — the underlying
            /// export is moved into the capsules on the first `__arrow_c_array__`.
            #[pyclass]
            pub struct ArrowColumn {
                export: Option<forgedb_storage::ColumnExport>,
                length: usize,
                format: &'static str,
            }

            #[pymethods]
            impl ArrowColumn {
                /// The Arrow C Data Interface PyCapsule protocol — returns the
                /// `(schema_capsule, array_capsule)` pair a consumer imports. The
                /// exported bytes/alias transfer into the capsules (single-shot);
                /// the capsule destructors honor the Arrow release protocol.
                #[pyo3(signature = (requested_schema=None))]
                fn __arrow_c_array__<'py>(
                    &mut self,
                    py: Python<'py>,
                    requested_schema: Option<Bound<'py, PyAny>>,
                ) -> PyResult<(Bound<'py, PyCapsule>, Bound<'py, PyCapsule>)> {
                    // We export exactly our fixed schema; a requested cast is not
                    // supported (the caller can cast in pyarrow).
                    let _ = requested_schema;
                    let export = self.export.take().ok_or_else(|| {
                        ForgeDbError::new_err("Arrow column already exported (single-shot)")
                    })?;
                    let fmt = arrow_format_cstr(self.format);
                    let (schema_val, array_val) = arrow_build_primitive(fmt, export, self.length);
                    let array_cap = PyCapsule::new_with_destructor(
                        py,
                        array_val,
                        Some(CString::new("arrow_array").unwrap()),
                        |mut a: ArrowArray, _ctx: *mut c_void| {
                            if let Some(rel) = a.release {
                                unsafe { rel(&mut a) }
                            }
                        },
                    )?;
                    let schema_cap = PyCapsule::new_with_destructor(
                        py,
                        schema_val,
                        Some(CString::new("arrow_schema").unwrap()),
                        |mut s: ArrowSchema, _ctx: *mut c_void| {
                            if let Some(rel) = s.release {
                                unsafe { rel(&mut s) }
                            }
                        },
                    )?;
                    Ok((schema_cap, array_cap))
                }
            }
        }
    }

    /// The per-(model, exportable-column) Arrow export methods on `ForgeDb`:
    /// `<m>_<col>_arrow() -> ArrowColumn`. Each computes the live physical row
    /// indices in generated code (`export_live_indices`) and exports exactly those
    /// rows of the one column (`export_col_<f>` → `ColumnExport`). The exportable
    /// set + Arrow format come from `RustGenerator::arrow_export_format` (the SAME
    /// source of truth the generated `export_col_<f>` and the FFI Arrow op use), so
    /// the three can never drift. Identity: the set is fixed by the schema at
    /// codegen time (never a runtime column list); the export takes opaque indices.
    fn generate_arrow_methods(schema: &Schema) -> Vec<TokenStream> {
        let mut methods = Vec::new();
        for model in Self::identity_models(schema) {
            let snake = RustGenerator::to_snake_case(&model.name);
            let storage = format_ident!("{}", snake);
            for field in &model.fields {
                let Some(fmt) = RustGenerator::arrow_export_format(&field.field_type) else {
                    continue;
                };
                let method_ident = format_ident!("{}_{}_arrow", snake, field.name);
                let export_method = format_ident!("export_col_{}", field.name);
                let doc = format!(
                    "Export the live `{}.{}` column as a zero-copy Arrow array (`{}`) — \
                     `pyarrow.array(db.{}_{}_arrow())`.",
                    model.name, field.name, fmt, snake, field.name
                );
                methods.push(quote! {
                    #[doc = #doc]
                    fn #method_ident(&self) -> PyResult<ArrowColumn> {
                        let (export, length) = match catch_unwind(AssertUnwindSafe(|| {
                            let live = self.inner.#storage.export_live_indices();
                            let n = live.len();
                            self.inner.#storage.#export_method(&live).map(|e| (e, n))
                        })) {
                            Ok(Ok(pair)) => pair,
                            Ok(Err(e)) => return Err(to_py_err(e)),
                            Err(p) => return Err(panic_to_py_err(p)),
                        };
                        Ok(ArrowColumn { export: Some(export), length, format: #fmt })
                    }
                });
            }
        }
        methods
    }

    /// Register the `ArrowColumn` class in the module (only when the schema has an
    /// Arrow-exportable column, matching `generate_arrow_spine`).
    fn generate_arrow_registration(schema: &Schema) -> TokenStream {
        if Self::has_arrow_columns(schema) {
            quote! { m.add_class::<ArrowColumn>()?; }
        } else {
            quote! {}
        }
    }

    /// Whether any identity model has at least one Arrow-exportable column.
    fn has_arrow_columns(schema: &Schema) -> bool {
        Self::identity_models(schema).any(|m| {
            m.fields
                .iter()
                .any(|f| RustGenerator::arrow_export_format(&f.field_type).is_some())
        })
    }

    /// `m.add_class::<Py<Model>>()?` for each row class.
    fn generate_registrations(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let py_ident = format_ident!("Py{}", model.name);
                quote! { m.add_class::<#py_ident>()?; }
            })
            .collect()
    }

    fn is_virtual_relation(field_type: &forgedb_parser::FieldType) -> bool {
        use forgedb_parser::{FieldType, RelationType};
        matches!(
            field_type,
            FieldType::Relation(RelationType::OneToMany(_))
                | FieldType::Relation(RelationType::ManyToMany(_))
        )
    }

    /// The PyO3 crate's `Cargo.toml`. User-editable config — written only when
    /// absent, mirroring the FFI / wasm scaffolds. `abi3-py38` makes one wheel
    /// work across CPython ≥ 3.8; `extension-module` omits linking libpython so
    /// the cdylib builds standalone (for the compile test) and as a wheel.
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib: the Python extension module (`import forgedb`).
name = "forgedb"
crate-type = ["cdylib"]

[dependencies]
forgedb-storage = "0.2"
forgedb-types = "0.2"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
forgedb-txn = "0.1"
forgedb-coordinator = "0.2"
forgedb-query-params = "0.1"
regex = "1"
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}
pyo3 = {{ version = "0.23", features = ["abi3-py38", "extension-module"] }}
pythonize = "0.23"
"#
        )
    }
}
