//! PyO3 language-binding generator (#51) — the ergonomic Python wrapper over the
//! SAME generated `database.rs`, a sibling of the native FFI spine (`ffi.rs`) and
//! the wasm replica (`wasm.rs`).
//!
//! It emits a per-schema `#[pyclass]` surface: one row class per identity model
//! (native marshalling through the generated struct's own serde contract via
//! `pythonize` — the same single source of truth the WAL / broker / FFI use, so
//! there is no second per-field matrix to drift) plus a `ForgeDb` class whose
//! methods mirror the generated `Database` CRUD **1:1**, calling the integrity
//! wrappers (`create_<m>`/`update_<m>`/`delete_<m>`) and storage reads by name.
//!
//! Identity: every schema-specific surface is generated per-model (constraint 2);
//! there is **no** generic `query`/`filter`/`predicate` entry point and no
//! `match model` dispatch (constraint 1). The row types and methods are named
//! from the schema, which IS the tailoring.

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

use crate::rust::RustGenerator;

pub struct PyO3Generator;

impl PyO3Generator {
    /// Generate the PyO3 wrapper (`pyo3/src/lib.rs`) for a schema.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let row_classes = Self::generate_row_classes(schema);
        let db_methods = Self::generate_db_methods(schema);
        let registrations = Self::generate_registrations(schema);

        let tokens = quote! {
            //! Generated by ForgeDB — Python binding (PyO3, #51).
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue: the ergonomic Python surface over the
            //! generated `Database`. One `#[pyclass]` per identity model + a
            //! `ForgeDb` whose methods mirror the generated CRUD 1:1. The tailored
            //! data logic lives in the generated `database.rs`; this file binds it.
            //! It invents no query API (the identity red line).
            #![allow(warnings)]

            mod database;

            use pyo3::prelude::*;
            use pyo3::exceptions::PyException;
            use std::panic::{AssertUnwindSafe, catch_unwind};

            use database::Database;
            // Names the primary-key type of UUID-keyed models (`id_type_tokens`
            // emits a bare `Uuid`); integer-PK models use std types.
            use forgedb_types::Uuid;

            pyo3::create_exception!(
                forgedb,
                ForgeDbError,
                PyException,
                "Raised on any ForgeDB engine or validation error."
            );

            /// Map any engine error (`ValidationError`, `io::Error`, …) to the
            /// Python-visible `ForgeDbError`.
            fn to_py_err<E: std::fmt::Display>(e: E) -> PyErr {
                ForgeDbError::new_err(e.to_string())
            }

            /// Convert a caught panic payload into a `ForgeDbError` so an engine
            /// panic (e.g. the single-writer `DirLock`) never unwinds into the
            /// interpreter as a raw abort.
            fn panic_to_py_err(payload: Box<dyn std::any::Any + Send>) -> PyErr {
                let msg = payload
                    .downcast_ref::<&str>()
                    .map(|s| s.to_string())
                    .or_else(|| payload.downcast_ref::<String>().cloned())
                    .unwrap_or_else(|| "engine panic".to_string());
                ForgeDbError::new_err(msg)
            }

            #(#row_classes)*

            /// A ForgeDB database handle — one single-writer process over a data
            /// directory. Methods mirror the generated `Database` surface 1:1.
            #[pyclass]
            pub struct ForgeDb {
                inner: Database,
            }

            #[pymethods]
            impl ForgeDb {
                /// Open (or create) the database at `root`. Holds the single-writer
                /// lock; a second writer raises `ForgeDbError` rather than aborting.
                #[staticmethod]
                fn open(root: String) -> PyResult<Self> {
                    let root = std::path::PathBuf::from(root);
                    match catch_unwind(AssertUnwindSafe(|| Database::open_at(root))) {
                        Ok(inner) => Ok(Self { inner }),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                /// Flush every column to disk (fsync on native).
                fn commit(&mut self) -> PyResult<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.commit())) {
                        Ok(r) => r.map_err(to_py_err),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                /// Force a WAL checkpoint (fsync columns, then truncate the WAL).
                fn checkpoint(&mut self) -> PyResult<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.checkpoint())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                /// Reclaim dead (superseded/tombstoned) row versions in-process.
                /// Explicit only — never reached from a read path (constraint 4).
                fn compact(&mut self) -> PyResult<()> {
                    match catch_unwind(AssertUnwindSafe(|| self.inner.compact())) {
                        Ok(()) => Ok(()),
                        Err(p) => Err(panic_to_py_err(p)),
                    }
                }

                #(#db_methods)*
            }

            /// The generated Python module — registers the row classes, `ForgeDb`,
            /// and `ForgeDbError`.
            #[pymodule]
            fn forgedb(m: &Bound<'_, PyModule>) -> PyResult<()> {
                m.add_class::<ForgeDb>()?;
                #(#registrations)*
                m.add("ForgeDbError", m.py().get_type::<ForgeDbError>())?;
                Ok(())
            }
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!(
                "Failed to parse generated PyO3 binding: {e}"
            ))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!("Python binding (PyO3) ({} models)", schema.models.len()),
        })
    }

    /// The identity models a binding surface is generated for — those with an
    /// `id` field or an auto-generated PK (same filter as the FFI spine).
    fn identity_models(schema: &Schema) -> impl Iterator<Item = &forgedb_parser::Model> {
        schema
            .models
            .iter()
            .filter(|m| m.fields.iter().any(|f| f.name == "id" || f.auto_generate))
    }

    /// One `#[pyclass]` per identity model: a newtype over the generated struct
    /// with a dict/mapping `__init__`, `to_dict`, `__repr__`, and per-field
    /// getters — all marshalled through the struct's serde impl via `pythonize`.
    fn generate_row_classes(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let model_ident = format_ident!("{}", model.name);
                let py_ident = format_ident!("Py{}", model.name);
                let name_str = model.name.as_str();

                // Per-field getters, marshalled natively via pythonize. Virtual
                // relation collections (`OneToMany`/`ManyToMany` → `()`) carry no
                // data and are skipped.
                let getters: Vec<TokenStream> = model
                    .fields
                    .iter()
                    .filter(|f| !Self::is_virtual_relation(&f.field_type))
                    .map(|f| {
                        let fname = format_ident!("{}", f.name);
                        let doc = format!("The `{}` field.", f.name);
                        quote! {
                            #[doc = #doc]
                            #[getter]
                            fn #fname<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
                                pythonize::pythonize(py, &self.inner.#fname).map_err(to_py_err)
                            }
                        }
                    })
                    .collect();

                let new_doc = format!(
                    "Construct a `{}` from a Python mapping (dict) matching the schema fields.",
                    model.name
                );
                let dict_doc = format!("Return this `{}` as a native Python dict.", model.name);

                quote! {
                    #[doc = #new_doc]
                    #[pyclass(name = #name_str)]
                    #[derive(Clone)]
                    pub struct #py_ident {
                        inner: database::#model_ident,
                    }

                    #[pymethods]
                    impl #py_ident {
                        #[new]
                        fn new(data: &Bound<'_, PyAny>) -> PyResult<Self> {
                            let inner: database::#model_ident =
                                pythonize::depythonize(data).map_err(to_py_err)?;
                            Ok(Self { inner })
                        }

                        #[doc = #dict_doc]
                        fn to_dict<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {
                            pythonize::pythonize(py, &self.inner).map_err(to_py_err)
                        }

                        fn __repr__(&self) -> String {
                            format!("{:?}", self.inner)
                        }

                        #(#getters)*
                    }

                    impl #py_ident {
                        fn from_record(inner: database::#model_ident) -> Self {
                            Self { inner }
                        }
                    }
                }
            })
            .collect()
    }

    /// The per-model CRUD methods on `ForgeDb`, mirroring the generated `Database`
    /// integrity wrappers + storage reads 1:1.
    fn generate_db_methods(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let snake = RustGenerator::to_snake_case(&model.name);
                let model_ident = format_ident!("{}", model.name);
                let py_ident = format_ident!("Py{}", model.name);
                let storage = format_ident!("{}", snake);
                let id_ty = RustGenerator::id_type_tokens(model);

                let create_fn = format_ident!("create_{}", snake);
                let update_fn = format_ident!("update_{}", snake);
                let delete_fn = format_ident!("delete_{}", snake);

                let create_m = format_ident!("create_{}", snake);
                let get_m = format_ident!("get_{}", snake);
                let all_m = format_ident!("all_{}", snake);
                let count_m = format_ident!("count_{}", snake);
                let update_m = format_ident!("update_{}", snake);
                let delete_m = format_ident!("delete_{}", snake);

                let create_doc = format!(
                    "Insert a `{}` (FK-checked + validated); returns the new id.",
                    model.name
                );
                let get_doc =
                    format!("Fetch a `{}` by id, or `None` if absent.", model.name);
                let all_doc = format!("Every live `{}`.", model.name);
                let count_doc = format!("Live `{}` row count.", model.name);
                let update_doc = format!(
                    "Update a `{}` by id; `True` if present, `False` if absent.",
                    model.name
                );
                let delete_doc = format!(
                    "Delete a `{}` by id (referential integrity enforced); `True`/`False`.",
                    model.name
                );

                quote! {
                    #[doc = #create_doc]
                    fn #create_m<'py>(
                        &mut self,
                        record: &Bound<'py, PyAny>,
                    ) -> PyResult<Bound<'py, PyAny>> {
                        let py = record.py();
                        let record: database::#model_ident =
                            pythonize::depythonize(record).map_err(to_py_err)?;
                        let id = match catch_unwind(AssertUnwindSafe(|| self.inner.#create_fn(record))) {
                            Ok(r) => r.map_err(to_py_err)?,
                            Err(p) => return Err(panic_to_py_err(p)),
                        };
                        pythonize::pythonize(py, &id).map_err(to_py_err)
                    }

                    #[doc = #get_doc]
                    fn #get_m(&self, id: &Bound<'_, PyAny>) -> PyResult<Option<#py_ident>> {
                        let id: #id_ty = pythonize::depythonize(id).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.get(id))) {
                            Ok(opt) => Ok(opt.map(#py_ident::from_record)),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #all_doc]
                    fn #all_m(&self) -> PyResult<Vec<#py_ident>> {
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.all())) {
                            Ok(rows) => Ok(rows.into_iter().map(#py_ident::from_record).collect()),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #count_doc]
                    fn #count_m(&self) -> PyResult<usize> {
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#storage.row_count())) {
                            Ok(n) => Ok(n),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #update_doc]
                    fn #update_m(
                        &mut self,
                        id: &Bound<'_, PyAny>,
                        record: &Bound<'_, PyAny>,
                    ) -> PyResult<bool> {
                        let id: #id_ty = pythonize::depythonize(id).map_err(to_py_err)?;
                        let record: database::#model_ident =
                            pythonize::depythonize(record).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#update_fn(id, record))) {
                            Ok(r) => r.map_err(to_py_err),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }

                    #[doc = #delete_doc]
                    fn #delete_m(&mut self, id: &Bound<'_, PyAny>) -> PyResult<bool> {
                        let id: #id_ty = pythonize::depythonize(id).map_err(to_py_err)?;
                        match catch_unwind(AssertUnwindSafe(|| self.inner.#delete_fn(id))) {
                            Ok(r) => r.map_err(to_py_err),
                            Err(p) => Err(panic_to_py_err(p)),
                        }
                    }
                }
            })
            .collect()
    }

    /// `m.add_class::<Py<Model>>()?` for each row class.
    fn generate_registrations(schema: &Schema) -> Vec<TokenStream> {
        Self::identity_models(schema)
            .map(|model| {
                let py_ident = format_ident!("Py{}", model.name);
                quote! { m.add_class::<#py_ident>()?; }
            })
            .collect()
    }

    fn is_virtual_relation(field_type: &forgedb_parser::FieldType) -> bool {
        use forgedb_parser::{FieldType, RelationType};
        matches!(
            field_type,
            FieldType::Relation(RelationType::OneToMany(_))
                | FieldType::Relation(RelationType::ManyToMany(_))
        )
    }

    /// The PyO3 crate's `Cargo.toml`. User-editable config — written only when
    /// absent, mirroring the FFI / wasm scaffolds. `abi3-py38` makes one wheel
    /// work across CPython ≥ 3.8; `extension-module` omits linking libpython so
    /// the cdylib builds standalone (for the compile test) and as a wheel.
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[lib]
# cdylib: the Python extension module (`import forgedb`).
name = "forgedb"
crate-type = ["cdylib"]

[dependencies]
forgedb-storage = "0.2"
forgedb-types = "0.2"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
forgedb-txn = "0.1"
forgedb-coordinator = "0.1"
forgedb-query-params = "0.1"
forgedb-auth = "0.1"
regex = "1"
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}
pyo3 = {{ version = "0.23", features = ["abi3-py38", "extension-module"] }}
pythonize = "0.23"
"#
        )
    }
}
