//! Rust database code generator
//!
//! Generates optimized Rust code with columnar storage for ForgeDB schemas.

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Rust code generator
pub struct RustGenerator;

impl RustGenerator {
    /// Generate Rust database implementation from schema
    ///
    /// # Arguments
    ///
    /// * `schema` - Parsed schema AST
    ///
    /// # Returns
    ///
    /// Generated Rust code as a string
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let code = Self::generate_code(schema)?;

        Ok(GeneratedCode {
            code,
            description: format!(
                "Rust database implementation ({} models)",
                schema.models.len()
            ),
        })
    }

    /// Generate the Rust code as a string
    fn generate_code(schema: &Schema) -> Result<String> {
        let mut tokens = TokenStream::new();

        // File header comments
        let header = quote! {
            //! Generated by ForgeDB
            //! DO NOT EDIT - This file is auto-generated
        };
        tokens.extend(header);

        // Attributes and imports
        let imports = quote! {
            #![allow(dead_code, unused_imports)]

            use std::collections::HashMap;
            use std::path::Path;
            use forgedb_storage::ColumnarStorage;
            use forgedb_types::{Uuid, Timestamp, Value};
        };
        tokens.extend(imports);

        // Generate models
        for model in &schema.models {
            let model_tokens = Self::generate_model(model)?;
            tokens.extend(model_tokens);
        }

        // Generate database struct
        let db_tokens = Self::generate_database(schema)?;
        tokens.extend(db_tokens);

        Ok(tokens.to_string())
    }

    /// Generate a single model struct
    fn generate_model(model: &forgedb_parser::Model) -> Result<TokenStream> {
        let model_name = format_ident!("{}", model.name);
        let storage_name = format_ident!("{}Storage", model.name);
        let model_doc = format!("{} model", model.name);
        let storage_doc = format!("Storage for {} model", model.name);

        // Generate field definitions
        let fields: Vec<_> = model
            .fields
            .iter()
            .map(|field| {
                let field_name = format_ident!("{}", field.name);
                let field_type = Self::map_field_type_ident(&field.field_type);

                if field.is_nullable() {
                    quote! { pub #field_name: Option<#field_type> }
                } else {
                    quote! { pub #field_name: #field_type }
                }
            })
            .collect();

        // Generate the model struct, storage struct, and implementation
        let tokens = quote! {
            #[doc = #model_doc]
            #[derive(Debug, Clone)]
            pub struct #model_name {
                #(#fields),*
            }

            #[doc = #storage_doc]
            pub struct #storage_name {
                // TODO: Implement columnar storage fields
            }

            impl #storage_name {
                pub fn new() -> Self {
                    Self {
                        // TODO: Initialize storage
                    }
                }

                pub fn insert(&mut self, record: #model_name) -> Uuid {
                    // TODO: Implement insert
                    Uuid::new_v4()
                }

                pub fn get(&self, id: Uuid) -> Option<#model_name> {
                    // TODO: Implement get
                    None
                }
            }
        };

        Ok(tokens)
    }

    /// Generate the main database struct
    fn generate_database(schema: &Schema) -> Result<TokenStream> {
        // Generate field definitions for each model storage
        let db_fields: Vec<_> = schema
            .models
            .iter()
            .map(|model| {
                let field_name = format_ident!("{}", Self::to_snake_case(&model.name));
                let storage_type = format_ident!("{}Storage", model.name);
                quote! { pub #field_name: #storage_type }
            })
            .collect();

        // Generate field initializers for the new() method
        let db_inits: Vec<_> = schema
            .models
            .iter()
            .map(|model| {
                let field_name = format_ident!("{}", Self::to_snake_case(&model.name));
                let storage_type = format_ident!("{}Storage", model.name);
                quote! { #field_name: #storage_type::new() }
            })
            .collect();

        let tokens = quote! {
            /// Main database struct
            pub struct Database {
                #(#db_fields),*
            }

            impl Database {
                pub fn new() -> Self {
                    Self {
                        #(#db_inits),*
                    }
                }
            }
        };

        Ok(tokens)
    }

    /// Map ForgeDB field type to Rust type identifier for use with quote!
    fn map_field_type_ident(field_type: &forgedb_parser::FieldType) -> TokenStream {
        match field_type {
            forgedb_parser::FieldType::U32 => quote! { u32 },
            forgedb_parser::FieldType::U64 => quote! { u64 },
            forgedb_parser::FieldType::I32 => quote! { i32 },
            forgedb_parser::FieldType::I64 => quote! { i64 },
            forgedb_parser::FieldType::F64 => quote! { f64 },
            forgedb_parser::FieldType::Bool => quote! { bool },
            forgedb_parser::FieldType::String => quote! { String },
            forgedb_parser::FieldType::Uuid => quote! { Uuid },
            forgedb_parser::FieldType::Timestamp => quote! { Timestamp },
            forgedb_parser::FieldType::StructType(name) => {
                let ident = format_ident!("{}", name);
                quote! { #ident }
            }
            forgedb_parser::FieldType::OptionalStructType(name) => {
                let ident = format_ident!("{}", name);
                quote! { #ident }
            }
            forgedb_parser::FieldType::Char(size) => {
                quote! { [u8; #size] }
            }
            forgedb_parser::FieldType::FixedArray(inner, count) => {
                let inner_type = Self::map_field_type_ident(inner);
                quote! { [#inner_type; #count] }
            }
            forgedb_parser::FieldType::Relation(rel) => {
                match rel {
                    forgedb_parser::RelationType::RequiredReference(_) => quote! { Uuid },
                    forgedb_parser::RelationType::OptionalReference(_) => quote! { Uuid },
                    _ => quote! { () }, // Virtual fields
                }
            }
            _ => quote! { String }, // Default fallback
        }
    }

    /// Convert PascalCase to snake_case
    fn to_snake_case(s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use forgedb_parser::ast::IndexType;
    use forgedb_parser::{Field, FieldType, Model, Schema};

    #[test]
    fn test_rust_generation_with_quote() {
        // Create a simple schema
        let schema = Schema {
            models: vec![Model {
                name: "User".to_string(),
                fields: vec![
                    Field {
                        name: "id".to_string(),
                        field_type: FieldType::Uuid,
                        auto_generate: true,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    },
                    Field {
                        name: "email".to_string(),
                        field_type: FieldType::String,
                        auto_generate: false,
                        unique: true,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    },
                    Field {
                        name: "age".to_string(),
                        field_type: FieldType::OptionalStructType("Age".to_string()),
                        auto_generate: false,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    },
                ],
                composite_indexes: vec![],
                soft_delete: false,
            }],
            structs: vec![],
        };

        let result = RustGenerator::generate(&schema).unwrap();
        let code = result.code;

        // Verify the generated code contains expected elements
        // Note: quote! generates tokens without spaces, so we check for the structure
        assert!(code.contains("pub struct User"));
        assert!(code.contains("pub id : Uuid"));
        assert!(code.contains("pub email : String"));
        assert!(code.contains("pub age : Option < Age >") || code.contains("pub age : Option <Age>") || code.contains("pub age : Option<Age>"));
        assert!(code.contains("pub struct UserStorage"));
        assert!(code.contains("pub struct Database"));
        assert!(code.contains("pub user : UserStorage"));
        assert!(code.contains("impl UserStorage"));
        assert!(code.contains("pub fn new"));
        assert!(code.contains("pub fn insert"));
        assert!(code.contains("pub fn get"));

        // Verify it compiles as valid Rust (basic syntax check)
        assert!(code.contains("use std :: collections :: HashMap"));
        assert!(code.contains("use forgedb_types :: { Uuid , Timestamp , Value }"));
    }

    #[test]
    fn test_multiple_models() {
        let schema = Schema {
            models: vec![
                Model {
                    name: "User".to_string(),
                    fields: vec![Field {
                        name: "id".to_string(),
                        field_type: FieldType::Uuid,
                        auto_generate: true,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    }],
                    composite_indexes: vec![],
                    soft_delete: false,
                },
                Model {
                    name: "Post".to_string(),
                    fields: vec![Field {
                        name: "id".to_string(),
                        field_type: FieldType::Uuid,
                        auto_generate: true,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    }],
                    composite_indexes: vec![],
                    soft_delete: false,
                },
            ],
            structs: vec![],
        };

        let result = RustGenerator::generate(&schema).unwrap();
        let code = result.code;

        assert!(code.contains("pub struct User"));
        assert!(code.contains("pub struct Post"));
        assert!(code.contains("pub struct UserStorage"));
        assert!(code.contains("pub struct PostStorage"));
        assert!(code.contains("pub user : UserStorage"));
        assert!(code.contains("pub post : PostStorage"));
    }
}
