//! Rust REST client SDK generator (`generate rust --sdk`, #206).
//!
//! Emits a standalone, `reqwest`-based async client crate for the generated REST
//! API — the Rust sibling of the TypeScript SDK (`typescript.rs`). It produces:
//!
//! - serde `struct`s for each model, a `<Model>Create` input, and one struct per
//!   `@projection` (#113);
//! - native `enum`s for each declared `#enum` (serialized as the variant-name
//!   string, matching the wire);
//! - a shared `ForgeDbError` / `ListResult<T>` / `ListOptions` surface;
//! - a `ForgeDbClient` with full CRUD (get / list / create / update / delete) plus
//!   per-projection read methods, faithfully wrapping the REST endpoint's real
//!   response shapes and status codes.
//!
//! Like the TS SDK, this is a *transport client* over the already-generated,
//! schema-tailored REST surface — it interprets no schema at runtime, so it is
//! class-2 access glue (per `CLAUDE.md`'s generator-identity invariant), not a
//! generic runtime or query builder.

use crate::rust::RustGenerator;
use crate::{GeneratedCode, Result};
use forgedb_parser::{Field, FieldType, Model, RelationType, Schema};

/// Rust REST client SDK generator.
pub struct RustSdkGenerator;

impl RustSdkGenerator {
    /// Generate the Rust SDK (`src/lib.rs`) for a schema.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let raw = Self::generate_code(schema);
        // Parse + reformat with prettyplease: this both pretty-prints the output
        // and validates that the emitted string is syntactically valid Rust at
        // generation time (a parse error surfaces here, not at the user's
        // `cargo build`).
        let code = match syn::parse_file(&raw) {
            Ok(tree) => prettyplease::unparse(&tree),
            Err(e) => {
                return Err(crate::CodegenError::GenerationFailed(format!(
                    "generated Rust SDK did not parse: {e}"
                )));
            }
        };
        Ok(GeneratedCode {
            code,
            description: format!("Rust REST client SDK ({} models)", schema.models.len()),
        })
    }

    /// The `Cargo.toml` for the generated SDK crate. Written next to `src/lib.rs`
    /// only when absent, so user edits survive regeneration. A leaf client crate
    /// (edition 2021 for the widest consumer toolchain range) — it links none of
    /// the forgedb substrate crates, only `reqwest`/`serde`.
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            "[package]\n\
             name = \"{crate_name}\"\n\
             version = \"0.1.0\"\n\
             edition = \"2021\"\n\
             \n\
             [dependencies]\n\
             reqwest = {{ version = \"0.12\", features = [\"json\"] }}\n\
             serde = {{ version = \"1\", features = [\"derive\"] }}\n\
             serde_json = \"1\"\n\
             \n\
             # The client methods are `async`; bring your own runtime, e.g.:\n\
             # tokio = {{ version = \"1\", features = [\"full\"] }}\n"
        )
    }

    fn generate_code(schema: &Schema) -> String {
        let mut c = String::new();
        c.push_str(
            "// Generated by ForgeDB — DO NOT EDIT\n\
             //\n\
             // Rust REST client SDK for a ForgeDB app. A transport client over the\n\
             // generated REST API; it interprets no schema at runtime.\n\
             #![allow(dead_code, clippy::all)]\n\n\
             use serde::{Deserialize, Serialize};\n\n",
        );

        // Enums first — models reference them.
        for en in &schema.enums {
            c.push_str(&format!(
                "/// `{name}` enum — serialized as its variant-name string.\n\
                 #[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]\n\
                 pub enum {name} {{\n",
                name = en.name
            ));
            for v in &en.variants {
                c.push_str(&format!("    {v},\n"));
            }
            c.push_str("}\n\n");
        }

        // Models + create-input + projection structs.
        for model in &schema.models {
            Self::push_model_struct(&mut c, model);
            Self::push_create_struct(&mut c, model);
            Self::push_projection_structs(&mut c, model);
        }

        c.push_str(Self::shared_types());
        Self::push_client(&mut c, schema);
        c
    }

    fn push_model_struct(c: &mut String, model: &Model) {
        c.push_str(&format!(
            "/// `{name}` — mirrors the wire shape of the generated model.\n\
             #[derive(Debug, Clone, Serialize, Deserialize)]\n\
             pub struct {name} {{\n",
            name = model.name
        ));
        for field in &model.fields {
            c.push_str(&format!("    pub {}: {},\n", field.name, Self::map_type(field)));
        }
        c.push_str("}\n\n");
    }

    fn push_create_struct(c: &mut String, model: &Model) {
        c.push_str(&format!(
            "/// Input to `create_{snake}` — a `{name}` without the fields the server\n\
             /// synthesizes (`+uuid`/`+timestamp` autos).\n\
             #[derive(Debug, Clone, Serialize)]\n\
             pub struct {name}Create {{\n",
            snake = RustGenerator::to_snake_case(&model.name),
            name = model.name
        ));
        for field in RustGenerator::creatable_fields(model) {
            c.push_str(&format!("    pub {}: {},\n", field.name, Self::map_type(field)));
        }
        c.push_str("}\n\n");
    }

    fn push_projection_structs(c: &mut String, model: &Model) {
        for proj in &model.projections {
            let ty = format!(
                "{}{}",
                model.name,
                RustGenerator::projection_pascal(&proj.name)
            );
            c.push_str(&format!(
                "/// Projection `{proj}` of `{model}` — PK + declared columns only.\n\
                 #[derive(Debug, Clone, Deserialize)]\n\
                 pub struct {ty} {{\n",
                proj = proj.name,
                model = model.name
            ));
            for field in RustGenerator::projected_field_set(model, proj) {
                c.push_str(&format!("    pub {}: {},\n", field.name, Self::map_type(field)));
            }
            c.push_str("}\n\n");
        }
    }

    /// The schema-independent SDK support types + the HTTP client scaffolding.
    fn shared_types() -> &'static str {
        r#"/// Raised on any non-2xx response (except a get / update / delete 404, which
/// the corresponding methods surface as `None` / `false`), and on transport
/// failures (`status == 0`). Carries the HTTP status and the parsed `{ error }`
/// body when present.
#[derive(Debug, Clone)]
pub struct ForgeDbError {
    pub status: u16,
    pub message: String,
    pub body: Option<serde_json::Value>,
}

impl std::fmt::Display for ForgeDbError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "ForgeDB error (status {}): {}", self.status, self.message)
    }
}

impl std::error::Error for ForgeDbError {}

impl ForgeDbError {
    /// A transport/client-side failure (connection refused, body decode, …):
    /// `status == 0`, no server body.
    fn transport(e: reqwest::Error) -> Self {
        Self { status: 0, message: e.to_string(), body: None }
    }
}

/// A page of list results — mirrors the REST list endpoint's response envelope.
#[derive(Debug, Clone, Deserialize)]
pub struct ListResult<T> {
    pub data: Vec<T>,
    pub total: usize,
    pub limit: usize,
    pub offset: usize,
}

/// Sort direction for a list query.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SortOrder {
    Asc,
    Desc,
}

impl SortOrder {
    fn as_str(self) -> &'static str {
        match self {
            SortOrder::Asc => "asc",
            SortOrder::Desc => "desc",
        }
    }
}

/// Options for a list query. `filter` holds exact-match `?field=value` pairs
/// matched by the generated per-model filter server-side.
#[derive(Debug, Clone, Default)]
pub struct ListOptions {
    pub limit: Option<usize>,
    pub offset: Option<usize>,
    pub sort: Option<String>,
    pub order: Option<SortOrder>,
    pub filter: Vec<(String, String)>,
}

/// The REST create/update response body (`{ "id": "..." }`).
#[derive(Deserialize)]
struct CreatedId {
    id: String,
}

/// Percent-encode one URL path segment (RFC 3986 unreserved set passes through),
/// so an arbitrary string id is safe to interpolate into the path.
fn encode_segment(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' => {
                out.push(b as char)
            }
            _ => out.push_str(&format!("%{:02X}", b)),
        }
    }
    out
}

/// A typed async client for a ForgeDB app's REST API.
pub struct ForgeDbClient {
    base_url: String,
    http: reqwest::Client,
}

impl ForgeDbClient {
    /// Build a client targeting `base_url` (a trailing slash is trimmed).
    pub fn new(base_url: impl Into<String>) -> Self {
        Self {
            base_url: base_url.into().trim_end_matches('/').to_string(),
            http: reqwest::Client::new(),
        }
    }

    /// Build a client over a caller-supplied `reqwest::Client` (custom timeouts,
    /// default headers, a proxy, …).
    pub fn with_client(base_url: impl Into<String>, http: reqwest::Client) -> Self {
        Self {
            base_url: base_url.into().trim_end_matches('/').to_string(),
            http,
        }
    }

    /// Build the `?limit=&offset=&sort=&order=&<filter>` query pairs for a list.
    fn list_query(&self, options: &ListOptions) -> Vec<(String, String)> {
        let mut q: Vec<(String, String)> = Vec::new();
        if let Some(v) = options.limit {
            q.push(("limit".to_string(), v.to_string()));
        }
        if let Some(v) = options.offset {
            q.push(("offset".to_string(), v.to_string()));
        }
        if let Some(v) = &options.sort {
            q.push(("sort".to_string(), v.clone()));
        }
        if let Some(v) = options.order {
            q.push(("order".to_string(), v.as_str().to_string()));
        }
        for (k, val) in &options.filter {
            q.push((k.clone(), val.clone()));
        }
        q
    }

    /// Map a non-2xx response to a typed `ForgeDbError`, extracting the server's
    /// `{ error }` message when the body is JSON; pass a 2xx response through.
    async fn assert_ok(&self, response: reqwest::Response) -> std::result::Result<reqwest::Response, ForgeDbError> {
        if response.status().is_success() {
            return Ok(response);
        }
        let status = response.status().as_u16();
        let body = response.json::<serde_json::Value>().await.ok();
        let message = body
            .as_ref()
            .and_then(|b| b.get("error"))
            .and_then(|e| e.as_str())
            .map(|s| s.to_string())
            .unwrap_or_else(|| format!("HTTP {status}"));
        Err(ForgeDbError { status, message, body })
    }
}

"#
    }

    fn push_client(c: &mut String, schema: &Schema) {
        // A second `impl` block carrying the per-model methods (the first block,
        // in `shared_types`, holds `new`/helpers).
        c.push_str("impl ForgeDbClient {\n");
        for model in &schema.models {
            let name = &model.name;
            let snake = RustGenerator::to_snake_case(name);
            let kebab = Self::to_kebab_case(name);

            // get
            c.push_str(&format!(
                "    /// Get a `{name}` by id, or `None` if it does not exist.\n\
                 \x20   pub async fn get_{snake}(&self, id: &str) -> std::result::Result<Option<{name}>, ForgeDbError> {{\n\
                 \x20       let url = format!(\"{{}}/api/{kebab}/{{}}\", self.base_url, encode_segment(id));\n\
                 \x20       let response = self.http.get(&url).send().await.map_err(ForgeDbError::transport)?;\n\
                 \x20       if response.status().as_u16() == 404 {{ return Ok(None); }}\n\
                 \x20       let response = self.assert_ok(response).await?;\n\
                 \x20       response.json::<{name}>().await.map(Some).map_err(ForgeDbError::transport)\n\
                 \x20   }}\n\n"
            ));

            // list
            c.push_str(&format!(
                "    /// List `{name}` rows with optional pagination, sort, and exact-match filters.\n\
                 \x20   pub async fn list_{snake}(&self, options: &ListOptions) -> std::result::Result<ListResult<{name}>, ForgeDbError> {{\n\
                 \x20       let url = format!(\"{{}}/api/{kebab}\", self.base_url);\n\
                 \x20       let response = self.http.get(&url).query(&self.list_query(options)).send().await.map_err(ForgeDbError::transport)?;\n\
                 \x20       let response = self.assert_ok(response).await?;\n\
                 \x20       response.json::<ListResult<{name}>>().await.map_err(ForgeDbError::transport)\n\
                 \x20   }}\n\n"
            ));

            // create
            c.push_str(&format!(
                "    /// Create a `{name}`. Returns the new id. Errors (`ForgeDbError`) on a\n\
                 \x20   /// constraint (422) or integrity conflict (409).\n\
                 \x20   pub async fn create_{snake}(&self, data: &{name}Create) -> std::result::Result<String, ForgeDbError> {{\n\
                 \x20       let url = format!(\"{{}}/api/{kebab}\", self.base_url);\n\
                 \x20       let response = self.http.post(&url).json(data).send().await.map_err(ForgeDbError::transport)?;\n\
                 \x20       let response = self.assert_ok(response).await?;\n\
                 \x20       response.json::<CreatedId>().await.map(|r| r.id).map_err(ForgeDbError::transport)\n\
                 \x20   }}\n\n"
            ));

            // update
            c.push_str(&format!(
                "    /// Replace a `{name}` by id (whole-record PUT). Returns `false` if the id\n\
                 \x20   /// does not exist; errors on a constraint/conflict.\n\
                 \x20   pub async fn update_{snake}(&self, id: &str, data: &{name}) -> std::result::Result<bool, ForgeDbError> {{\n\
                 \x20       let url = format!(\"{{}}/api/{kebab}/{{}}\", self.base_url, encode_segment(id));\n\
                 \x20       let response = self.http.put(&url).json(data).send().await.map_err(ForgeDbError::transport)?;\n\
                 \x20       if response.status().as_u16() == 404 {{ return Ok(false); }}\n\
                 \x20       self.assert_ok(response).await?;\n\
                 \x20       Ok(true)\n\
                 \x20   }}\n\n"
            ));

            // delete
            c.push_str(&format!(
                "    /// Delete a `{name}` by id. Returns `true` if deleted, `false` if absent.\n\
                 \x20   /// Errors (409) if `@on_delete(restrict)` children block it.\n\
                 \x20   pub async fn delete_{snake}(&self, id: &str) -> std::result::Result<bool, ForgeDbError> {{\n\
                 \x20       let url = format!(\"{{}}/api/{kebab}/{{}}\", self.base_url, encode_segment(id));\n\
                 \x20       let response = self.http.delete(&url).send().await.map_err(ForgeDbError::transport)?;\n\
                 \x20       if response.status().as_u16() == 404 {{ return Ok(false); }}\n\
                 \x20       self.assert_ok(response).await?;\n\
                 \x20       Ok(true)\n\
                 \x20   }}\n\n"
            ));

            // projections
            for proj in &model.projections {
                let ty = format!("{}{}", name, RustGenerator::projection_pascal(&proj.name));
                let proj_snake = RustGenerator::to_snake_case(&proj.name);
                let pname = &proj.name;
                c.push_str(&format!(
                    "    /// Get the `{pname}` projection of a `{name}` by id, or `None` if absent.\n\
                     \x20   pub async fn get_{snake}_{proj_snake}(&self, id: &str) -> std::result::Result<Option<{ty}>, ForgeDbError> {{\n\
                     \x20       let url = format!(\"{{}}/api/{kebab}/{{}}\", self.base_url, encode_segment(id));\n\
                     \x20       let response = self.http.get(&url).query(&[(\"projection\", \"{pname}\")]).send().await.map_err(ForgeDbError::transport)?;\n\
                     \x20       if response.status().as_u16() == 404 {{ return Ok(None); }}\n\
                     \x20       let response = self.assert_ok(response).await?;\n\
                     \x20       response.json::<{ty}>().await.map(Some).map_err(ForgeDbError::transport)\n\
                     \x20   }}\n\n"
                ));
                c.push_str(&format!(
                    "    /// List `{name}` rows as the `{pname}` projection (PK + declared columns).\n\
                     \x20   pub async fn list_{snake}_{proj_snake}(&self, options: &ListOptions) -> std::result::Result<ListResult<{ty}>, ForgeDbError> {{\n\
                     \x20       let url = format!(\"{{}}/api/{kebab}\", self.base_url);\n\
                     \x20       let mut q = self.list_query(options);\n\
                     \x20       q.push((\"projection\".to_string(), \"{pname}\".to_string()));\n\
                     \x20       let response = self.http.get(&url).query(&q).send().await.map_err(ForgeDbError::transport)?;\n\
                     \x20       let response = self.assert_ok(response).await?;\n\
                     \x20       response.json::<ListResult<{ty}>>().await.map_err(ForgeDbError::transport)\n\
                     \x20   }}\n\n"
                ));
            }
        }
        c.push_str("}\n");
    }

    /// Map a schema field to its Rust SDK wire type. Scalars map precisely; a FK
    /// reference is the uuid it stores (`String`); the opaque bucket (`json`,
    /// `char(N)`, fixed arrays, inline structs, and virtual one-to-many / M2M
    /// relations, which the server serializes as `null`) maps to
    /// `serde_json::Value` — the honest analogue of the TS SDK's `unknown`/`any`.
    fn map_type(field: &Field) -> String {
        let (opaque, base) = Self::base_type(&field.field_type);
        if opaque {
            // `serde_json::Value` already holds `null`, so nullability needs no
            // extra wrapper.
            base
        } else if field.is_nullable() {
            format!("Option<{base}>")
        } else {
            base
        }
    }

    /// `(is_opaque, base_type)` for a field type, unwrapping `Nullable`.
    fn base_type(ft: &FieldType) -> (bool, String) {
        match ft {
            FieldType::U32 => (false, "u32".into()),
            FieldType::U64 => (false, "u64".into()),
            FieldType::I32 => (false, "i32".into()),
            FieldType::I64 => (false, "i64".into()),
            FieldType::F64 => (false, "f64".into()),
            FieldType::Timestamp => (false, "i64".into()),
            FieldType::Bool => (false, "bool".into()),
            FieldType::String | FieldType::Uuid => (false, "String".into()),
            // decimal rides the wire as a precision-preserving JSON string.
            FieldType::Decimal => (false, "String".into()),
            FieldType::Enum(name) => (false, name.clone()),
            FieldType::Relation(RelationType::RequiredReference(_))
            | FieldType::Relation(RelationType::OptionalReference(_)) => (false, "String".into()),
            FieldType::Nullable(inner) => Self::base_type(inner),
            // Opaque bucket — same class as the TS SDK's `unknown`/`any`.
            _ => (true, "serde_json::Value".into()),
        }
    }

    /// PascalCase model name → kebab-case URL segment (matches the Rust router).
    fn to_kebab_case(s: &str) -> String {
        let mut result = String::new();
        for (i, ch) in s.chars().enumerate() {
            if ch.is_uppercase() && i > 0 {
                result.push('-');
            }
            result.push(ch.to_ascii_lowercase());
        }
        result
    }
}
