//! Rust database code generator
//!
//! Generates optimized Rust code with columnar storage for ForgeDB schemas.

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;
use proc_macro2::TokenStream;
use quote::{format_ident, quote};

/// Rust code generator
pub struct RustGenerator;

impl RustGenerator {
    /// Generate Rust database implementation from schema
    ///
    /// # Arguments
    ///
    /// * `schema` - Parsed schema AST
    ///
    /// # Returns
    ///
    /// Generated Rust code as a string
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let code = Self::generate_code(schema)?;

        Ok(GeneratedCode {
            code,
            description: format!(
                "Rust database implementation ({} models)",
                schema.models.len()
            ),
        })
    }

    /// Generate the Rust code as a string
    fn generate_code(schema: &Schema) -> Result<String> {
        let mut tokens = TokenStream::new();

        // File header comments
        let header = quote! {
            //! Generated by ForgeDB
            //! DO NOT EDIT - This file is auto-generated
        };
        tokens.extend(header);

        // Attributes and imports
        let imports = quote! {
            #![allow(dead_code, unused_imports)]

            use std::collections::HashMap;
            use std::path::{Path, PathBuf};
            use forgedb_storage::{FixedColumn, VariableColumn, Tombstones};
            use forgedb_types::{Uuid, Timestamp, Value};
            use serde::{Deserialize, Serialize};
            use utoipa::ToSchema;
        };
        tokens.extend(imports);

        // Generate models
        for model in &schema.models {
            let model_tokens = Self::generate_model(model, schema)?;
            tokens.extend(model_tokens);
        }

        // Generate database struct
        let db_tokens = Self::generate_database(schema)?;
        tokens.extend(db_tokens);

        // Parse and format with prettyplease
        let syntax_tree = syn::parse_file(&tokens.to_string())
            .map_err(|e| crate::CodegenError::GenerationFailed(format!("Failed to parse generated code: {}", e)))?;

        Ok(prettyplease::unparse(&syntax_tree))
    }

    /// Generate a single model struct
    fn generate_model(model: &forgedb_parser::Model, schema: &Schema) -> Result<TokenStream> {
        let model_name = format_ident!("{}", model.name);
        let storage_name = format_ident!("{}Storage", model.name);
        let model_doc = format!("{} model", model.name);
        let storage_doc = format!("Storage for {} model", model.name);

        // Generate field definitions
        let fields: Vec<_> = model
            .fields
            .iter()
            .map(|field| {
                let field_name = format_ident!("{}", field.name);
                let field_type = Self::map_field_type_ident(&field.field_type);

                if field.is_nullable() {
                    quote! { pub #field_name: Option<#field_type> }
                } else {
                    quote! { pub #field_name: #field_type }
                }
            })
            .collect();

        // Generate columnar storage fields
        let storage_fields = Self::generate_storage_fields(model);

        // Generate storage initialization
        let storage_inits = Self::generate_storage_inits(model, schema);

        // Generate insert logic
        let insert_logic = Self::generate_insert_logic(model);

        // Generate get logic
        let get_logic = Self::generate_get_logic(model);

        // Generate the model struct, storage struct, and implementation
        let tokens = quote! {
            #[doc = #model_doc]
            #[repr(C)]
            #[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
            pub struct #model_name {
                #(#fields),*
            }

            #[doc = #storage_doc]
            pub struct #storage_name {
                #storage_fields
            }

            impl #storage_name {
                pub fn new() -> Self {
                    Self {
                        #storage_inits
                    }
                }

                pub fn insert(&mut self, record: #model_name) -> Uuid {
                    #insert_logic
                }

                // Takes `&mut self` because the columnar readers seek the
                // underlying files, which requires mutable access.
                pub fn get(&mut self, id: Uuid) -> Option<#model_name> {
                    #get_logic
                }
            }
        };

        Ok(tokens)
    }

    /// Generate storage field declarations for columnar storage
    fn generate_storage_fields(model: &forgedb_parser::Model) -> TokenStream {
        let mut column_fields = Vec::new();

        for field in &model.fields {
            let field_col_name = format_ident!("{}_col", field.name);

            if Self::is_fixed_size_type(&field.field_type) {
                column_fields.push(quote! {
                    #field_col_name: FixedColumn
                });
            } else if Self::is_string_type(&field.field_type) {
                column_fields.push(quote! {
                    #field_col_name: VariableColumn
                });
            }
            // Skip relations and other non-storage types
        }

        quote! {
            id_to_row: HashMap<Uuid, usize>,
            row_count: usize,
            #(#column_fields,)*
            tombstones: forgedb_storage::Tombstones,
        }
    }

    /// Generate storage initialization code
    fn generate_storage_inits(model: &forgedb_parser::Model, _schema: &Schema) -> TokenStream {
        let mut inits = Vec::new();
        let mut column_index = 0usize;
        // Namespace all storage paths under the model name to prevent collision
        let model_snake = Self::to_snake_case(&model.name);

        for field in &model.fields {
            let field_col_name = format_ident!("{}_col", field.name);

            if Self::is_fixed_size_type(&field.field_type) {
                let col_path = format!(
                    "{}/fixed/{}_{}.bin",
                    model_snake,
                    Self::type_name(&field.field_type),
                    column_index
                );
                // C3: emit size_of in generated code so column size matches the Rust type
                let value_size_expr =
                    Self::column_value_size_expr(&field.field_type);

                inits.push(quote! {
                    #field_col_name: FixedColumn::new(
                        PathBuf::from(#col_path),
                        #value_size_expr
                    ).expect("Failed to create fixed column")
                });
                column_index += 1;
            } else if Self::is_string_type(&field.field_type) {
                let data_path = format!("{}/variable/string_data_{}.bin", model_snake, column_index);
                let offsets_path = format!("{}/variable/string_offsets_{}.bin", model_snake, column_index);

                inits.push(quote! {
                    #field_col_name: VariableColumn::new(
                        PathBuf::from(#data_path),
                        PathBuf::from(#offsets_path)
                    ).expect("Failed to create variable column")
                });
                column_index += 1;
            }
        }

        let tombstones_path = format!("{}/tombstones.bin", model_snake);
        quote! {
            id_to_row: HashMap::new(),
            row_count: 0,
            #(#inits,)*
            tombstones: forgedb_storage::Tombstones::new(
                PathBuf::from(#tombstones_path)
            ).expect("Failed to create tombstones"),
        }
    }

    /// Emit a `size_of`-based expression for the column's value size so it matches
    /// the actual Rust type layout (C3).  For complex/struct types we defer to
    /// `std::mem::size_of::<T>()` evaluated at compile time in the generated code.
    fn column_value_size_expr(field_type: &forgedb_parser::FieldType) -> TokenStream {
        match field_type {
            forgedb_parser::FieldType::StructType(name) => {
                let ident = format_ident!("{}", name);
                quote! { std::mem::size_of::<#ident>() }
            }
            forgedb_parser::FieldType::OptionalStructType(name) => {
                let ident = format_ident!("{}", name);
                quote! { std::mem::size_of::<Option<#ident>>() }
            }
            forgedb_parser::FieldType::Nullable(inner) => {
                let inner_tokens = Self::map_field_type_ident(inner);
                quote! { std::mem::size_of::<Option<#inner_tokens>>() }
            }
            _ => {
                // For all other fixed-size types the constant is authoritative
                let size = match field_type {
                    forgedb_parser::FieldType::U32 | forgedb_parser::FieldType::I32 => 4usize,
                    forgedb_parser::FieldType::U64 | forgedb_parser::FieldType::I64 => 8,
                    forgedb_parser::FieldType::F64 => 8,
                    forgedb_parser::FieldType::Bool => 1,
                    forgedb_parser::FieldType::Uuid => 16,
                    forgedb_parser::FieldType::Timestamp => 8,
                    forgedb_parser::FieldType::Char(n) => *n,
                    forgedb_parser::FieldType::FixedArray(inner, count) => {
                        // Fall back to map_field_type_ident for array sizing
                        let inner_tokens = Self::map_field_type_ident(inner);
                        return quote! { std::mem::size_of::<[#inner_tokens; #count]>() };
                    }
                    _ => 8, // Default
                };
                quote! { #size }
            }
        }
    }

    /// Generate insert method logic
    fn generate_insert_logic(model: &forgedb_parser::Model) -> TokenStream {
        let mut append_statements = Vec::new();

        // Find the ID field
        let id_field = model.fields.iter().find(|f| f.name == "id" || f.auto_generate);
        let id_field_name = if let Some(f) = id_field {
            format_ident!("{}", f.name)
        } else {
            format_ident!("id")
        };

        for field in &model.fields {
            let field_name = format_ident!("{}", field.name);
            let field_col_name = format_ident!("{}_col", field.name);

            if Self::is_string_type(&field.field_type) {
                append_statements.push(quote! {
                    self.#field_col_name.append_string(&record.#field_name)
                        .expect("Failed to append string");
                });
            } else if Self::is_fixed_size_type(&field.field_type) {
                // Check if this is a complex type that needs byte conversion
                let needs_byte_conversion = matches!(
                    &field.field_type,
                    forgedb_parser::FieldType::Char(_)
                        | forgedb_parser::FieldType::FixedArray(_, _)
                        | forgedb_parser::FieldType::StructType(_)
                        | forgedb_parser::FieldType::OptionalStructType(_)
                        | forgedb_parser::FieldType::Nullable(_)
                );

                if needs_byte_conversion {
                    // C3: use size_of_val so the byte count matches the column size
                    append_statements.push(quote! {
                        {
                            let bytes = unsafe {
                                std::slice::from_raw_parts(
                                    &record.#field_name as *const _ as *const u8,
                                    std::mem::size_of_val(&record.#field_name)
                                )
                            };
                            self.#field_col_name.append_bytes(bytes)
                                .expect("Failed to append to column");
                        }
                    });
                } else {
                    // For primitives, use typed method
                    let append_method = Self::get_append_method(&field.field_type);

                    // Special handling for UUID
                    if matches!(&field.field_type, forgedb_parser::FieldType::Uuid) {
                        append_statements.push(quote! {
                            self.#field_col_name.#append_method(*record.#field_name.as_bytes())
                                .expect("Failed to append to column");
                        });
                    } else {
                        append_statements.push(quote! {
                            self.#field_col_name.#append_method(record.#field_name)
                                .expect("Failed to append to column");
                        });
                    }
                }
            }
        }

        quote! {
            let row_index = self.row_count;
            let id = record.#id_field_name;

            // Append all fields to their respective columns
            #(#append_statements)*

            // Mark as not deleted
            self.tombstones.append(false).expect("Failed to append tombstone");

            // Store ID mapping
            self.id_to_row.insert(id, row_index);
            self.row_count += 1;

            id
        }
    }

    /// Generate get method logic
    fn generate_get_logic(model: &forgedb_parser::Model) -> TokenStream {
        let mut read_statements = Vec::new();
        let mut field_values = Vec::new();

        for field in &model.fields {
            let field_name = format_ident!("{}", field.name);
            let field_col_name = format_ident!("{}_col", field.name);
            let field_value_name = format_ident!("{}_value", field.name);

            if Self::is_string_type(&field.field_type) {
                read_statements.push(quote! {
                    let #field_value_name = self.#field_col_name.read_string(row_index)
                        .expect("Failed to read string");
                });
                // C1: only push to field_values inside the branch that emits a binding
                field_values.push(quote! { #field_name: #field_value_name });
            } else if Self::is_fixed_size_type(&field.field_type) {
                // Check if this is a complex type that needs byte conversion
                let needs_byte_conversion = matches!(
                    &field.field_type,
                    forgedb_parser::FieldType::Char(_)
                        | forgedb_parser::FieldType::FixedArray(_, _)
                        | forgedb_parser::FieldType::StructType(_)
                        | forgedb_parser::FieldType::OptionalStructType(_)
                        | forgedb_parser::FieldType::Nullable(_)
                );

                if needs_byte_conversion {
                    // C3: use the actual stored type (Option<T> for nullable/optional) for the
                    // type annotation and use ptr::read_unaligned to avoid UB on unaligned reads
                    let stored_type = Self::stored_type_tokens(&field.field_type, field.is_nullable());
                    read_statements.push(quote! {
                        let #field_value_name: #stored_type = {
                            let bytes = self.#field_col_name.read_bytes(row_index)
                                .expect("Failed to read from column");
                            unsafe {
                                std::ptr::read_unaligned(bytes.as_ptr() as *const #stored_type)
                            }
                        };
                    });
                } else {
                    // For primitives, use typed method
                    let read_method = Self::get_read_method(&field.field_type);

                    // Special handling for UUID
                    if matches!(&field.field_type, forgedb_parser::FieldType::Uuid) {
                        read_statements.push(quote! {
                            let #field_value_name = {
                                let bytes = self.#field_col_name.#read_method(row_index)
                                    .expect("Failed to read from column");
                                Uuid::from_bytes(bytes)
                            };
                        });
                    } else {
                        read_statements.push(quote! {
                            let #field_value_name = self.#field_col_name.#read_method(row_index)
                                .expect("Failed to read from column");
                        });
                    }
                }
                // C1: only push inside this branch
                field_values.push(quote! { #field_name: #field_value_name });
            } else {
                // C1: Relation/component fields have no storage column.
                // Provide a type-appropriate default value so the struct literal compiles.
                let default_val = Self::default_for_unstored_field(&field.field_type);
                field_values.push(quote! { #field_name: #default_val });
            }
        }

        let model_name = format_ident!("{}", model.name);

        quote! {
            // Look up row index
            let row_index = *self.id_to_row.get(&id)?;

            // Check if deleted
            if self.tombstones.is_deleted(row_index).unwrap_or(true) {
                return None;
            }

            // Read all fields
            #(#read_statements)*

            // Construct model
            Some(#model_name {
                #(#field_values),*
            })
        }
    }

    /// Return the Rust type tokens used for raw byte storage read/write (C3).
    /// For `OptionalStructType` and `Nullable` the stored type is `Option<Inner>`.
    fn stored_type_tokens(
        field_type: &forgedb_parser::FieldType,
        is_nullable: bool,
    ) -> TokenStream {
        let base = Self::map_field_type_ident(field_type);
        if is_nullable {
            quote! { Option<#base> }
        } else {
            base
        }
    }

    /// Generate a sensible default value for fields that have no storage column
    /// (relations, components).  Returned tokens are placed directly in the
    /// struct literal, so they must be valid expressions of the correct type.
    fn default_for_unstored_field(field_type: &forgedb_parser::FieldType) -> TokenStream {
        match field_type {
            forgedb_parser::FieldType::Relation(rel) => match rel {
                // FK reference fields map to Uuid in the generated struct
                forgedb_parser::RelationType::RequiredReference(_) => {
                    quote! { Default::default() }
                }
                // Optional FK maps to Option<Uuid>
                forgedb_parser::RelationType::OptionalReference(_) => quote! { None },
                // Virtual relation fields (no storage at all) map to ()
                _ => quote! { () },
            },
            // Component fields map to String
            forgedb_parser::FieldType::Component(_) => quote! { Default::default() },
            _ => quote! { Default::default() },
        }
    }

    /// Check if a field type is fixed-size
    fn is_fixed_size_type(field_type: &forgedb_parser::FieldType) -> bool {
        match field_type {
            forgedb_parser::FieldType::U32
            | forgedb_parser::FieldType::U64
            | forgedb_parser::FieldType::I32
            | forgedb_parser::FieldType::I64
            | forgedb_parser::FieldType::F64
            | forgedb_parser::FieldType::Bool
            | forgedb_parser::FieldType::Uuid
            | forgedb_parser::FieldType::Timestamp
            | forgedb_parser::FieldType::Char(_)
            | forgedb_parser::FieldType::FixedArray(_, _)
            | forgedb_parser::FieldType::StructType(_)
            | forgedb_parser::FieldType::OptionalStructType(_) => true,
            forgedb_parser::FieldType::Nullable(inner) => Self::is_fixed_size_type(inner),
            _ => false,
        }
    }

    /// Check if a field type is a string (variable-length)
    fn is_string_type(field_type: &forgedb_parser::FieldType) -> bool {
        match field_type {
            forgedb_parser::FieldType::String => true,
            forgedb_parser::FieldType::Nullable(inner) => Self::is_string_type(inner),
            _ => false,
        }
    }

    /// Get the type name for storage paths
    fn type_name(field_type: &forgedb_parser::FieldType) -> &'static str {
        match field_type {
            forgedb_parser::FieldType::U32 => "u32",
            forgedb_parser::FieldType::U64 => "u64",
            forgedb_parser::FieldType::I32 => "i32",
            forgedb_parser::FieldType::I64 => "i64",
            forgedb_parser::FieldType::F64 => "f64",
            forgedb_parser::FieldType::Bool => "bool",
            forgedb_parser::FieldType::Uuid => "uuid",
            forgedb_parser::FieldType::Timestamp => "timestamp",
            forgedb_parser::FieldType::Char(_) => "bytes",
            forgedb_parser::FieldType::FixedArray(_, _) => "bytes",
            forgedb_parser::FieldType::StructType(_) => "bytes",
            forgedb_parser::FieldType::OptionalStructType(_) => "bytes",
            forgedb_parser::FieldType::Nullable(inner) => Self::type_name(inner),
            _ => "unknown",
        }
    }

    /// Get the append method name for a field type
    fn get_append_method(field_type: &forgedb_parser::FieldType) -> proc_macro2::Ident {
        format_ident!("append_{}", Self::type_name(field_type))
    }

    /// Get the read method name for a field type
    fn get_read_method(field_type: &forgedb_parser::FieldType) -> proc_macro2::Ident {
        format_ident!("read_{}", Self::type_name(field_type))
    }

    /// Generate the main database struct
    fn generate_database(schema: &Schema) -> Result<TokenStream> {
        // Generate field definitions for each model storage
        let db_fields: Vec<_> = schema
            .models
            .iter()
            .map(|model| {
                let field_name = format_ident!("{}", Self::to_snake_case(&model.name));
                let storage_type = format_ident!("{}Storage", model.name);
                quote! { pub #field_name: #storage_type }
            })
            .collect();

        // Generate field initializers for the new() method
        let db_inits: Vec<_> = schema
            .models
            .iter()
            .map(|model| {
                let field_name = format_ident!("{}", Self::to_snake_case(&model.name));
                let storage_type = format_ident!("{}Storage", model.name);
                quote! { #field_name: #storage_type::new() }
            })
            .collect();

        let tokens = quote! {
            /// Main database struct
            pub struct Database {
                #(#db_fields),*
            }

            impl Database {
                pub fn new() -> Self {
                    Self {
                        #(#db_inits),*
                    }
                }
            }
        };

        Ok(tokens)
    }

    /// Map ForgeDB field type to Rust type identifier for use with quote!
    ///
    /// Note: for `OptionalStructType` and `Nullable`, this returns the *inner* type
    /// token.  The `Option<>` wrapper is applied by callers that check `field.is_nullable()`.
    fn map_field_type_ident(field_type: &forgedb_parser::FieldType) -> TokenStream {
        match field_type {
            forgedb_parser::FieldType::U32 => quote! { u32 },
            forgedb_parser::FieldType::U64 => quote! { u64 },
            forgedb_parser::FieldType::I32 => quote! { i32 },
            forgedb_parser::FieldType::I64 => quote! { i64 },
            forgedb_parser::FieldType::F64 => quote! { f64 },
            forgedb_parser::FieldType::Bool => quote! { bool },
            forgedb_parser::FieldType::String => quote! { String },
            forgedb_parser::FieldType::Uuid => quote! { Uuid },
            forgedb_parser::FieldType::Timestamp => quote! { Timestamp },
            forgedb_parser::FieldType::StructType(name) => {
                let ident = format_ident!("{}", name);
                quote! { #ident }
            }
            forgedb_parser::FieldType::OptionalStructType(name) => {
                let ident = format_ident!("{}", name);
                quote! { #ident }
            }
            forgedb_parser::FieldType::Nullable(inner) => {
                // Return the inner type; is_nullable() causes the Option<> wrapper to be added
                Self::map_field_type_ident(inner)
            }
            forgedb_parser::FieldType::Char(size) => {
                quote! { [u8; #size] }
            }
            forgedb_parser::FieldType::FixedArray(inner, count) => {
                let inner_type = Self::map_field_type_ident(inner);
                quote! { [#inner_type; #count] }
            }
            forgedb_parser::FieldType::Relation(rel) => {
                match rel {
                    forgedb_parser::RelationType::RequiredReference(_) => quote! { Uuid },
                    forgedb_parser::RelationType::OptionalReference(_) => quote! { Uuid },
                    _ => quote! { () }, // Virtual fields
                }
            }
            _ => quote! { String }, // Default fallback
        }
    }

    /// Convert PascalCase to snake_case
    fn to_snake_case(s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        }
        result
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use forgedb_parser::ast::IndexType;
    use forgedb_parser::{Field, FieldType, Model, Schema};

    #[test]
    fn test_rust_generation_with_quote() {
        // Create a simple schema
        let schema = Schema {
            models: vec![Model {
                name: "User".to_string(),
                fields: vec![
                    Field {
                        name: "id".to_string(),
                        field_type: FieldType::Uuid,
                        auto_generate: true,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    },
                    Field {
                        name: "email".to_string(),
                        field_type: FieldType::String,
                        auto_generate: false,
                        unique: true,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    },
                    Field {
                        name: "age".to_string(),
                        field_type: FieldType::OptionalStructType("Age".to_string()),
                        auto_generate: false,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    },
                ],
                composite_indexes: vec![],
                soft_delete: false,
            }],
            structs: vec![],
        };

        let result = RustGenerator::generate(&schema).unwrap();
        let code = result.code;

        // Verify the generated code contains expected elements (formatted by prettyplease)
        assert!(code.contains("pub struct User"));
        assert!(code.contains("pub id: Uuid"));
        assert!(code.contains("pub email: String"));
        assert!(code.contains("pub age: Option<Age>"));
        assert!(code.contains("pub struct UserStorage"));
        assert!(code.contains("pub struct Database"));
        assert!(code.contains("pub user: UserStorage"));
        assert!(code.contains("impl UserStorage"));
        assert!(code.contains("pub fn new"));
        assert!(code.contains("pub fn insert"));
        assert!(code.contains("pub fn get"));

        // Verify it compiles as valid Rust (basic syntax check)
        assert!(code.contains("use std::collections::HashMap"));
        assert!(code.contains("use forgedb_types::{Uuid, Timestamp, Value}"));
    }

    #[test]
    fn test_multiple_models() {
        let schema = Schema {
            models: vec![
                Model {
                    name: "User".to_string(),
                    fields: vec![Field {
                        name: "id".to_string(),
                        field_type: FieldType::Uuid,
                        auto_generate: true,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    }],
                    composite_indexes: vec![],
                    soft_delete: false,
                },
                Model {
                    name: "Post".to_string(),
                    fields: vec![Field {
                        name: "id".to_string(),
                        field_type: FieldType::Uuid,
                        auto_generate: true,
                        unique: false,
                        indexed: false,
                        constraints: vec![],
                        index_type: IndexType::Hash,
                        is_computed: false,
                        fulltext_indexed: false,
                        is_materialized: false,
                    }],
                    composite_indexes: vec![],
                    soft_delete: false,
                },
            ],
            structs: vec![],
        };

        let result = RustGenerator::generate(&schema).unwrap();
        let code = result.code;

        // Verify formatted output
        assert!(code.contains("pub struct User"));
        assert!(code.contains("pub struct Post"));
        assert!(code.contains("pub struct UserStorage"));
        assert!(code.contains("pub struct PostStorage"));
        assert!(code.contains("pub user: UserStorage"));
        assert!(code.contains("pub post: PostStorage"));
    }
}
