//! Rust database code generator
//!
//! Generates optimized Rust code with columnar storage for ForgeDB schemas.

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;

/// Rust code generator
pub struct RustGenerator;

impl RustGenerator {
    /// Generate Rust database implementation from schema
    ///
    /// # Arguments
    ///
    /// * `schema` - Parsed schema AST
    ///
    /// # Returns
    ///
    /// Generated Rust code as a string
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let code = Self::generate_code(schema)?;

        Ok(GeneratedCode {
            code,
            description: format!(
                "Rust database implementation ({} models)",
                schema.models.len()
            ),
        })
    }

    /// Generate the Rust code as a string
    fn generate_code(schema: &Schema) -> Result<String> {
        let mut code = String::new();

        // File header
        code.push_str("//! Generated by ForgeDB\n");
        code.push_str("//! DO NOT EDIT - This file is auto-generated\n\n");

        // Imports
        code.push_str("#![allow(dead_code, unused_imports)]\n\n");
        code.push_str("use std::collections::HashMap;\n");
        code.push_str("use std::path::Path;\n");
        code.push_str("use forgedb_storage::ColumnarStorage;\n");
        code.push_str("use forgedb_types::{Uuid, Timestamp, Value};\n\n");

        // Generate models
        for model in &schema.models {
            code.push_str(&Self::generate_model(model)?);
            code.push_str("\n\n");
        }

        // Generate database struct
        code.push_str(&Self::generate_database(schema)?);

        Ok(code)
    }

    /// Generate a single model struct
    fn generate_model(model: &forgedb_parser::Model) -> Result<String> {
        let mut code = String::new();

        code.push_str(&format!("/// {} model\n", model.name));
        code.push_str("#[derive(Debug, Clone)]\n");
        code.push_str(&format!("pub struct {} {{\n", model.name));

        for field in &model.fields {
            let field_type = Self::map_field_type(&field.field_type);
            let nullable = if field.is_nullable() { "Option<" } else { "" };
            let nullable_end = if field.is_nullable() { ">" } else { "" };

            code.push_str(&format!(
                "    pub {}: {}{}{},\n",
                field.name, nullable, field_type, nullable_end
            ));
        }

        code.push_str("}\n");

        // Generate storage struct
        code.push_str("\n");
        code.push_str(&format!("/// Storage for {} model\n", model.name));
        code.push_str(&format!("pub struct {}Storage {{\n", model.name));
        code.push_str("    // TODO: Implement columnar storage fields\n");
        code.push_str("}\n");

        // Generate implementation
        code.push_str("\n");
        code.push_str(&format!("impl {}Storage {{\n", model.name));
        code.push_str("    pub fn new() -> Self {\n");
        code.push_str("        Self {\n");
        code.push_str("            // TODO: Initialize storage\n");
        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("\n");
        code.push_str(&format!("    pub fn insert(&mut self, record: {}) -> Uuid {{\n", model.name));
        code.push_str("        // TODO: Implement insert\n");
        code.push_str("        Uuid::new_v4()\n");
        code.push_str("    }\n");
        code.push_str("\n");
        code.push_str(&format!("    pub fn get(&self, id: Uuid) -> Option<{}> {{\n", model.name));
        code.push_str("        // TODO: Implement get\n");
        code.push_str("        None\n");
        code.push_str("    }\n");
        code.push_str("}\n");

        Ok(code)
    }

    /// Generate the main database struct
    fn generate_database(schema: &Schema) -> Result<String> {
        let mut code = String::new();

        code.push_str("/// Main database struct\n");
        code.push_str("pub struct Database {\n");

        for model in &schema.models {
            code.push_str(&format!(
                "    pub {}: {}Storage,\n",
                Self::to_snake_case(&model.name),
                model.name
            ));
        }

        code.push_str("}\n\n");

        code.push_str("impl Database {\n");
        code.push_str("    pub fn new() -> Self {\n");
        code.push_str("        Self {\n");

        for model in &schema.models {
            code.push_str(&format!(
                "            {}: {}Storage::new(),\n",
                Self::to_snake_case(&model.name),
                model.name
            ));
        }

        code.push_str("        }\n");
        code.push_str("    }\n");
        code.push_str("}\n");

        Ok(code)
    }

    /// Map ForgeDB field type to Rust type
    fn map_field_type(field_type: &forgedb_parser::FieldType) -> &'static str {
        match field_type {
            forgedb_parser::FieldType::I32 => "i32",
            forgedb_parser::FieldType::I64 => "i64",
            forgedb_parser::FieldType::F64 => "f64",
            forgedb_parser::FieldType::Bool => "bool",
            forgedb_parser::FieldType::String => "String",
            forgedb_parser::FieldType::Uuid => "Uuid",
            forgedb_parser::FieldType::Timestamp => "Timestamp",
            _ => "String", // Default fallback
        }
    }

    /// Convert PascalCase to snake_case
    fn to_snake_case(s: &str) -> String {
        let mut result = String::new();
        for (i, c) in s.chars().enumerate() {
            if c.is_uppercase() && i > 0 {
                result.push('_');
            }
            result.push(c.to_ascii_lowercase());
        }
        result
    }
}
