pub struct ServerPackage;

impl ServerPackage {
    const BODY: &'static str = include_str!("templates/server_main_body.rs.txt");

    const PREAMBLE: &'static str = "use forgedb_core as database;\n\
                                    use database::*;\n\
                                    \n\
                                    mod api;\n";

    pub fn main_rs() -> String {
        format!("{}{}", Self::PREAMBLE, Self::BODY)
    }

    pub fn cargo_toml(crate_name: &str, core_package: &str) -> String {
        format!(
            r#"# Generated by ForgeDB. Do not edit — rewritten in full on every generate.
[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "{crate_name}"
path = "src/main.rs"

[dependencies]
# The one generated database for this app. Renamed so no generated source
# carries this app's package name.
forgedb_core = {{ package = "{core_package}", path = "../core" }}

# Substrate the API layer links directly. NOT the storage/wal/txn set — those
# reach this crate through `core`, which is what makes their types UNIFY rather
# than merely happen to resolve to the same version.
forgedb-auth = {{ version = "0.2", features = ["jwks-http"] }}
forgedb-query-params = "0.1"
forgedb-changefeed = "0.2"

serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

# NOT substrate, and therefore pinned here rather than routed through `core`:
# `api.rs` names `rust_decimal::Decimal` ABSOLUTELY when any model carries a
# `decimal` field, to parse a REST filter value out of the query string. Only a
# direct dependency puts a crate in this crate's extern prelude — `core`
# re-exporting it would answer `forgedb_core::rust_decimal`, not the bare path
# the generated code writes.
#
# Pinned unconditionally rather than per-schema, matching how `utoipa` and
# `serde_json` are handled: the manifest is not schema-shaped, and a
# conditional pin would make the failure depend on whether the app happens to
# declare a `decimal` — which is exactly how this shipped broken. It was
# invisible to every snapshot (they compare strings) and to every in-tree
# build, and surfaced only on a real `forgedb build` of a schema with a
# `decimal` column: `error[E0433]: cannot find module or crate rust_decimal`.
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}

utoipa = {{ version = "5", features = ["uuid"] }}
utoipa-axum = "0.2"
axum = {{ version = "0.8", features = ["ws"] }}
tokio = {{ version = "1", features = ["full"] }}
tower-http = {{ version = "0.6", features = ["trace", "cors"] }}
tracing = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter", "json"] }}
"#
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_generated_main_links_core() {
        let main = ServerPackage::main_rs();
        assert!(main.ends_with(ServerPackage::BODY));
        assert!(
            main.starts_with("use forgedb_core as database;"),
            "{}",
            &main[..200]
        );
        assert!(
            !main.contains("#[path"),
            "the generated main must not use #[path] modules"
        );

        let forbidden = format!("..{}", "/generated/");

        for entry in std::fs::read_dir(concat!(env!("CARGO_MANIFEST_DIR"), "/src")).unwrap() {
            let path = entry.unwrap().path();
            if path.extension().is_none_or(|e| e != "rs") {
                continue;
            }
            let body = std::fs::read_to_string(&path).unwrap();
            let code: String = body
                .lines()
                .filter(|l| !l.trim_start().starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n");
            assert!(
                !code.contains(&forbidden),
                "{} still emits a #[path] into the output directory — the in-tree \
                 server layout is deleted, not merely unused",
                path.display()
            );
        }
    }

    #[test]
    fn the_body_reaches_the_database_through_the_alias() {
        assert!(
            ServerPackage::BODY.contains("database::Database::open_at"),
            "the body no longer opens the database the way the preamble aliases"
        );
    }

    #[test]
    fn the_body_carries_the_c4_startup_guard() {
        assert!(ServerPackage::BODY.contains("refusing to open a database inside the ForgeDB build cache"));
        assert!(ServerPackage::BODY.contains("fn forgedb_home_dir()"));
        assert!(ServerPackage::BODY.contains("fn closest_real_ancestor("));
    }

    #[test]
    fn no_generated_byte_carries_the_app_hash() {
        let cache = ServerPackage::main_rs();
        let manifest = ServerPackage::cargo_toml("blog-3f2a1b-server", "blog-3f2a1b-core");
        assert!(manifest.contains("blog-3f2a1b-core"));
        assert!(!cache.contains("3f2a1b"), "the app hash leaked into main.rs");
    }

    #[test]
    fn the_body_uses_no_edition_2024_only_syntax() {
        for (i, line) in ServerPackage::BODY.lines().enumerate() {
            let t = line.trim_start();
            if t.starts_with("//") {
                continue;
            }
            let is_let_head = t.starts_with("if let ") || t.starts_with("while let ");
            assert!(
                !(is_let_head && t.trim_end().ends_with("&&")),
                "line {} opens a let-chain, which is edition 2024 only:\n  {line}",
                i + 1
            );
        }
    }

    #[test]
    fn the_manifest_parses_as_toml() {
        let manifest = ServerPackage::cargo_toml("app-server", "app-core");
        toml::from_str::<toml::Value>(&manifest)
            .unwrap_or_else(|e| panic!("server manifest is not valid TOML: {e}\n{manifest}"));
        assert!(!manifest.contains("[profile"), "{manifest}");
    }
}
