//! The `server/` cache package: the generated REST API as a binary crate
//! (#335 §1, epic #332).
//!
//! # One `main.rs`, one preamble
//!
//! The body of the generated server — env-driven config, the tenant data dir,
//! the JWT authenticator, CORS, the router, graceful shutdown — is **one
//! definition**, in `templates/server_main_body.rs.txt`, and there is now
//! exactly one preamble in front of it: `server/` links `core` as an ordinary
//! cargo dependency.
//!
//! There used to be a second, `ServerLayout::InTree`, which reached the
//! generated files through `#[path]` modules for `forgedb init`'s cargo
//! scaffold.  #335 §15 deleted that scaffold and #338 decided in-tree carries
//! **no server at all** — an in-tree placement emits `core` and nothing else —
//! so the variant had no caller outside its own test.  A layout parameter with
//! one variant is an invitation to add a second emitter of one artifact, which
//! is the drift #335 exists to end.
//!
//! # Why `api.rs` needs no generator change
//!
//! It opens with `use super::*;`, re-globbing whatever the crate root imported —
//! the same mechanism the `init` scaffold already relies on.  A `main.rs` that
//! says `use forgedb_core::*; mod api;` compiles it verbatim.

/// The `server/` package.
pub struct ServerPackage;

impl ServerPackage {
    /// The shared body — everything below the module preamble.
    const BODY: &'static str = include_str!("templates/server_main_body.rs.txt");

    /// The module preamble: `server/` links `core` as a cargo dependency.
    ///
    /// `use forgedb_core as database;` keeps the body's one
    /// `database::Database::open_at` reference resolving unchanged — which is
    /// what let the body be shared when there were two layouts, and what keeps
    /// the body free of any knowledge of how it is reached now there is one.
    ///
    /// The per-app package name never appears here: the MANIFEST renames the
    /// dependency to `forgedb_core`, so no generated `.rs` byte carries the
    /// app's derived name.
    const PREAMBLE: &'static str = "use forgedb_core as database;\n\
                                    use database::*;\n\
                                    \n\
                                    mod api;\n";

    /// Render `main.rs`.
    ///
    /// **It takes no layout argument** (#338). The `#[path]`-module layout had
    /// no caller once `forgedb init` stopped scaffolding a cargo package
    /// (#335 §15), and in-tree placement emits `core` alone — no `api.rs`, no
    /// `main.rs`, no `[[bin]]`.
    pub fn main_rs() -> String {
        format!("{}{}", Self::PREAMBLE, Self::BODY)
    }

    /// Render `server/Cargo.toml`.
    ///
    /// `core_package` is the app's `core` package name; the dependency is
    /// **renamed** to `forgedb_core` so the generated source never carries the
    /// app hash.
    ///
    /// No `[profile.*]` table: a profile in a workspace member is silently
    /// ignored, and the release floor is applied by the build driver.
    pub fn cargo_toml(crate_name: &str, core_package: &str) -> String {
        format!(
            r#"# Generated by ForgeDB. Do not edit — rewritten in full on every generate.
[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "{crate_name}"
path = "src/main.rs"

[dependencies]
# The one generated database for this app. Renamed so no generated source
# carries this app's package name.
forgedb_core = {{ package = "{core_package}", path = "../core" }}

# Substrate the API layer links directly. NOT the storage/wal/txn set — those
# reach this crate through `core`, which is what makes their types UNIFY rather
# than merely happen to resolve to the same version.
forgedb-auth = {{ version = "0.2", features = ["jwks-http"] }}
forgedb-query-params = "0.1"
forgedb-changefeed = "0.2"

serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

# NOT substrate, and therefore pinned here rather than routed through `core`:
# `api.rs` names `rust_decimal::Decimal` ABSOLUTELY when any model carries a
# `decimal` field, to parse a REST filter value out of the query string. Only a
# direct dependency puts a crate in this crate's extern prelude — `core`
# re-exporting it would answer `forgedb_core::rust_decimal`, not the bare path
# the generated code writes.
#
# Pinned unconditionally rather than per-schema, matching how `utoipa` and
# `serde_json` are handled: the manifest is not schema-shaped, and a
# conditional pin would make the failure depend on whether the app happens to
# declare a `decimal` — which is exactly how this shipped broken. It was
# invisible to every snapshot (they compare strings) and to every in-tree
# build, and surfaced only on a real `forgedb build` of a schema with a
# `decimal` column: `error[E0433]: cannot find module or crate rust_decimal`.
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}

utoipa = {{ version = "5", features = ["uuid"] }}
utoipa-axum = "0.2"
axum = {{ version = "0.8", features = ["ws"] }}
tokio = {{ version = "1", features = ["full"] }}
tower-http = {{ version = "0.6", features = ["trace", "cors"] }}
tracing = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter", "json"] }}
"#
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// **#338 scenario 15.** `main_rs()` takes no layout argument, its preamble
    /// links `forgedb_core`, and no `#[path = "../generated/…"]` string survives
    /// anywhere in this crate's source.
    ///
    /// The last clause is asserted over the crate's own files with comments
    /// stripped, because this file EXPLAINS the deleted layout at length and a
    /// naive `contains` would be satisfied by the explanation. A guard a comment
    /// can satisfy is not a guard, and a well-commented deletion makes that
    /// worse rather than better: the prose restates the removed construct in the
    /// exact words the assertion greps for.
    #[test]
    fn the_generated_main_links_core() {
        let main = ServerPackage::main_rs();
        assert!(main.ends_with(ServerPackage::BODY));
        assert!(
            main.starts_with("use forgedb_core as database;"),
            "{}",
            &main[..200]
        );
        assert!(
            !main.contains("#[path"),
            "the generated main must not use #[path] modules"
        );

        // Assembled from two halves so THIS assertion's own source does not
        // contain the string it forbids. The reflex fix for a self-matching
        // scanner is to skip its own file, and that would blind it to exactly
        // the file the deleted layout lived in.
        //
        // `ServerLayout` itself needs no text scan: it is gone from the crate,
        // so naming it is a compile error. Only a string LITERAL can come back
        // invisibly, and that is what this looks for.
        let forbidden = format!("..{}", "/generated/");

        for entry in std::fs::read_dir(concat!(env!("CARGO_MANIFEST_DIR"), "/src")).unwrap() {
            let path = entry.unwrap().path();
            if path.extension().is_none_or(|e| e != "rs") {
                continue;
            }
            let body = std::fs::read_to_string(&path).unwrap();
            let code: String = body
                .lines()
                .filter(|l| !l.trim_start().starts_with("//"))
                .collect::<Vec<_>>()
                .join("\n");
            assert!(
                !code.contains(&forbidden),
                "{} still emits a #[path] into the output directory — the in-tree \
                 server layout is deleted, not merely unused",
                path.display()
            );
        }
    }

    /// The body's one `database::` reference must keep resolving under the
    /// cache preamble's rename — that is the whole reason the body can be shared.
    #[test]
    fn the_body_reaches_the_database_through_the_alias() {
        assert!(
            ServerPackage::BODY.contains("database::Database::open_at"),
            "the body no longer opens the database the way the preamble aliases"
        );
    }

    /// C4 must be enforced in generated code, not in prose.
    #[test]
    fn the_body_carries_the_c4_startup_guard() {
        assert!(ServerPackage::BODY.contains("refusing to open a database inside the ForgeDB build cache"));
        assert!(ServerPackage::BODY.contains("fn forgedb_home_dir()"));
        assert!(ServerPackage::BODY.contains("fn closest_real_ancestor("));
    }

    #[test]
    fn no_generated_byte_carries_the_app_hash() {
        let cache = ServerPackage::main_rs();
        // The manifest carries the hashed package name; the source never does.
        let manifest = ServerPackage::cargo_toml("blog-3f2a1b-server", "blog-3f2a1b-core");
        assert!(manifest.contains("blog-3f2a1b-core"));
        assert!(!cache.contains("3f2a1b"), "the app hash leaked into main.rs");
    }

    /// The generated server must compile under the CONSUMER's edition, and the
    /// `init` scaffold is edition 2021.
    ///
    /// This shipped broken once: a `forgedb_home_dir` helper written with a
    /// let-chain (`if let Some(x) = ... && cond`) compiled fine in this
    /// workspace — which is edition 2024 — and failed with `let chains are only
    /// allowed in Rust 2024 or later` the moment a real scaffold was compiled.
    /// Nothing in-tree could have caught it, because in-tree is the wrong
    /// edition to notice.
    ///
    /// Anchored on the CONSTRUCT rather than on the helper's name, so it keeps
    /// guarding when the helper is renamed or another one is added.
    #[test]
    fn the_body_uses_no_edition_2024_only_syntax() {
        for (i, line) in ServerPackage::BODY.lines().enumerate() {
            let t = line.trim_start();
            if t.starts_with("//") {
                continue;
            }
            let is_let_head = t.starts_with("if let ") || t.starts_with("while let ");
            assert!(
                !(is_let_head && t.trim_end().ends_with("&&")),
                "line {} opens a let-chain, which is edition 2024 only:\n  {line}",
                i + 1
            );
        }
    }

    #[test]
    fn the_manifest_parses_as_toml() {
        let manifest = ServerPackage::cargo_toml("app-server", "app-core");
        toml::from_str::<toml::Value>(&manifest)
            .unwrap_or_else(|e| panic!("server manifest is not valid TOML: {e}\n{manifest}"));
        assert!(!manifest.contains("[profile"), "{manifest}");
    }
}
