//! The `server/` cache package: the generated REST API as a binary crate
//! (#335 §1, epic #332).
//!
//! # One `main.rs`, two preambles
//!
//! The body of the generated server — env-driven config, the tenant data dir,
//! the JWT authenticator, CORS, the router, graceful shutdown — is **one
//! definition**, in `templates/server_main_body.rs.txt`.  Only the module
//! preamble differs between the two places it is used:
//!
//! * **in-tree** (`forgedb init`'s scaffold, until #335 step 10 removes it)
//!   reaches the generated files through `#[path]` modules;
//! * **cache** (`server/` here) links `core` as an ordinary dependency.
//!
//! Copying the body for the second case would create exactly the drift this
//! issue exists to end — two emitters of one artifact, agreeing today and
//! diverging on the first edit that touches only one of them.
//!
//! # Why `api.rs` needs no generator change
//!
//! It opens with `use super::*;`, re-globbing whatever the crate root imported —
//! the same mechanism the `init` scaffold already relies on.  A `main.rs` that
//! says `use forgedb_core::*; mod api;` compiles it verbatim.

/// Where the generated server is being emitted, which decides only how it
/// reaches `database` and `api`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ServerLayout {
    /// `forgedb init`'s scaffold: `#[path]` modules pointing at the output dir.
    InTree,
    /// The cache `server/` package: `core` is a cargo dependency, `api` a sibling
    /// module in `src/`.
    Cache,
}

impl ServerLayout {
    fn preamble(self) -> &'static str {
        match self {
            ServerLayout::InTree => {
                "#[path = \"../generated/database.rs\"]\n\
                 mod database;\n\
                 use database::*;\n\
                 \n\
                 #[path = \"../generated/api.rs\"]\n\
                 mod api;\n"
            }
            // `use forgedb_core as database;` keeps the body's one
            // `database::Database::open_at` reference working unchanged — which
            // is what lets the body be shared rather than parameterised.
            //
            // The per-app package name never appears here: the MANIFEST renames
            // the dependency to `forgedb_core`, so no generated `.rs` byte
            // carries the app hash.
            ServerLayout::Cache => {
                "use forgedb_core as database;\n\
                 use database::*;\n\
                 \n\
                 mod api;\n"
            }
        }
    }
}

/// The `server/` package.
pub struct ServerPackage;

impl ServerPackage {
    /// The shared body — everything below the module preamble.
    const BODY: &'static str = include_str!("templates/server_main_body.rs.txt");

    /// Render `main.rs` for one layout.
    pub fn main_rs(layout: ServerLayout) -> String {
        format!("{}{}", layout.preamble(), Self::BODY)
    }

    /// Render `server/Cargo.toml`.
    ///
    /// `core_package` is the app's `core` package name; the dependency is
    /// **renamed** to `forgedb_core` so the generated source never carries the
    /// app hash.
    ///
    /// No `[profile.*]` table: a profile in a workspace member is silently
    /// ignored, and the release floor is applied by the build driver.
    pub fn cargo_toml(crate_name: &str, core_package: &str) -> String {
        format!(
            r#"# Generated by ForgeDB. Do not edit — rewritten in full on every generate.
[package]
name = "{crate_name}"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "{crate_name}"
path = "src/main.rs"

[dependencies]
# The one generated database for this app. Renamed so no generated source
# carries this app's package name.
forgedb_core = {{ package = "{core_package}", path = "../core" }}

# Substrate the API layer links directly. NOT the storage/wal/txn set — those
# reach this crate through `core`, which is what makes their types UNIFY rather
# than merely happen to resolve to the same version.
forgedb-auth = {{ version = "0.2", features = ["jwks-http"] }}
forgedb-query-params = "0.1"
forgedb-changefeed = "0.2"

serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"

# NOT substrate, and therefore pinned here rather than routed through `core`:
# `api.rs` names `rust_decimal::Decimal` ABSOLUTELY when any model carries a
# `decimal` field, to parse a REST filter value out of the query string. Only a
# direct dependency puts a crate in this crate's extern prelude — `core`
# re-exporting it would answer `forgedb_core::rust_decimal`, not the bare path
# the generated code writes.
#
# Pinned unconditionally rather than per-schema, matching how `utoipa` and
# `serde_json` are handled: the manifest is not schema-shaped, and a
# conditional pin would make the failure depend on whether the app happens to
# declare a `decimal` — which is exactly how this shipped broken. It was
# invisible to every snapshot (they compare strings) and to every in-tree
# build, and surfaced only on a real `forgedb build` of a schema with a
# `decimal` column: `error[E0433]: cannot find module or crate rust_decimal`.
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}

utoipa = {{ version = "5", features = ["uuid"] }}
utoipa-axum = "0.2"
axum = {{ version = "0.8", features = ["ws"] }}
tokio = {{ version = "1", features = ["full"] }}
tower-http = {{ version = "0.6", features = ["trace", "cors"] }}
tracing = "0.1"
tracing-subscriber = {{ version = "0.3", features = ["env-filter", "json"] }}
"#
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn both_layouts_share_one_body() {
        let in_tree = ServerPackage::main_rs(ServerLayout::InTree);
        let cache = ServerPackage::main_rs(ServerLayout::Cache);

        assert!(in_tree.ends_with(ServerPackage::BODY));
        assert!(cache.ends_with(ServerPackage::BODY));
        assert_ne!(in_tree, cache, "the preambles must differ");
    }

    #[test]
    fn the_cache_layout_links_core_rather_than_path_modules() {
        let cache = ServerPackage::main_rs(ServerLayout::Cache);
        assert!(cache.contains("use forgedb_core as database;"), "{}", &cache[..200]);
        assert!(
            !cache.contains("#[path"),
            "the cache layout must not use #[path] modules"
        );
    }

    /// The body's one `database::` reference must keep resolving under the
    /// cache preamble's rename — that is the whole reason the body can be shared.
    #[test]
    fn the_body_reaches_the_database_through_the_alias() {
        assert!(
            ServerPackage::BODY.contains("database::Database::open_at"),
            "the body no longer opens the database the way the preamble aliases"
        );
    }

    /// C4 must be enforced in generated code, not in prose.
    #[test]
    fn the_body_carries_the_c4_startup_guard() {
        assert!(ServerPackage::BODY.contains("refusing to open a database inside the ForgeDB build cache"));
        assert!(ServerPackage::BODY.contains("fn forgedb_home_dir()"));
        assert!(ServerPackage::BODY.contains("fn closest_real_ancestor("));
    }

    #[test]
    fn no_generated_byte_carries_the_app_hash() {
        let cache = ServerPackage::main_rs(ServerLayout::Cache);
        // The manifest carries the hashed package name; the source never does.
        let manifest = ServerPackage::cargo_toml("blog-3f2a1b-server", "blog-3f2a1b-core");
        assert!(manifest.contains("blog-3f2a1b-core"));
        assert!(!cache.contains("3f2a1b"), "the app hash leaked into main.rs");
    }

    /// The generated server must compile under the CONSUMER's edition, and the
    /// `init` scaffold is edition 2021.
    ///
    /// This shipped broken once: a `forgedb_home_dir` helper written with a
    /// let-chain (`if let Some(x) = ... && cond`) compiled fine in this
    /// workspace — which is edition 2024 — and failed with `let chains are only
    /// allowed in Rust 2024 or later` the moment a real scaffold was compiled.
    /// Nothing in-tree could have caught it, because in-tree is the wrong
    /// edition to notice.
    ///
    /// Anchored on the CONSTRUCT rather than on the helper's name, so it keeps
    /// guarding when the helper is renamed or another one is added.
    #[test]
    fn the_body_uses_no_edition_2024_only_syntax() {
        for (i, line) in ServerPackage::BODY.lines().enumerate() {
            let t = line.trim_start();
            if t.starts_with("//") {
                continue;
            }
            let is_let_head = t.starts_with("if let ") || t.starts_with("while let ");
            assert!(
                !(is_let_head && t.trim_end().ends_with("&&")),
                "line {} opens a let-chain, which is edition 2024 only:\n  {line}",
                i + 1
            );
        }
    }

    #[test]
    fn the_manifest_parses_as_toml() {
        let manifest = ServerPackage::cargo_toml("app-server", "app-core");
        toml::from_str::<toml::Value>(&manifest)
            .unwrap_or_else(|e| panic!("server manifest is not valid TOML: {e}\n{manifest}"));
        assert!(!manifest.contains("[profile"), "{manifest}");
    }
}
