//! TypeScript types and SDK generator

use crate::{GeneratedCode, Result};
use forgedb_parser::Schema;

/// TypeScript code generator
pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    /// Generate TypeScript types and SDK from schema
    ///
    /// # Arguments
    ///
    /// * `schema` - Parsed schema AST
    ///
    /// # Returns
    ///
    /// Generated TypeScript code as a string
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let code = Self::generate_code(schema)?;

        Ok(GeneratedCode {
            code,
            description: format!(
                "TypeScript types and SDK ({} models)",
                schema.models.len()
            ),
        })
    }

    /// Generate TypeScript code as a string
    fn generate_code(schema: &Schema) -> Result<String> {
        let mut code = String::new();

        // File header
        code.push_str("/**\n");
        code.push_str(" * Generated by ForgeDB\n");
        code.push_str(" * DO NOT EDIT - This file is auto-generated\n");
        code.push_str(" */\n\n");

        // Generate type definitions
        for model in &schema.models {
            code.push_str(&Self::generate_interface(model)?);
            code.push_str("\n\n");
        }

        // Generate SDK client
        code.push_str(&Self::generate_sdk_client(schema)?);

        Ok(code)
    }

    /// Generate a TypeScript interface for a model
    fn generate_interface(model: &forgedb_parser::Model) -> Result<String> {
        let mut code = String::new();

        code.push_str(&format!("export interface {} {{\n", model.name));

        for field in &model.fields {
            let field_type = Self::map_field_type(&field.field_type);
            let nullable = if field.is_nullable() { " | null" } else { "" };

            code.push_str(&format!(
                "  {}: {}{};\n",
                field.name, field_type, nullable
            ));
        }

        code.push_str("}\n");

        Ok(code)
    }

    /// Generate SDK client
    fn generate_sdk_client(schema: &Schema) -> Result<String> {
        let mut code = String::new();

        code.push_str("export class ForgeDBClient {\n");
        code.push_str("  private baseUrl: string;\n\n");
        code.push_str("  constructor(baseUrl: string = 'http://localhost:3000') {\n");
        code.push_str("    this.baseUrl = baseUrl;\n");
        code.push_str("  }\n\n");

        for model in &schema.models {
            let model_lower = model.name.to_lowercase();

            code.push_str(&format!(
                "  async get{}(id: string): Promise<{} | null> {{\n",
                model.name, model.name
            ));
            code.push_str(&format!(
                "    const response = await fetch(`${{this.baseUrl}}/api/{}/{{}}`id);\n",
                model_lower
            ));
            code.push_str("    if (!response.ok) return null;\n");
            code.push_str("    const data = await response.json();\n");
            code.push_str("    return data.data;\n");
            code.push_str("  }\n\n");

            code.push_str(&format!(
                "  async list{}(): Promise<{}[]> {{\n",
                model.name, model.name
            ));
            code.push_str(&format!(
                "    const response = await fetch(`${{this.baseUrl}}/api/{}`);\n",
                model_lower
            ));
            code.push_str("    const data = await response.json();\n");
            code.push_str("    return data.data || [];\n");
            code.push_str("  }\n\n");

            code.push_str(&format!(
                "  async create{}(data: Omit<{}, 'id'>): Promise<{}> {{\n",
                model.name, model.name, model.name
            ));
            code.push_str(&format!(
                "    const response = await fetch(`${{this.baseUrl}}/api/{}`, {{\n",
                model_lower
            ));
            code.push_str("      method: 'POST',\n");
            code.push_str("      headers: { 'Content-Type': 'application/json' },\n");
            code.push_str("      body: JSON.stringify(data),\n");
            code.push_str("    });\n");
            code.push_str("    const result = await response.json();\n");
            code.push_str("    return result.data;\n");
            code.push_str("  }\n\n");
        }

        code.push_str("}\n");

        Ok(code)
    }

    /// Map ForgeDB field type to TypeScript type
    fn map_field_type(field_type: &forgedb_parser::FieldType) -> &'static str {
        match field_type {
            forgedb_parser::FieldType::I32 | forgedb_parser::FieldType::I64 | forgedb_parser::FieldType::F64 => "number",
            forgedb_parser::FieldType::Bool => "boolean",
            forgedb_parser::FieldType::String | forgedb_parser::FieldType::Uuid => "string",
            forgedb_parser::FieldType::Timestamp => "number",
            _ => "any",
        }
    }
}
