//! Browser read-replica transport generator (#110 Milestone C, follow-up #3).
//!
//! Emits, per schema, the `#[wasm_bindgen]` `Replica` glue that drives the
//! `wasm32` build of the generated `database.rs` as a read-only follower in the
//! browser. This is **class-2 transport glue** (the spirit of `crates/ffi`): the
//! lifecycle (`open`/`applyWire`/`commit`/`watermark`) is schema-invariant, and
//! every read it exposes is a thin wrapper over a method the generated
//! `Database` already emits — it invents **no** query API (the identity red
//! line). The tailored data logic stays in the generated `database.rs`; this
//! file only marshals ids/records across the JS boundary and JSON-serializes the
//! generated reads.
//!
//! Before #3 this transport was hand-written per schema in the E2E harness;
//! generating it removes that last hand-authored, schema-specific artifact from
//! the browser-replica path.

use crate::rust::RustGenerator;
use crate::{GeneratedCode, Result};
use forgedb_parser::{FieldType, Model, RelationType, Schema};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::{HashMap, HashSet};

/// Generates the `#[wasm_bindgen]` browser read-replica transport (`lib.rs`).
pub struct WasmGenerator;

/// The JSON shape a generated read returns across the boundary — drives both the
/// Rust wrapper body and the TS client's parse.
#[derive(Clone, Copy)]
enum ReadRet {
    /// `u32` live-record count.
    Count,
    /// `Option<String>` — a JSON record or `null`.
    Optional,
    /// `String` — a JSON array (never null; `"[]"` when empty).
    Array,
}

/// One generated read method — the single source of truth shared by the Rust
/// `Replica` (`rust`) and the TS `ReplicaClient` (name/args/ret). Enumerated
/// once by [`WasmGenerator::read_surface`] so the client can never drift from,
/// or invent a method absent from, the `Replica` (the PM's strict-mirror
/// constraint).
struct ReadMethod {
    js_name: String,
    /// Whether the method takes a single `id: String` argument.
    takes_id: bool,
    ret: ReadRet,
    /// The `#[wasm_bindgen]` Rust wrapper emitted into the `Replica` impl.
    rust: TokenStream,
}

impl WasmGenerator {
    /// Generate the transport `lib.rs` for a schema.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let surface = Self::read_surface(schema);
        let reads: Vec<&TokenStream> = surface.iter().map(|m| &m.rust).collect();

        // Lifecycle is schema-invariant boilerplate; the reads impl is generated.
        let tokens = quote! {
            //! Generated by ForgeDB — browser read-replica transport (wasm-bindgen).
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue for the #110 browser read-replica follower.
            //! Exposes ONLY the generated read surface + lifecycle to browser JS —
            //! it invents no query API. The tailored data logic lives in the
            //! generated `database.rs`; this file is glue.
            #![allow(warnings)]

            mod database;

            use std::cell::Cell;
            use std::cell::RefCell;
            use std::path::PathBuf;

            use forgedb_changefeed::durable::PersistedEvent;
            use forgedb_storage::persist::{self, Backend};
            use forgedb_storage::store;
            use forgedb_types::Uuid;
            use wasm_bindgen::prelude::*;

            use database::Database;

            /// The arena-blob key under which the resume watermark is persisted,
            /// so it rides the same IndexedDB/OPFS dump as the column data.
            fn watermark_key(db_name: &str) -> PathBuf {
                PathBuf::from(format!("{db_name}/_watermark"))
            }

            /// A ForgeDB browser read-replica following one server tenant.
            #[wasm_bindgen]
            pub struct Replica {
                // Interior mutability so the exported async methods can take
                // `&self` (wasm-bindgen cannot hold `&mut self` across an await).
                db: RefCell<Database>,
                backend: Backend,
                db_name: String,
                watermark: Cell<u64>,
            }

            #[wasm_bindgen]
            impl Replica {
                /// Open (or resume) the replica for `db_name` over `backend`
                /// (`"indexeddb"` or `"opfs"`). Loads the persisted column blobs
                /// into the in-memory arenas (the async hydrate boundary), opens
                /// the generated `Database` over them, and reads the last-applied
                /// offset so the caller can reconnect with `/replicate?after=W`.
                pub async fn open(db_name: String, backend: String) -> Result<Replica, JsValue> {
                    let backend = Backend::from_str_lossy(&backend);
                    store::clear();
                    // Hydrate strategy is the backend's: IndexedDB loads every
                    // blob now (eager); OPFS registers a synchronous fault-in
                    // source and reads nothing until a column is first touched
                    // (lazy / partial). Either way the per-row API stays sync.
                    persist::hydrate(backend, &db_name)
                        .await
                        .map_err(|e| JsValue::from_str(&format!("hydrate failed: {e:?}")))?;

                    // The follower opens under a stable root == db_name, so its
                    // arena paths are identical across sessions and round-trip
                    // through persist.
                    let root = PathBuf::from(&db_name);
                    let db = Database::open_at(root);

                    let watermark = store::get(&watermark_key(&db_name))
                        .filter(|b| b.len() == 8)
                        .map(|b| u64::from_le_bytes(b.try_into().unwrap()))
                        .unwrap_or(0);

                    Ok(Replica {
                        db: RefCell::new(db),
                        backend,
                        db_name,
                        watermark: Cell::new(watermark),
                    })
                }

                /// Apply one binary `/replicate` frame (an opaque
                /// `PersistedEvent::to_wire`). Decodes it and replays through the
                /// generated `apply_frame`; advances the resume watermark. The
                /// follower never decodes a field to route.
                #[wasm_bindgen(js_name = applyWire)]
                pub fn apply_wire(&self, bytes: &[u8]) -> Result<(), JsValue> {
                    let ev = PersistedEvent::from_wire(bytes)
                        .map_err(|e| JsValue::from_str(&format!("bad frame: {e}")))?;
                    let offset = ev.offset;
                    self.db
                        .borrow_mut()
                        .apply_frame(&ev)
                        .map_err(|e| JsValue::from_str(&format!("apply failed: {e}")))?;
                    if offset > self.watermark.get() {
                        self.watermark.set(offset);
                    }
                    Ok(())
                }

                /// Persist the current arenas + resume watermark to IndexedDB/OPFS
                /// at commit granularity. Durable across a tab reload.
                pub async fn commit(&self) -> Result<(), JsValue> {
                    {
                        self.db
                            .borrow_mut()
                            .commit()
                            .map_err(|e| JsValue::from_str(&format!("commit failed: {e}")))?;
                    }
                    store::put(
                        watermark_key(&self.db_name),
                        self.watermark.get().to_le_bytes().to_vec(),
                    );
                    // IndexedDB rewrites the whole snapshot; OPFS writes only the
                    // grown column tails, watermark marker last (crash-recoverable
                    // prefix — see `persist::commit`).
                    persist::commit(self.backend, &self.db_name)
                        .await
                        .map_err(|e| JsValue::from_str(&format!("persist failed: {e:?}")))?;
                    Ok(())
                }

                /// The highest applied offset — pass as `/replicate?after=<watermark>`.
                pub fn watermark(&self) -> u64 {
                    self.watermark.get()
                }

                #(#reads)*
            }
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!(
                "Failed to parse generated wasm transport: {e}"
            ))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!(
                "wasm-bindgen browser read-replica transport ({} models)",
                schema.models.len()
            ),
        })
    }

    /// Enumerate the generated read surface ONCE, mirroring the read methods of
    /// the generated `Database` exactly (same names, via the same `RustGenerator`
    /// helpers) so neither the `Replica` nor the `ReplicaClient` ever invents a
    /// query. Each entry carries the Rust wrapper AND the (name, args, ret)
    /// descriptor the TS client is generated from — one source of truth. A
    /// single `seen` gate on both the Rust ident and the JS name guarantees no
    /// duplicate method or duplicate `js_name` (either would fail to compile /
    /// bind).
    fn read_surface(schema: &Schema) -> Vec<ReadMethod> {
        let mut methods: Vec<ReadMethod> = Vec::new();
        let mut seen_rust: HashSet<String> = HashSet::new();
        let mut seen_js: HashSet<String> = HashSet::new();

        let mut push = |methods: &mut Vec<ReadMethod>,
                        rust_name: &str,
                        js_name: &str,
                        takes_id: bool,
                        ret: ReadRet,
                        tokens: TokenStream| {
            if !seen_rust.insert(rust_name.to_string()) || !seen_js.insert(js_name.to_string()) {
                return;
            }
            methods.push(ReadMethod {
                js_name: js_name.to_string(),
                takes_id,
                ret,
                rust: tokens,
            });
        };

        // --- Per-model core reads: get / count / all -------------------------
        for model in &schema.models {
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_field = format_ident!("{model_snake}");

            // count (every model has storage)
            let count_rust = format!("{model_snake}_count");
            let count_js = format!("{}Count", lower_camel_from_pascal(&model.name));
            let count_ident = format_ident!("{count_rust}");
            push(
                &mut methods,
                &count_rust,
                &count_js,
                false,
                ReadRet::Count,
                quote! {
                    #[doc = "Number of live records (a generated read)."]
                    #[wasm_bindgen(js_name = #count_js)]
                    pub fn #count_ident(&self) -> u32 {
                        self.db.borrow().#model_field.all().len() as u32
                    }
                },
            );

            // all -> JSON array
            let all_rust = format!("all_{model_snake}");
            let all_js = format!("all{}s", model.name);
            let all_ident = format_ident!("{all_rust}");
            push(
                &mut methods,
                &all_rust,
                &all_js,
                false,
                ReadRet::Array,
                quote! {
                    #[doc = "All live records as a JSON array (a generated read)."]
                    #[wasm_bindgen(js_name = #all_js)]
                    pub fn #all_ident(&self) -> String {
                        serde_json::to_string(&self.db.borrow().#model_field.all())
                            .unwrap_or_else(|_| "[]".to_string())
                    }
                },
            );

            // get(id) -> JSON | null — only for id-bearing models.
            if identity_field(model).is_some() {
                let get_rust = format!("get_{model_snake}");
                let get_js = format!("get{}", model.name);
                let get_ident = format_ident!("{get_rust}");
                let pk_parse = pk_parse_opt(schema, model);
                push(
                    &mut methods,
                    &get_rust,
                    &get_js,
                    true,
                    ReadRet::Optional,
                    quote! {
                        #[doc = "A record by id as JSON, or `null` (a generated read; 404-equivalent)."]
                        #[wasm_bindgen(js_name = #get_js)]
                        pub fn #get_ident(&self, id: String) -> Option<String> {
                            let __pk = #pk_parse?;
                            let __rec = self.db.borrow().#model_field.get(__pk)?;
                            serde_json::to_string(&__rec).ok()
                        }
                    },
                );
            }
        }

        // --- Forward FK getters (`*Target` / `?Target`) ----------------------
        // Mirror `generate_traversal_impl` section A: the generated method
        // `<model>_<field>(&record) -> Option<Target>` exists for every FK to a
        // UUID-keyed target. The wrapper fetches the source record by id first
        // (only possible when the source model is itself id-bearing), then
        // resolves through the generated getter.
        for model in &schema.models {
            let Some(_) = identity_field(model) else {
                continue;
            };
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_field = format_ident!("{model_snake}");
            let pk_parse = pk_parse_opt(schema, model);
            for field in &model.fields {
                let target_name = match &field.field_type {
                    FieldType::Relation(RelationType::RequiredReference(t))
                    | FieldType::Relation(RelationType::OptionalReference(t)) => t,
                    _ => continue,
                };
                if schema.find_model(target_name).is_none() {
                    continue;
                }
                let method_name = format!("{model_snake}_{}", field.name);
                let method_ident = format_ident!("{method_name}");
                let js = lower_camel_from_snake(&method_name);
                push(
                    &mut methods,
                    &method_name,
                    &js,
                    true,
                    ReadRet::Optional,
                    quote! {
                        #[doc = "Resolve the foreign key to its record as JSON, or `null` (a generated read)."]
                        #[wasm_bindgen(js_name = #js)]
                        pub fn #method_ident(&self, id: String) -> Option<String> {
                            let __pk = #pk_parse?;
                            let __db = self.db.borrow();
                            let __rec = __db.#model_field.get(__pk)?;
                            let __res = __db.#method_ident(&__rec)?;
                            serde_json::to_string(&__res).ok()
                        }
                    },
                );
            }
        }

        // --- Reverse one-to-many collection getters --------------------------
        // Mirror section B, including the by-child-field disambiguation for a
        // parent whose child holds multiple FKs back to it. #266: the argument
        // is parsed as the parent's OWN key type, so a non-uuid-keyed parent is
        // an ordinary FK target here too.
        let pairs = schema.detect_relations();
        let mut group_counts: HashMap<(String, String), usize> = HashMap::new();
        for p in &pairs {
            *group_counts
                .entry((p.parent_model.clone(), p.parent_field.clone()))
                .or_default() += 1;
        }
        for p in &pairs {
            let Some(parent) = schema.find_model(&p.parent_model) else {
                continue;
            };
            // #266: the argument is the PARENT's key, whatever it is.
            let parent_pk_parse = pk_parse_opt(schema, parent);
            let ambiguous = group_counts
                .get(&(p.parent_model.clone(), p.parent_field.clone()))
                .is_some_and(|&c| c > 1);
            let method_name = if ambiguous {
                format!(
                    "{}_{}_by_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field,
                    p.child_field
                )
            } else {
                format!(
                    "{}_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field
                )
            };
            let method_ident = format_ident!("{method_name}");
            let js = lower_camel_from_snake(&method_name);
            let doc = format!("All {} referencing the given id, as a JSON array.", p.child_model);
            push(
                &mut methods,
                &method_name,
                &js,
                true,
                ReadRet::Array,
                quote! {
                    #[doc = #doc]
                    #[wasm_bindgen(js_name = #js)]
                    pub fn #method_ident(&self, id: String) -> String {
                        let Some(__pk) = #parent_pk_parse else {
                            return "[]".to_string();
                        };
                        serde_json::to_string(&self.db.borrow().#method_ident(__pk))
                            .unwrap_or_else(|_| "[]".to_string())
                    }
                },
            );
        }

        // --- Many-to-many query helpers --------------------------------------
        // Mirror section C: `<model1>_<field1>` and `<model2>_<field2>` each take
        // THAT endpoint's own id (#266) and return the linked records. (The
        // `link_*` mutators are NOT exposed — a read replica is a follower.)
        for m in RustGenerator::valid_m2m(schema) {
            for (model_name, field) in
                [(&m.model1, &m.field1), (&m.model2, &m.field2)]
            {
                // The id arrives from JS as a string and is parsed as the
                // endpoint model's OWN key type.
                let Some(endpoint) = schema.find_model(model_name) else {
                    continue;
                };
                let pk_parse = pk_parse_opt(schema, endpoint);
                let method_name =
                    format!("{}_{}", RustGenerator::to_snake_case(model_name), field);
                let method_ident = format_ident!("{method_name}");
                let js = lower_camel_from_snake(&method_name);
                let doc = format!("All records linked to the given {model_name} id, as a JSON array.");
                push(
                    &mut methods,
                    &method_name,
                    &js,
                    true,
                    ReadRet::Array,
                    quote! {
                        #[doc = #doc]
                        #[wasm_bindgen(js_name = #js)]
                        pub fn #method_ident(&self, id: String) -> String {
                            let Some(__pk) = #pk_parse else {
                                return "[]".to_string();
                            };
                            serde_json::to_string(&self.db.borrow().#method_ident(__pk))
                                .unwrap_or_else(|_| "[]".to_string())
                        }
                    },
                );
            }
        }

        // --- Column projections (#113) ---------------------------------------
        // Per @projection, a narrow read on the follower: only the projected
        // columns are decoded, so the storage-web lazy backend never faults in
        // the unselected columns — the browser working-set win. Mirrors the
        // generated `get_<name>` / `all_<name>` storage methods.
        for model in &schema.models {
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_field = format_ident!("{model_snake}");
            for proj in &model.projections {
                let pascal = RustGenerator::projection_pascal(&proj.name);

                // all_<name> -> JSON array
                let all_rust = format!("all_{model_snake}_{}", proj.name);
                let all_js = format!("all{}{}", model.name, pascal);
                let all_ident = format_ident!("{all_rust}");
                let proj_all = format_ident!("all_{}", proj.name);
                push(
                    &mut methods,
                    &all_rust,
                    &all_js,
                    false,
                    ReadRet::Array,
                    quote! {
                        #[doc = "All live records as this projection (a generated narrow read; unselected columns stay lazy)."]
                        #[wasm_bindgen(js_name = #all_js)]
                        pub fn #all_ident(&self) -> String {
                            serde_json::to_string(&self.db.borrow().#model_field.#proj_all())
                                .unwrap_or_else(|_| "[]".to_string())
                        }
                    },
                );

                // get_<name>(id) -> JSON | null — id-bearing models only.
                if identity_field(model).is_some() {
                    let get_rust = format!("get_{model_snake}_{}", proj.name);
                    let get_js = format!("get{}{}", model.name, pascal);
                    let get_ident = format_ident!("{get_rust}");
                    let proj_get = format_ident!("get_{}", proj.name);
                    let pk_parse = pk_parse_opt(schema, model);
                    push(
                        &mut methods,
                        &get_rust,
                        &get_js,
                        true,
                        ReadRet::Optional,
                        quote! {
                            #[doc = "The projection for an id as JSON, or `null` (a generated narrow read; unselected columns stay lazy)."]
                            #[wasm_bindgen(js_name = #get_js)]
                            pub fn #get_ident(&self, id: String) -> Option<String> {
                                let __pk = #pk_parse?;
                                let __rec = self.db.borrow().#model_field.#proj_get(__pk)?;
                                serde_json::to_string(&__rec).ok()
                            }
                        },
                    );
                }
            }
        }

        methods
    }

    /// Generate the per-schema async **`ReplicaClient`** (TypeScript, main
    /// thread). It mirrors the `Replica`'s read surface EXACTLY — one typed async
    /// method per [`ReadMethod`] from [`read_surface`] — each `postMessage`-ing
    /// `{method, args}` to the Worker (which runs the engine) and awaiting the
    /// reply. It invents no query and exposes no mutator: strict class-2 glue,
    /// the async transport hop across the Worker boundary (the PM constraint).
    /// The Worker bootstrap it drives is a STATIC, schema-agnostic script emitted
    /// separately (never from this generator).
    pub fn generate_client(schema: &Schema) -> Result<GeneratedCode> {
        let surface = Self::read_surface(schema);

        let mut methods = String::new();
        for m in &surface {
            let (sig_args, call_args) = if m.takes_id {
                ("id: string", "[id]")
            } else {
                ("", "[]")
            };
            let (ret_ty, body) = match m.ret {
                ReadRet::Count => (
                    "number".to_string(),
                    format!("return (await this.#call('{}', {})) as number;", m.js_name, call_args),
                ),
                ReadRet::Optional => (
                    "Record<string, unknown> | null".to_string(),
                    format!(
                        "const r = await this.#call('{}', {}); return r == null ? null : JSON.parse(r as string);",
                        m.js_name, call_args
                    ),
                ),
                ReadRet::Array => (
                    "Record<string, unknown>[]".to_string(),
                    format!(
                        "const r = await this.#call('{}', {}); return JSON.parse((r as string) ?? '[]');",
                        m.js_name, call_args
                    ),
                ),
            };
            methods.push_str(&format!(
                "\n  /** Generated read — mirrors `Replica.{name}`. */\n  async {name}({sig}): Promise<{ret}> {{\n    {body}\n  }}\n",
                name = m.js_name,
                sig = sig_args,
                ret = ret_ty,
                body = body,
            ));
        }

        let code = format!(
            r#"// Generated by ForgeDB — browser read-replica async client.
// DO NOT EDIT - This file is auto-generated.
//
// Class-2 transport glue for the #110 browser read-replica follower. Runs on the
// main thread and mirrors the generated `Replica`'s read surface EXACTLY, one
// typed async method per generated read. Each call is a `postMessage` RPC to the
// Worker that runs the engine (`replica-worker.js`, a static schema-agnostic
// script). This file invents no query and exposes no mutator — a follower is
// read-only, and all field-aware logic lives in the generated Rust it drives.

export type ReplicaBackend = "indexeddb" | "opfs" | "auto";

export interface ReplicaOpenOptions {{
  /** Durable backend; "auto" probes for OPFS sync-access support. */
  backend?: ReplicaBackend;
  /** WebSocket `/replicate` URL; when set the Worker follows the live stream. */
  replicateUrl?: string;
}}

interface Pending {{
  resolve: (v: unknown) => void;
  reject: (e: unknown) => void;
}}

export class ReplicaClient {{
  #worker: Worker;
  #seq = 0;
  #pending = new Map<number, Pending>();

  /**
   * @param workerUrl URL of the static `replica-worker.js` (schema-agnostic).
   * @param wasmUrl   URL of the wasm-pack ES module (`<pkg>/<name>.js`).
   */
  constructor(workerUrl: string | URL, private wasmUrl: string) {{
    this.#worker = new Worker(workerUrl, {{ type: "module" }});
    this.#worker.onmessage = (e: MessageEvent) => {{
      const {{ id, ok, result, error }} = e.data ?? {{}};
      const p = this.#pending.get(id);
      if (!p) return;
      this.#pending.delete(id);
      if (ok) p.resolve(result);
      else p.reject(new Error(String(error)));
    }};
  }}

  #call(method: string, args: unknown[]): Promise<unknown> {{
    const id = ++this.#seq;
    return new Promise((resolve, reject) => {{
      this.#pending.set(id, {{ resolve, reject }});
      this.#worker.postMessage({{ id, method, args }});
    }});
  }}

  /** Boot the wasm module in the Worker (call once before `open`). */
  async init(): Promise<void> {{
    await this.#call("__init", [this.wasmUrl]);
  }}

  /** Open (or resume) the replica for `dbName` and, if given, follow the stream. */
  async open(dbName: string, opts: ReplicaOpenOptions = {{}}): Promise<void> {{
    await this.#call("__open", [
      dbName,
      opts.backend ?? "auto",
      opts.replicateUrl ?? null,
    ]);
  }}

  /** Apply one binary `/replicate` frame directly (for manual/test streaming). */
  async applyWire(frame: Uint8Array): Promise<void> {{
    await this.#call("__applyWire", [frame]);
  }}

  /** Persist the current state now (bypassing the debounce). */
  async commit(): Promise<void> {{
    await this.#call("commit", []);
  }}

  /** Highest applied replication offset (u64 arrives as BigInt → Number). */
  async watermark(): Promise<number> {{
    return Number(await this.#call("watermark", []));
  }}

  /** Tear down the Worker and its engine. */
  close(): void {{
    this.#worker.terminate();
  }}
{methods}}}
"#,
            methods = methods
        );

        Ok(GeneratedCode {
            code,
            description: format!(
                "async ReplicaClient (main-thread, {} read methods)",
                surface.len()
            ),
        })
    }

    /// The STATIC, schema-agnostic Worker bootstrap (`replica-worker.js`). It
    /// runs the wasm engine, owns the `/replicate` WebSocket, debounces
    /// auto-commit, and dispatches reads generically via `replica[method](...)`.
    /// It is a fixed string — NOT emitted by any schema-aware code path — so it
    /// cannot become schema-aware (the PM constraint). The `ReplicaClient` above
    /// is the schema-tailored half; this pipe knows only method NAMES it is told.
    pub fn worker_bootstrap() -> &'static str {
        WORKER_BOOTSTRAP_JS
    }

    /// The Worker bootstrap with the auto-commit debounce/frame-ceiling knobs
    /// substituted from the generate-time config (#148, epic #126). The template
    /// stays STATIC and schema-agnostic — only two schema-blind numeric constants
    /// are swapped, so the pipe still interprets no schema (#110 constraint).
    /// Default (250 / 100) yields the byte-identical bootstrap.
    pub fn worker_bootstrap_with_config(config: crate::GenConfig) -> String {
        WORKER_BOOTSTRAP_JS
            .replace(
                "const COMMIT_DEBOUNCE_MS = 250;",
                &format!("const COMMIT_DEBOUNCE_MS = {};", config.wasm_commit_debounce_ms),
            )
            .replace(
                "const COMMIT_MAX_FRAMES = 100;",
                &format!("const COMMIT_MAX_FRAMES = {};", config.wasm_commit_max_frames),
            )
    }

    /// The `Cargo.toml` for the generated replica crate. User-editable config,
    /// so the CLI writes it ONLY when absent (like the TS SDK's `package.json`).
    /// Pins the substrate at the versions the wasm build requires (see the
    /// "WASM PUBLISH GAP" note — these must be published for an outside-repo
    /// build to resolve from crates.io).
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.0.0"
edition = "2024"

# Compiled to WebAssembly with `wasm-pack build --target web`.
[lib]
crate-type = ["cdylib"]

[dependencies]
forgedb-storage = "0.3"
forgedb-types = "0.3"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
# The generated database.rs embeds a Tier-2 CommitSequencer field (MVCC #75);
# forgedb-txn is pure in-memory (no fs/net) so it compiles to wasm32. The Tier-3
# coordinator surface is cfg-gated off wasm, so forgedb-coordinator is NOT a
# replica dep. The read-only Replica transport exposes no write/transaction API.
forgedb-txn = "0.1"
rust_decimal = {{ version = "1", features = ["serde-with-str"] }}
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"

[profile.release]
opt-level = "s"
"#
        )
    }
}

/// The static, schema-agnostic Worker bootstrap. Runs the wasm engine, owns the
/// `/replicate` WebSocket, debounces auto-commit (idle ~250ms or ~100 frames),
/// probes for an OPFS sync-access backend, and dispatches reads generically via
/// `replica[method](...args)`. It interprets NO schema — it knows only the method
/// NAMES it is handed in each message (the PM's schema-agnostic-pipe constraint).
const WORKER_BOOTSTRAP_JS: &str = r#"// Generated by ForgeDB — browser read-replica Worker bootstrap (STATIC).
// DO NOT EDIT - schema-agnostic. Runs the wasm engine, follows /replicate,
// auto-commits on a debounce, and dispatches reads via replica[method](...args).

let mod = null;      // the wasm-pack ES module (booted on __init)
let replica = null;  // the generated Replica instance (opened on __open)
let ws = null;

// --- debounced auto-commit -------------------------------------------------
let pendingFrames = 0;
let commitTimer = null;
let committing = false;
const COMMIT_DEBOUNCE_MS = 250;
const COMMIT_MAX_FRAMES = 100;

function scheduleCommit() {
  pendingFrames++;
  if (pendingFrames >= COMMIT_MAX_FRAMES) { void doCommit(); return; }
  if (commitTimer) clearTimeout(commitTimer);
  commitTimer = setTimeout(() => { void doCommit(); }, COMMIT_DEBOUNCE_MS);
}

async function doCommit() {
  if (commitTimer) { clearTimeout(commitTimer); commitTimer = null; }
  if (committing || !replica) return;
  committing = true;
  pendingFrames = 0;
  try {
    await replica.commit();
  } catch (err) {
    console.error('[forgedb replica] commit failed', err);
  } finally {
    committing = false;
  }
}

// --- backend capability probe (sync-access-handle semantics) ---------------
async function probeBackend() {
  try {
    const root = await navigator.storage.getDirectory();
    const dir = await root.getDirectoryHandle('__forgedb_probe', { create: true });
    const fh = await dir.getFileHandle('p', { create: true });
    const ah = await fh.createSyncAccessHandle();
    const ok = typeof ah.getSize() === 'number'; // sync semantics -> a number
    ah.close();
    try { await dir.removeEntry('p'); } catch (_) {}
    try { await root.removeEntry('__forgedb_probe', { recursive: true }); } catch (_) {}
    return ok ? 'opfs' : 'indexeddb';
  } catch (_) {
    return 'indexeddb';
  }
}

// --- live /replicate follow ------------------------------------------------
function connect(url) {
  const sep = url.includes('?') ? '&' : '?';
  ws = new WebSocket(`${url}${sep}after=${replica.watermark()}`);
  ws.binaryType = 'arraybuffer';
  ws.onmessage = (e) => {
    // The /replicate stream is binary frames; ignore any non-binary control
    // message (e.g. a harness end-of-stream sentinel).
    if (typeof e.data === 'string') return;
    try {
      replica.applyWire(new Uint8Array(e.data));
      scheduleCommit();
    } catch (err) {
      console.error('[forgedb replica] apply failed', err);
    }
  };
  ws.onerror = (err) => console.error('[forgedb replica] ws error', err);
}

// --- generic RPC (schema-agnostic pipe) ------------------------------------
self.onmessage = async (e) => {
  const { id, method, args } = e.data || {};
  try {
    let result;
    if (method === '__init') {
      mod = await import(args[0]);
      await mod.default();
    } else if (method === '__open') {
      let [dbName, backend, replicateUrl] = args;
      if (backend === 'auto') backend = await probeBackend();
      replica = await mod.Replica.open(dbName, backend);
      if (replicateUrl) connect(replicateUrl);
      result = backend;
    } else if (method === '__applyWire') {
      replica.applyWire(new Uint8Array(args[0]));
      scheduleCommit();
    } else if (method === 'commit') {
      await replica.commit();
    } else if (method === 'watermark') {
      result = replica.watermark();
    } else {
      // A generated read: dispatch by name to the compiled Replica. The pipe
      // interprets nothing — the method name came from the generated client.
      result = replica[method](...args);
    }
    self.postMessage({ id, ok: true, result });
  } catch (err) {
    self.postMessage({ id, ok: false, error: String((err && err.stack) || err) });
  }
};
"#;

/// A model's identity field (`id`, or the first auto-generate field), if any.
///
/// **`id` wins by name, then by `+`.**  Written as a two-pass search rather than
/// one `find(|f| f.name == "id" || f.auto_generate)` on purpose (#254): the
/// single-pass form returns whichever comes FIRST in declaration order, so a
/// model writing `created_at: +timestamp` above `id: +uuid` resolves its identity
/// to the stamp.  Before #254 that produced a `Timestamp` id type and the
/// generated crate simply did not compile — loud, if obscure.  #254 makes a
/// `timestamp` identity legal, so the same schema would now compile and silently
/// key every row on its creation stamp.
fn identity_field(model: &Model) -> Option<&forgedb_parser::Field> {
    model
        .fields
        .iter()
        .find(|f| f.name == "id")
        .or_else(|| model.fields.iter().find(|f| f.auto_generate))
}

/// An expression yielding `Option<PkType>` from a `String` binding named `id`,
/// matching the model's identity type (uuid or integer). Only used for
/// id-bearing models.
fn pk_parse_opt(schema: &Schema, model: &Model) -> TokenStream {
    // #266: resolved, so a model whose identity is itself a foreign key
    // (`Order { id: *Customer }`) parses its key as the far end of the chain.
    match RustGenerator::identity_type(schema, model).as_ref() {
        Some(FieldType::U32) => quote! { id.parse::<u32>().ok() },
        Some(FieldType::U64) => quote! { id.parse::<u64>().ok() },
        Some(FieldType::I32) => quote! { id.parse::<i32>().ok() },
        Some(FieldType::I64) => quote! { id.parse::<i64>().ok() },
        // A string identity IS the string — parsing it as a uuid would reject
        // every id. #238 adds `string(N)` here; bare `string` was already in the
        // fall-through and already wrong, so both arms land together.
        Some(FieldType::String | FieldType::StringN { .. }) => quote! { Some(id) },
        _ => quote! { Uuid::parse_str(&id).ok() },
    }
}

/// `User` -> `user` (models are PascalCase; lowercase just the first char).
fn lower_camel_from_pascal(pascal: &str) -> String {
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// `user_posts` -> `userPosts`, `post_author` -> `postAuthor`. Deterministic
/// snake→lowerCamel so a generated JS name is stable across regenerations.
fn lower_camel_from_snake(snake: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}
