//! Browser read-replica transport generator (#110 Milestone C, follow-up #3).
//!
//! Emits, per schema, the `#[wasm_bindgen]` `Replica` glue that drives the
//! `wasm32` build of the generated `database.rs` as a read-only follower in the
//! browser. This is **class-2 transport glue** (the spirit of `crates/ffi`): the
//! lifecycle (`open`/`applyWire`/`commit`/`watermark`) is schema-invariant, and
//! every read it exposes is a thin wrapper over a method the generated
//! `Database` already emits — it invents **no** query API (the identity red
//! line). The tailored data logic stays in the generated `database.rs`; this
//! file only marshals ids/records across the JS boundary and JSON-serializes the
//! generated reads.
//!
//! Before #3 this transport was hand-written per schema in the E2E harness;
//! generating it removes that last hand-authored, schema-specific artifact from
//! the browser-replica path.

use crate::rust::RustGenerator;
use crate::{GeneratedCode, Result};
use forgedb_parser::{FieldType, Model, RelationType, Schema};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use std::collections::{HashMap, HashSet};

/// Generates the `#[wasm_bindgen]` browser read-replica transport (`lib.rs`).
pub struct WasmGenerator;

impl WasmGenerator {
    /// Generate the transport `lib.rs` for a schema.
    pub fn generate(schema: &Schema) -> Result<GeneratedCode> {
        let reads = Self::generate_reads(schema);

        // Lifecycle is schema-invariant boilerplate; the reads impl is generated.
        let tokens = quote! {
            //! Generated by ForgeDB — browser read-replica transport (wasm-bindgen).
            //! DO NOT EDIT - This file is auto-generated.
            //!
            //! Class-2 transport glue for the #110 browser read-replica follower.
            //! Exposes ONLY the generated read surface + lifecycle to browser JS —
            //! it invents no query API. The tailored data logic lives in the
            //! generated `database.rs`; this file is glue.
            #![allow(warnings)]

            mod database;

            use std::cell::Cell;
            use std::cell::RefCell;
            use std::path::PathBuf;

            use forgedb_changefeed::durable::PersistedEvent;
            use forgedb_storage::persist::{self, Backend};
            use forgedb_storage::store;
            use forgedb_types::Uuid;
            use wasm_bindgen::prelude::*;

            use database::Database;

            /// The arena-blob key under which the resume watermark is persisted,
            /// so it rides the same IndexedDB/OPFS dump as the column data.
            fn watermark_key(db_name: &str) -> PathBuf {
                PathBuf::from(format!("{db_name}/_watermark"))
            }

            /// A ForgeDB browser read-replica following one server tenant.
            #[wasm_bindgen]
            pub struct Replica {
                // Interior mutability so the exported async methods can take
                // `&self` (wasm-bindgen cannot hold `&mut self` across an await).
                db: RefCell<Database>,
                backend: Backend,
                db_name: String,
                watermark: Cell<u64>,
            }

            #[wasm_bindgen]
            impl Replica {
                /// Open (or resume) the replica for `db_name` over `backend`
                /// (`"indexeddb"` or `"opfs"`). Loads the persisted column blobs
                /// into the in-memory arenas (the async hydrate boundary), opens
                /// the generated `Database` over them, and reads the last-applied
                /// offset so the caller can reconnect with `/replicate?after=W`.
                pub async fn open(db_name: String, backend: String) -> Result<Replica, JsValue> {
                    let backend = Backend::from_str_lossy(&backend);
                    store::clear();
                    let entries = persist::load(backend, &db_name)
                        .await
                        .map_err(|e| JsValue::from_str(&format!("hydrate failed: {e:?}")))?;
                    store::hydrate(entries);

                    // The follower opens under a stable root == db_name, so its
                    // arena paths are identical across sessions and round-trip
                    // through persist.
                    let root = PathBuf::from(&db_name);
                    let db = Database::open_at(root);

                    let watermark = store::get(&watermark_key(&db_name))
                        .filter(|b| b.len() == 8)
                        .map(|b| u64::from_le_bytes(b.try_into().unwrap()))
                        .unwrap_or(0);

                    Ok(Replica {
                        db: RefCell::new(db),
                        backend,
                        db_name,
                        watermark: Cell::new(watermark),
                    })
                }

                /// Apply one binary `/replicate` frame (an opaque
                /// `PersistedEvent::to_wire`). Decodes it and replays through the
                /// generated `apply_frame`; advances the resume watermark. The
                /// follower never decodes a field to route.
                #[wasm_bindgen(js_name = applyWire)]
                pub fn apply_wire(&self, bytes: &[u8]) -> Result<(), JsValue> {
                    let ev = PersistedEvent::from_wire(bytes)
                        .map_err(|e| JsValue::from_str(&format!("bad frame: {e}")))?;
                    let offset = ev.offset;
                    self.db
                        .borrow_mut()
                        .apply_frame(&ev)
                        .map_err(|e| JsValue::from_str(&format!("apply failed: {e}")))?;
                    if offset > self.watermark.get() {
                        self.watermark.set(offset);
                    }
                    Ok(())
                }

                /// Persist the current arenas + resume watermark to IndexedDB/OPFS
                /// at commit granularity. Durable across a tab reload.
                pub async fn commit(&self) -> Result<(), JsValue> {
                    {
                        self.db
                            .borrow_mut()
                            .commit()
                            .map_err(|e| JsValue::from_str(&format!("commit failed: {e}")))?;
                    }
                    store::put(
                        watermark_key(&self.db_name),
                        self.watermark.get().to_le_bytes().to_vec(),
                    );
                    let entries = store::dump();
                    persist::store(self.backend, &self.db_name, entries)
                        .await
                        .map_err(|e| JsValue::from_str(&format!("persist failed: {e:?}")))?;
                    Ok(())
                }

                /// The highest applied offset — pass as `/replicate?after=<watermark>`.
                pub fn watermark(&self) -> u64 {
                    self.watermark.get()
                }

                #(#reads)*
            }
        };

        let syntax_tree = syn::parse_file(&tokens.to_string()).map_err(|e| {
            crate::CodegenError::GenerationFailed(format!(
                "Failed to parse generated wasm transport: {e}"
            ))
        })?;
        let code = prettyplease::unparse(&syntax_tree);

        Ok(GeneratedCode {
            code,
            description: format!(
                "wasm-bindgen browser read-replica transport ({} models)",
                schema.models.len()
            ),
        })
    }

    /// Emit the generated read wrappers, mirroring the read surface of the
    /// generated `Database` exactly (same names, via the same `RustGenerator`
    /// helpers) so the transport never invents a query. A single `seen` gate on
    /// both the Rust ident and the JS name guarantees no duplicate method or
    /// duplicate `js_name` (either would fail to compile / bind).
    fn generate_reads(schema: &Schema) -> Vec<TokenStream> {
        let mut methods = Vec::new();
        let mut seen_rust: HashSet<String> = HashSet::new();
        let mut seen_js: HashSet<String> = HashSet::new();

        let mut push = |methods: &mut Vec<TokenStream>,
                        rust_name: &str,
                        js_name: &str,
                        tokens: TokenStream| {
            if !seen_rust.insert(rust_name.to_string()) || !seen_js.insert(js_name.to_string()) {
                return;
            }
            methods.push(tokens);
        };

        // --- Per-model core reads: get / count / all -------------------------
        for model in &schema.models {
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_field = format_ident!("{model_snake}");

            // count (every model has storage)
            let count_rust = format!("{model_snake}_count");
            let count_js = format!("{}Count", lower_camel_from_pascal(&model.name));
            let count_ident = format_ident!("{count_rust}");
            push(
                &mut methods,
                &count_rust,
                &count_js,
                quote! {
                    #[doc = "Number of live records (a generated read)."]
                    #[wasm_bindgen(js_name = #count_js)]
                    pub fn #count_ident(&self) -> u32 {
                        self.db.borrow().#model_field.all().len() as u32
                    }
                },
            );

            // all -> JSON array
            let all_rust = format!("all_{model_snake}");
            let all_js = format!("all{}s", model.name);
            let all_ident = format_ident!("{all_rust}");
            push(
                &mut methods,
                &all_rust,
                &all_js,
                quote! {
                    #[doc = "All live records as a JSON array (a generated read)."]
                    #[wasm_bindgen(js_name = #all_js)]
                    pub fn #all_ident(&self) -> String {
                        serde_json::to_string(&self.db.borrow().#model_field.all())
                            .unwrap_or_else(|_| "[]".to_string())
                    }
                },
            );

            // get(id) -> JSON | null — only for id-bearing models.
            if identity_field(model).is_some() {
                let get_rust = format!("get_{model_snake}");
                let get_js = format!("get{}", model.name);
                let get_ident = format_ident!("{get_rust}");
                let pk_parse = pk_parse_opt(model);
                push(
                    &mut methods,
                    &get_rust,
                    &get_js,
                    quote! {
                        #[doc = "A record by id as JSON, or `null` (a generated read; 404-equivalent)."]
                        #[wasm_bindgen(js_name = #get_js)]
                        pub fn #get_ident(&self, id: String) -> Option<String> {
                            let __pk = #pk_parse?;
                            let __rec = self.db.borrow().#model_field.get(__pk)?;
                            serde_json::to_string(&__rec).ok()
                        }
                    },
                );
            }
        }

        // --- Forward FK getters (`*Target` / `?Target`) ----------------------
        // Mirror `generate_traversal_impl` section A: the generated method
        // `<model>_<field>(&record) -> Option<Target>` exists for every FK to a
        // UUID-keyed target. The wrapper fetches the source record by id first
        // (only possible when the source model is itself id-bearing), then
        // resolves through the generated getter.
        for model in &schema.models {
            let Some(_) = identity_field(model) else {
                continue;
            };
            let model_snake = RustGenerator::to_snake_case(&model.name);
            let model_field = format_ident!("{model_snake}");
            let pk_parse = pk_parse_opt(model);
            for field in &model.fields {
                let target_name = match &field.field_type {
                    FieldType::Relation(RelationType::RequiredReference(t))
                    | FieldType::Relation(RelationType::OptionalReference(t)) => t,
                    _ => continue,
                };
                let Some(target) = schema.find_model(target_name) else {
                    continue;
                };
                if !RustGenerator::is_uuid_pk(target) {
                    continue;
                }
                let method_name = format!("{model_snake}_{}", field.name);
                let method_ident = format_ident!("{method_name}");
                let js = lower_camel_from_snake(&method_name);
                push(
                    &mut methods,
                    &method_name,
                    &js,
                    quote! {
                        #[doc = "Resolve the foreign key to its record as JSON, or `null` (a generated read)."]
                        #[wasm_bindgen(js_name = #js)]
                        pub fn #method_ident(&self, id: String) -> Option<String> {
                            let __pk = #pk_parse?;
                            let __db = self.db.borrow();
                            let __rec = __db.#model_field.get(__pk)?;
                            let __res = __db.#method_ident(&__rec)?;
                            serde_json::to_string(&__res).ok()
                        }
                    },
                );
            }
        }

        // --- Reverse one-to-many collection getters --------------------------
        // Mirror section B, including the by-child-field disambiguation for a
        // parent whose child holds multiple FKs back to it. Parents are
        // UUID-keyed, so the argument is always a uuid string.
        let pairs = schema.detect_relations();
        let mut group_counts: HashMap<(String, String), usize> = HashMap::new();
        for p in &pairs {
            *group_counts
                .entry((p.parent_model.clone(), p.parent_field.clone()))
                .or_default() += 1;
        }
        for p in &pairs {
            let Some(parent) = schema.find_model(&p.parent_model) else {
                continue;
            };
            if !RustGenerator::is_uuid_pk(parent) {
                continue;
            }
            let ambiguous = group_counts
                .get(&(p.parent_model.clone(), p.parent_field.clone()))
                .is_some_and(|&c| c > 1);
            let method_name = if ambiguous {
                format!(
                    "{}_{}_by_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field,
                    p.child_field
                )
            } else {
                format!(
                    "{}_{}",
                    RustGenerator::to_snake_case(&p.parent_model),
                    p.parent_field
                )
            };
            let method_ident = format_ident!("{method_name}");
            let js = lower_camel_from_snake(&method_name);
            let doc = format!("All {} referencing the given id, as a JSON array.", p.child_model);
            push(
                &mut methods,
                &method_name,
                &js,
                quote! {
                    #[doc = #doc]
                    #[wasm_bindgen(js_name = #js)]
                    pub fn #method_ident(&self, id: String) -> String {
                        let __pk = match Uuid::parse_str(&id) {
                            Ok(__u) => __u,
                            Err(_) => return "[]".to_string(),
                        };
                        serde_json::to_string(&self.db.borrow().#method_ident(__pk))
                            .unwrap_or_else(|_| "[]".to_string())
                    }
                },
            );
        }

        // --- Many-to-many query helpers --------------------------------------
        // Mirror section C: `<model1>_<field1>` and `<model2>_<field2>` both take
        // a uuid id and return the linked records. (The `link_*` mutators are NOT
        // exposed — a read replica is a follower.)
        for m in RustGenerator::valid_m2m(schema) {
            for (model_name, field) in
                [(&m.model1, &m.field1), (&m.model2, &m.field2)]
            {
                let method_name =
                    format!("{}_{}", RustGenerator::to_snake_case(model_name), field);
                let method_ident = format_ident!("{method_name}");
                let js = lower_camel_from_snake(&method_name);
                let doc = format!("All records linked to the given {model_name} id, as a JSON array.");
                push(
                    &mut methods,
                    &method_name,
                    &js,
                    quote! {
                        #[doc = #doc]
                        #[wasm_bindgen(js_name = #js)]
                        pub fn #method_ident(&self, id: String) -> String {
                            let __pk = match Uuid::parse_str(&id) {
                                Ok(__u) => __u,
                                Err(_) => return "[]".to_string(),
                            };
                            serde_json::to_string(&self.db.borrow().#method_ident(__pk))
                                .unwrap_or_else(|_| "[]".to_string())
                        }
                    },
                );
            }
        }

        methods
    }

    /// The `Cargo.toml` for the generated replica crate. User-editable config,
    /// so the CLI writes it ONLY when absent (like the TS SDK's `package.json`).
    /// Pins the substrate at the versions the wasm build requires (see the
    /// "WASM PUBLISH GAP" note — these must be published for an outside-repo
    /// build to resolve from crates.io).
    pub fn cargo_toml_scaffold(crate_name: &str) -> String {
        format!(
            r#"[package]
name = "{crate_name}"
version = "0.0.0"
edition = "2024"

# Compiled to WebAssembly with `wasm-pack build --target web`.
[lib]
crate-type = ["cdylib"]

[dependencies]
forgedb-storage = "0.2"
forgedb-types = "0.2"
forgedb-changefeed = "0.2"
forgedb-wal = "0.2"
forgedb-compaction = "0.1"
serde = {{ version = "1", features = ["derive"] }}
serde_json = "1"
utoipa = {{ version = "5", features = ["uuid"] }}
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"

[profile.release]
opt-level = "s"
"#
        )
    }
}

/// A model's identity field (`id`, or the first auto-generate field), if any.
fn identity_field(model: &Model) -> Option<&forgedb_parser::Field> {
    model.fields.iter().find(|f| f.name == "id" || f.auto_generate)
}

/// An expression yielding `Option<PkType>` from a `String` binding named `id`,
/// matching the model's identity type (uuid or integer). Only used for
/// id-bearing models.
fn pk_parse_opt(model: &Model) -> TokenStream {
    match identity_field(model).map(|f| &f.field_type) {
        Some(FieldType::U32) => quote! { id.parse::<u32>().ok() },
        Some(FieldType::U64) => quote! { id.parse::<u64>().ok() },
        Some(FieldType::I32) => quote! { id.parse::<i32>().ok() },
        Some(FieldType::I64) => quote! { id.parse::<i64>().ok() },
        _ => quote! { Uuid::parse_str(&id).ok() },
    }
}

/// `User` -> `user` (models are PascalCase; lowercase just the first char).
fn lower_camel_from_pascal(pascal: &str) -> String {
    let mut chars = pascal.chars();
    match chars.next() {
        Some(first) => first.to_lowercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}

/// `user_posts` -> `userPosts`, `post_author` -> `postAuthor`. Deterministic
/// snake→lowerCamel so a generated JS name is stable across regenerations.
fn lower_camel_from_snake(snake: &str) -> String {
    let mut out = String::new();
    let mut upper_next = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}
