[package]
name = "forgedb-validation"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"
description = "Schema validation for ForgeDB"
repository = "https://github.com/hoodiecollin/forgedb"
keywords = ["database", "validation", "forgedb", "schema"]
categories = ["database"]

[dependencies]
