//! In-tree Rust placement (#338, epic #332's class D).
//!
//! # What this is
//!
//! `[placement].rust_package` points at a directory in the **consumer's own
//! tree**, and `generate` writes a complete, self-contained, ForgeDB-owned cargo
//! package there: the same `core` the build cache gets, at a second destination.
//! It changes no generated byte — the package receives the same memoized
//! `String` `<output>/database.rs` receives, rendered by the same
//! [`CorePackage::files`] the cache emitter reads.
//!
//! From that point the consumer's cargo owns everything: one dependency
//! resolution, one `target/`, one lockfile, their profiles, their toolchain.
//! `forgedb build` does not compile it — class D has no delivery step.
//!
//! # What ForgeDB does NOT do
//!
//! It writes nothing outside the placement directory. Not the workspace root,
//! not `[workspace] members`, not `exclude`, not the consumer's
//! `[dependencies]`, not their `.gitignore`, not their lockfile.
//!
//! **The dep line is printed, never written.** Which of a consumer's crates
//! should depend on the database is not knowable — a workspace may hold many —
//! and picking one is guessing in a file ForgeDB did not author. Printing it
//! costs the user one paste and costs ForgeDB the entire class of "edited a file
//! it does not own" hazards.
//!
//! **No `members` entry.** Cargo makes every path dependency residing inside the
//! workspace directory a member automatically, so the entry is unnecessary — and
//! the write it would take on has a workspace-wide failure mode: a `members`
//! entry naming a path with no manifest is a hard error that breaks *every*
//! build in that workspace, including `cargo build -p` on unrelated members.
//!
//! **No `[workspace]` table in the emitted package.** Not a suboptimal choice —
//! an unusable one. A nested package carrying `[workspace]` that any member
//! path-depends on makes cargo fail the entire workspace with `multiple
//! workspace roots found in the same workspace`. It is buildable only while
//! nothing depends on it, which is to say only while it is useless. A generated
//! package with no `[workspace]` is the correct shape (measured; #430 closed as
//! not-a-defect).
//!
//! # The package is committed source
//!
//! A path dep pointing at a missing directory fails the workspace load for every
//! crate in it, including a fresh clone that has never run `forgedb generate`.
//! So the emitted package is checked in, like every other generated text
//! artifact under the epic's rule.
//!
//! # `fs::write`, never `write_file`
//!
//! `write_file` refuses an existing file without `--force`, so routing this
//! through it would make the second `generate` fail — and, worse, would make a
//! stale substrate pin survivable. This package is **ForgeDB's file**: its
//! header says so, and rewriting it in full on every generate is exactly what
//! keeps #290's floor problem out of user property.

use std::path::{Path, PathBuf};

use forgedb_codegen::{CorePackage, GenConfig};

use crate::{error::Result, ui};

/// Emit the ForgeDB-owned package into `dir`, and report both the path and the
/// line the consumer pastes.
///
/// Returns what was written, in the order [`CorePackage::files`] enumerates it.
///
/// **The line is printed on every emitting run**, not only when the manifest
/// changed. Printing on change is stateful, is untestable without a fixture that
/// survives two runs, and goes quiet in exactly the case where the user has not
/// pasted it yet.
pub(super) fn emit(
    dir: &Path,
    core_pkg: &str,
    config: &GenConfig,
    core_lib: &str,
) -> Result<Vec<PathBuf>> {
    let files = CorePackage::files(core_pkg, config, core_lib);
    let mut written = Vec::with_capacity(files.len());

    for (rel, body) in &files {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, body)?;
        written.push(path);
    }

    ui::success(&format!(
        "In-tree Rust package: {} ({} files)",
        dir.display(),
        written.len()
    ));
    ui::info("  Add this one line to the [dependencies] of whichever crate should use it:");
    ui::info(&format!("    {}", CorePackage::dep_line(core_pkg, dir)));

    Ok(written)
}
