//! In-tree Rust placement (#338, epic #332's class D).
//!
//! # What this is
//!
//! `[placement].rust_package` points at a directory in the **consumer's own
//! tree**, and `generate` writes a complete, self-contained, ForgeDB-owned cargo
//! package there: the same `core` the build cache gets, at a second destination.
//! It changes no generated byte — the package receives the same memoized
//! `String` `<output>/database.rs` receives, rendered by the same
//! [`CorePackage::files`] the cache emitter reads.
//!
//! From that point the consumer's cargo owns everything: one dependency
//! resolution, one `target/`, one lockfile, their profiles, their toolchain.
//! `forgedb build` does not compile it — class D has no delivery step.
//!
//! # What ForgeDB does NOT do
//!
//! It writes nothing outside the placement directory. Not the workspace root,
//! not `[workspace] members`, not `exclude`, not the consumer's
//! `[dependencies]`, not their `.gitignore`, not their lockfile.
//!
//! **The dep line is printed, never written.** Which of a consumer's crates
//! should depend on the database is not knowable — a workspace may hold many —
//! and picking one is guessing in a file ForgeDB did not author. Printing it
//! costs the user one paste and costs ForgeDB the entire class of "edited a file
//! it does not own" hazards.
//!
//! **No `members` entry.** Cargo makes every path dependency residing inside the
//! workspace directory a member automatically, so the entry is unnecessary — and
//! the write it would take on has a workspace-wide failure mode: a `members`
//! entry naming a path with no manifest is a hard error that breaks *every*
//! build in that workspace, including `cargo build -p` on unrelated members.
//!
//! **No `[workspace]` table in the emitted package.** Not a suboptimal choice —
//! an unusable one. A nested package carrying `[workspace]` that any member
//! path-depends on makes cargo fail the entire workspace with `multiple
//! workspace roots found in the same workspace`. It is buildable only while
//! nothing depends on it, which is to say only while it is useless. A generated
//! package with no `[workspace]` is the correct shape (measured; #430 closed as
//! not-a-defect).
//!
//! # The package is committed source
//!
//! A path dep pointing at a missing directory fails the workspace load for every
//! crate in it, including a fresh clone that has never run `forgedb generate`.
//! So the emitted package is checked in, like every other generated text
//! artifact under the epic's rule.
//!
//! # `fs::write`, never `write_file`
//!
//! `write_file` refuses an existing file without `--force`, so routing this
//! through it would make the second `generate` fail — and, worse, would make a
//! stale substrate pin survivable. This package is **ForgeDB's file**: its
//! header says so, and rewriting it in full on every generate is exactly what
//! keeps #290's floor problem out of user property.

use std::path::{Path, PathBuf};

use forgedb_codegen::{CorePackage, GenConfig};

use crate::{error::Result, ui};

/// Emit the ForgeDB-owned package into `dir`, and report both the path and the
/// line the consumer pastes.
///
/// Returns what was written, in the order [`CorePackage::files`] enumerates it.
///
/// **The line is printed on every emitting run**, not only when the manifest
/// changed. Printing on change is stateful, is untestable without a fixture that
/// survives two runs, and goes quiet in exactly the case where the user has not
/// pasted it yet.
///
/// **The `path` is written as ForgeDB resolved it — relative to the directory
/// `generate` ran in.** A consumer crate in a subdirectory has to re-base it, and
/// the printed message says so. The alternative, an absolute path, is correct on
/// exactly one machine: this line lands in a *committed* manifest, so an absolute
/// path breaks the repo for every other developer and for CI. ForgeDB cannot
/// compute the right relative path itself, because it does not know — and by
/// decision cannot know — which of the consumer's crates receives the line.
pub(super) fn emit(
    dir: &Path,
    core_pkg: &str,
    config: &GenConfig,
    core_lib: &str,
) -> Result<Vec<PathBuf>> {
    let files = CorePackage::files(core_pkg, config, core_lib);
    let mut written = Vec::with_capacity(files.len());

    for (rel, body) in &files {
        let path = dir.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, body)?;
        written.push(path);
    }

    ui::success(&format!(
        "In-tree Rust package: {} ({} files)",
        dir.display(),
        written.len()
    ));
    ui::info("  Add this one line to the [dependencies] of whichever crate should use it,");
    ui::info("  with `path` re-based against THAT crate's directory:");
    ui::info(&format!("    {}", CorePackage::dep_line(core_pkg, dir)));

    Ok(written)
}

/// Refuse a placement that resolves inside the build cache (C1/C8) **before
/// anything is written**.
///
/// The cache is derived state: `forgedb` prunes it, and a GC may delete it at
/// any time. A placement inside it is committed source in a directory whose
/// contract is "may vanish", so the two claims are irreconcilable and the config
/// is refused rather than repaired.
///
/// It asks [`crate::cache::home_containing`] the same question
/// `assert_not_in_cache` asks, and writes its own diagnostic: the two refusals
/// are about different things (a *data* root, a *placement*) and a shared
/// message would name the wrong one in half the cases.
///
/// **Where this is called matters more than what it does.** It runs before the
/// output directory is created and before the mirror is written, so a refused
/// config leaves the tree untouched. #345's lesson is the reason that is
/// asserted rather than assumed: `cache::assert_not_in_cache` was fully
/// mutation-tested while having executed zero times, because mutating a
/// predicate proves the check works and only mutating the CALL SITE proves it
/// runs.
pub(super) fn guard(dir: &Path) -> Result<()> {
    if let Some(home) = crate::cache::home_containing(dir)? {
        return Err(crate::error::CliError::Config(format!(
            "[placement].rust_package = {} resolves inside the ForgeDB build cache ({}).\n\
             The build cache is derived state and may be deleted at any time, so it must \
             never hold committed source — and an in-tree package is committed source: a \
             path dependency naming a missing directory fails the workspace load for every \
             crate in it.\n\
             Point `[placement].rust_package` at a directory in your own repository, or \
             remove the key to opt out.",
            dir.display(),
            home.display()
        )));
    }
    Ok(())
}

/// Compare only — **`--check` writes nothing, anywhere.**
///
/// Returns `(missing, stale)` for the in-tree package, to be joined into the
/// existing check-mode report.
///
/// It renders in memory and compares against the live location. It deliberately
/// does **not** piggyback on `generated_files`: that path computes
/// `committed.join(scratch.strip_prefix(output).unwrap_or(scratch))`, and
/// joining an *absolute* path replaces the base. A placement can sit anywhere,
/// including outside the output directory, so the `unwrap_or` would fall through
/// to the absolute scratch path and the join would silently resolve to the live
/// location — a check mode that writes.
pub(super) fn check(
    dir: &Path,
    core_pkg: &str,
    config: &GenConfig,
    core_lib: &str,
) -> Result<(Vec<PathBuf>, Vec<PathBuf>)> {
    let mut missing = Vec::new();
    let mut stale = Vec::new();

    for (rel, body) in CorePackage::files(core_pkg, config, core_lib) {
        let path = dir.join(rel);
        match std::fs::read_to_string(&path) {
            Ok(existing) if existing == body => {}
            Ok(_) => stale.push(path),
            Err(_) => missing.push(path),
        }
    }

    Ok((missing, stale))
}
