use std::path::{Component, Path, PathBuf};

use crate::error::{CliError, Result};
use crate::naming::PackageKind;

pub const HOME_ENV: &str = "FORGEDB_HOME";

const WORKSPACE_RESOLVER: &str = "3";

pub fn forgedb_home() -> Result<PathBuf> {
    if let Some(explicit) = std::env::var_os(HOME_ENV)
        && !explicit.is_empty()
    {
        return Ok(PathBuf::from(explicit));
    }

    home::home_dir()
        .map(|h| h.join(".forgedb"))
        .ok_or_else(|| {
            CliError::Config(format!(
                "Cannot determine a home directory for the ForgeDB build cache. \
                 Set {} to an explicit path.",
                HOME_ENV
            ))
        })
}

pub fn ledger_root() -> Result<PathBuf> {
    Ok(forgedb_home()?.join("ledger"))
}

pub fn projects_root() -> Result<PathBuf> {
    Ok(forgedb_home()?.join("projects"))
}

pub fn project_dir(project_id: &str) -> Result<PathBuf> {
    if project_id.is_empty() {
        return Err(CliError::Config(
            "Empty project id: the build cache cannot be keyed by an unnamed project".to_string(),
        ));
    }
    Ok(projects_root()?.join(project_id))
}

fn normalize_for_hash(rel_schema: &Path) -> String {
    let mut parts: Vec<String> = Vec::new();
    for component in rel_schema.components() {
        match component {
            Component::Normal(part) => parts.push(part.to_string_lossy().into_owned()),
            Component::CurDir => {}
            Component::RootDir | Component::Prefix(_) => {}
            Component::ParentDir => parts.push("..".to_string()),
        }
    }
    parts.join("/")
}

pub fn member_hash(rel_schema: &Path) -> String {
    path_hash(&normalize_for_hash(rel_schema))
}

pub fn path_hash(input: &str) -> String {
    fnv1a_hex(input.as_bytes())
}

pub fn fnv1a_hex(bytes: &[u8]) -> String {
    const FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;
    const FNV_PRIME: u64 = 0x100_0000_01b3;

    let mut hash = FNV_OFFSET_BASIS;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }

    format!("{:016x}", hash)
}

pub fn member_dir(project_id: &str, rel_schema: &Path) -> Result<PathBuf> {
    Ok(project_dir(project_id)?
        .join("apps")
        .join(member_hash(rel_schema)))
}

fn render_workspace_root(project: &Path, members: &[PathBuf]) -> Result<String> {
    let mut entries: Vec<String> = Vec::new();

    for member in members {
        let relative = member.strip_prefix(project).map_err(|_| {
            CliError::Config(format!(
                "Workspace member {} is not inside the project directory {}",
                member.display(),
                project.display()
            ))
        })?;

        let mut rendered = String::new();
        for (i, component) in relative.components().enumerate() {
            if let Component::Normal(part) = component {
                if i > 0 {
                    rendered.push('/');
                }
                rendered.push_str(&part.to_string_lossy());
            }
        }
        entries.push(rendered);
    }

    entries.sort();
    entries.dedup();

    let members_block = if entries.is_empty() {
        "members = []\n".to_string()
    } else {
        let listed = entries
            .iter()
            .map(|e| format!("    \"{}\",\n", e))
            .collect::<String>();
        format!("members = [\n{}]\n", listed)
    };

    let default_entries: Vec<&String> = entries
        .iter()
        .filter(|e| {
            e.rsplit('/')
                .next()
                .and_then(PackageKind::from_dir)
                .is_some_and(|k| k.is_default_member())
        })
        .collect();

    let default_block =
        if default_entries.is_empty() || default_entries.len() == entries.len() {
            String::new()
        } else {
            let listed = default_entries
                .iter()
                .map(|e| format!("    \"{}\",\n", e))
                .collect::<String>();
            format!("default-members = [\n{}]\n", listed)
        };

    Ok(format!(
        "# Generated by ForgeDB. Do not edit — this file is rewritten in full on\n\
         # every generate, as a pure function of the apps in this project.\n\
         #\n\
         # This is a build cache. Deleting this whole directory is safe: it holds\n\
         # no input, only derived state.\n\
         #\n\
         # The release profile floor (panic=unwind, and opt-level for wasm) is\n\
         # applied by `forgedb build` on the cargo invocation, NOT by this file.\n\
         # A bare `cargo build` run here does not get it.\n\
         [workspace]\n\
         resolver = \"{}\"\n\
         {}{}",
        WORKSPACE_RESOLVER, members_block, default_block
    ))
}

pub fn write_workspace_root(project: &Path, members: &[PathBuf]) -> Result<()> {
    std::fs::create_dir_all(project)?;
    let manifest = render_workspace_root(project, members)?;
    std::fs::write(project.join("Cargo.toml"), manifest)?;
    Ok(())
}

const MEMBER_SCHEMA_FILE: &str = "schema-path";

pub fn record_member(member: &Path, schema: &Path) -> Result<()> {
    std::fs::create_dir_all(member)?;
    std::fs::write(member.join(MEMBER_SCHEMA_FILE), schema.to_string_lossy().as_bytes())?;
    Ok(())
}

pub fn member_schema(member: &Path) -> Option<PathBuf> {
    let raw = std::fs::read_to_string(member.join(MEMBER_SCHEMA_FILE)).ok()?;
    let trimmed = raw.trim();
    (!trimmed.is_empty()).then(|| PathBuf::from(trimmed))
}

const MEMBER_APP_NAME_FILE: &str = "app-name";

pub fn record_app_name(member: &Path, app_name: &str) -> Result<()> {
    std::fs::create_dir_all(member)?;
    std::fs::write(member.join(MEMBER_APP_NAME_FILE), app_name.as_bytes())?;
    Ok(())
}

pub fn member_app_name(member: &Path) -> Option<String> {
    let raw = std::fs::read_to_string(member.join(MEMBER_APP_NAME_FILE)).ok()?;
    let trimmed = raw.trim();
    (!trimmed.is_empty()).then(|| trimmed.to_string())
}

pub fn live_members(project: &Path, keep: &Path) -> Result<Vec<PathBuf>> {
    let mut live = vec![keep.to_path_buf()];

    let apps_dir = project.join("apps");
    if apps_dir.exists() {
        for entry in std::fs::read_dir(&apps_dir)? {
            let entry = entry?;
            if !entry.file_type()?.is_dir() {
                continue;
            }
            let path = entry.path();
            if path == keep {
                continue;
            }
            match member_schema(&path) {
                Some(schema) if !schema.exists() => continue,
                _ => live.push(path),
            }
        }
    }

    live.sort();
    live.dedup();
    Ok(live)
}

pub fn orphans(project: &Path, live: &[PathBuf]) -> Result<Vec<PathBuf>> {
    if live.is_empty() {
        return Err(CliError::Config(format!(
            "Refusing to scan {} for orphans with an empty live member set — \
             this would report every member as garbage.",
            project.display()
        )));
    }

    let apps_dir = project.join("apps");
    if !apps_dir.exists() {
        return Ok(Vec::new());
    }

    let mut found = Vec::new();
    for entry in std::fs::read_dir(&apps_dir)? {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let path = entry.path();
        if !live.iter().any(|l| l == &path) {
            found.push(path);
        }
    }

    found.sort();
    Ok(found)
}

pub fn assert_not_in_cache(data_root: &Path) -> Result<()> {
    if let Some(home_resolved) = home_containing(data_root)? {
        return Err(CliError::Config(format!(
            "Data root {} resolves inside the ForgeDB build cache ({}).\n\
             The build cache is derived state and may be deleted at any time, so it \
             must never hold database data, tenant dirs, WAL, or backups.\n\
             Set an explicit `[tenant] root` outside the cache, or run from a \
             different working directory.",
            data_root.display(),
            home_resolved.display()
        )));
    }

    Ok(())
}

pub fn home_containing(path: &Path) -> Result<Option<PathBuf>> {
    let home = forgedb_home()?;

    let absolute = if path.is_absolute() {
        path.to_path_buf()
    } else {
        std::env::current_dir()?.join(path)
    };
    let resolved = closest_real_ancestor(&absolute);
    let home_resolved = closest_real_ancestor(&home);

    Ok(resolved
        .starts_with(&home_resolved)
        .then_some(home_resolved))
}

#[derive(Debug)]
pub struct Reserved {
    pub project: PathBuf,
    pub container: PathBuf,
    pub app_name: String,
}

pub fn reserve(
    project_id: &str,
    project_root: &Path,
    schema: &Path,
    mode: crate::naming::SymbolNaming,
) -> Result<Reserved> {
    let project = project_dir(project_id)?;
    let schema = absolutize(schema);

    let relative = schema
        .strip_prefix(project_root)
        .map(Path::to_path_buf)
        .unwrap_or_else(|_| schema.clone());

    let member = member_dir(project_id, &relative)?;
    record_member(&member, &schema)?;

    let siblings = crate::project::discover_schemas(project_root);
    let app_name = crate::naming::app_name(project_id, &relative, &siblings, mode);
    record_app_name(&member, &app_name)?;

    Ok(Reserved {
        project,
        container: member,
        app_name,
    })
}

#[derive(Debug)]
pub struct Synced {
    pub members: Vec<PathBuf>,
    pub orphans: Vec<PathBuf>,
    pub lock_dropped: bool,
}

const CLI_VERSION_FILE: &str = "cli-version";

fn enforce_cli_version(project: &Path) -> Result<bool> {
    let running = env!("CARGO_PKG_VERSION");
    let marker = project.join(CLI_VERSION_FILE);

    let recorded = std::fs::read_to_string(&marker).ok();
    let matches = recorded.as_deref().map(str::trim) == Some(running);
    if matches {
        return Ok(false);
    }

    let lock = project.join("Cargo.lock");
    let dropped = lock.is_file();
    if dropped {
        std::fs::remove_file(&lock)?;
    }

    std::fs::create_dir_all(project)?;
    std::fs::write(&marker, running.as_bytes())?;
    Ok(dropped)
}

pub fn sync_root(project: &Path, keep: &Path) -> Result<Synced> {
    sync_root_excluding(project, keep, &[])
}

pub fn sync_root_excluding(project: &Path, keep: &Path, excluded: &[PathBuf]) -> Result<Synced> {
    let live = live_members(project, keep)?;

    let mut members = Vec::new();
    for container in &live {
        members.extend(packages_in(container)?);
    }
    members.retain(|m| !excluded.iter().any(|e| same_dir(e, m)));
    members.sort();
    members.dedup();

    write_workspace_root(project, &members)?;
    let lock_dropped = enforce_cli_version(project)?;
    let orphans = orphans(project, &live)?;

    Ok(Synced {
        members,
        orphans,
        lock_dropped,
    })
}

#[derive(Debug)]
pub struct Pruned {
    pub synced: Synced,
    pub removed: Vec<PathBuf>,
}

pub fn prune(project: &Path, keep: &Path, doomed: &[PathBuf]) -> Result<Pruned> {
    prune_with(project, keep, doomed, &mut |dir| std::fs::remove_dir_all(dir))
}

fn prune_with(
    project: &Path,
    keep: &Path,
    doomed: &[PathBuf],
    remove: &mut dyn FnMut(&Path) -> std::io::Result<()>,
) -> Result<Pruned> {
    for dir in doomed {
        let inside = closest_real_ancestor(dir).starts_with(closest_real_ancestor(keep));
        if !inside {
            return Err(CliError::Config(format!(
                "Refusing to prune {}: it is outside the app container {} this prune \
                 was given. A prune never reaches beyond one app.",
                dir.display(),
                keep.display()
            )));
        }
    }

    let synced = sync_root_excluding(project, keep, doomed)?;

    let mut removed = Vec::new();
    for dir in doomed {
        match remove(dir) {
            Ok(()) => removed.push(dir.clone()),
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => return Err(e.into()),
        }
    }

    Ok(Pruned { synced, removed })
}

pub fn prunable(
    container: &Path,
    declared_kinds: &[PackageKind],
    owner: crate::naming::PruneOwner,
) -> Result<Vec<PathBuf>> {
    let mut doomed = Vec::new();
    let entries = match std::fs::read_dir(container) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(doomed),
        Err(e) => return Err(e.into()),
    };

    for entry in entries {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };
        let Some(kind) = PackageKind::from_dir(name) else {
            continue;
        };
        if kind.owner() != owner {
            continue;
        }
        if declared_kinds.contains(&kind) {
            continue;
        }
        doomed.push(entry.path());
    }

    doomed.sort();
    Ok(doomed)
}

fn packages_in(container: &Path) -> Result<Vec<PathBuf>> {
    let mut found = Vec::new();
    let entries = match std::fs::read_dir(container) {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(found),
        Err(e) => return Err(e.into()),
    };

    for entry in entries {
        let entry = entry?;
        if !entry.file_type()?.is_dir() {
            continue;
        }
        let path = entry.path();
        let name = entry.file_name();
        let Some(name) = name.to_str() else { continue };
        if PackageKind::from_dir(name).is_none() {
            continue;
        }
        if path.join("Cargo.toml").is_file() {
            found.push(path);
        }
    }

    found.sort();
    Ok(found)
}

fn same_dir(a: &Path, b: &Path) -> bool {
    a == b || closest_real_ancestor(a) == closest_real_ancestor(b)
}

fn absolutize(p: &Path) -> PathBuf {
    if p.is_absolute() {
        return p.to_path_buf();
    }
    match std::env::current_dir() {
        Ok(cwd) => cwd.join(p),
        Err(_) => p.to_path_buf(),
    }
}

fn closest_real_ancestor(path: &Path) -> PathBuf {
    let mut current = path;
    loop {
        if let Ok(canonical) = current.canonicalize() {
            let remainder = path.strip_prefix(current).unwrap_or(Path::new(""));
            return canonical.join(remainder);
        }
        match current.parent() {
            Some(parent) => current = parent,
            None => return path.to_path_buf(),
        }
    }
}

#[cfg(test)]
mod prune_order_tests {

    use super::*;
    use crate::naming::PruneOwner;

    fn stub_package(dir: &Path, name: &str) {
        std::fs::create_dir_all(dir.join("src")).unwrap();
        std::fs::write(
            dir.join("Cargo.toml"),
            format!("[package]\nname = \"{name}\"\nversion = \"0.0.0\"\nedition = \"2021\"\n"),
        )
        .unwrap();
        std::fs::write(dir.join("src/lib.rs"), "").unwrap();
    }

    fn fixture() -> (tempfile::TempDir, PathBuf, PathBuf) {
        let tmp = tempfile::tempdir().unwrap();
        let project = tmp.path().join("projects/p");
        let container = project.join("apps/aaaaaaaaaaaaaaaa");
        let sibling = project.join("apps/bbbbbbbbbbbbbbbb");

        stub_package(&container.join("core"), "a-core");
        stub_package(&container.join("napi"), "a-napi");
        stub_package(&sibling.join("core"), "b-core");

        sync_root(&project, &container).unwrap();
        assert!(
            members_in_manifest(&project).contains("/napi"),
            "the fixture starts with the doomed package LISTED"
        );

        (tmp, project, container)
    }

    fn members_in_manifest(project: &Path) -> String {
        std::fs::read_to_string(project.join("Cargo.toml")).unwrap()
    }

    #[test]
    fn scenario_12_the_root_is_rewritten_before_anything_is_unlinked() {
        let (_tmp, project, container) = fixture();
        let doomed = prunable(&container, &[PackageKind::Core], PruneOwner::GenerateBuild).unwrap();
        assert_eq!(doomed, vec![container.join("napi")], "napi is the doomed one");

        let mut observed = 0;
        let killed = prune_with(&project, &container, &doomed, &mut |dir| {
            observed += 1;

            let manifest = members_in_manifest(&project);
            assert!(
                !manifest.contains("/napi"),
                "the root still names the package about to be deleted — every app \
                 in this project is about to become unbuildable:\n{manifest}"
            );
            assert!(manifest.contains("/core"), "the survivors are still listed:\n{manifest}");
            assert!(dir.is_dir(), "the delete has not happened yet");

            Err(std::io::Error::other("killed between the de-list and the delete"))
        });

        assert_eq!(observed, 1, "the removal seam ran exactly once");
        assert!(killed.is_err(), "the injected failure propagates");

        let manifest = members_in_manifest(&project);
        assert!(!manifest.contains("/napi"), "{manifest}");
        assert!(manifest.contains("apps/aaaaaaaaaaaaaaaa/core"), "{manifest}");
        assert!(manifest.contains("apps/bbbbbbbbbbbbbbbb/core"), "{manifest}");
        assert!(
            container.join("napi/Cargo.toml").is_file(),
            "the directory is still there — that is what makes this the interrupted state"
        );
    }

    #[test]
    fn scenario_12_a_completed_prune_removes_the_directory_and_the_member() {
        let (_tmp, project, container) = fixture();
        let doomed = prunable(&container, &[PackageKind::Core], PruneOwner::GenerateBuild).unwrap();

        let pruned = prune(&project, &container, &doomed).unwrap();

        assert_eq!(pruned.removed, doomed);
        assert!(!container.join("napi").exists());
        let manifest = members_in_manifest(&project);
        assert!(!manifest.contains("/napi"), "{manifest}");
        assert!(manifest.contains("apps/aaaaaaaaaaaaaaaa/core"), "{manifest}");
        assert!(manifest.contains("apps/bbbbbbbbbbbbbbbb/core"), "{manifest}");
    }

    #[test]
    fn a_differently_spelled_doomed_path_is_still_de_listed_first() {
        let (_tmp, project, container) = fixture();

        let hash = container.file_name().unwrap().to_owned();
        let mistyped = vec![container.join("..").join(hash).join("napi")];
        assert!(mistyped[0].is_dir(), "the mis-spelling names a real directory");
        assert_ne!(mistyped[0], container.join("napi"), "…and is not Path-equal to it");

        let pruned = prune(&project, &container, &mistyped).unwrap();

        assert_eq!(pruned.removed, mistyped, "it was deleted");
        assert!(!container.join("napi").exists());
        let manifest = members_in_manifest(&project);
        assert!(
            !manifest.contains("/napi"),
            "the root still names a directory that is now GONE — every app in this \
             project is unbuildable:\n{manifest}"
        );
    }

    #[test]
    fn a_doomed_path_outside_the_container_is_refused() {
        let (_tmp, project, container) = fixture();
        let sibling = project.join("apps/bbbbbbbbbbbbbbbb/core");

        let mut removals = 0;
        let err = prune_with(&project, &container, std::slice::from_ref(&sibling), &mut |_| {
            removals += 1;
            Ok(())
        })
        .expect_err("must refuse");

        assert_eq!(removals, 0, "nothing was deleted");
        assert!(err.to_string().contains("outside the app container"), "{err}");
        assert!(sibling.join("Cargo.toml").is_file(), "the sibling is untouched");
        let manifest = members_in_manifest(&project);
        assert!(
            manifest.contains("apps/bbbbbbbbbbbbbbbb/core"),
            "and is still a member:\n{manifest}"
        );
    }

    #[test]
    fn an_empty_prune_deletes_nothing_and_still_rewrites_the_root() {
        let (_tmp, project, container) = fixture();

        let pruned = prune(&project, &container, &[]).unwrap();

        assert!(pruned.removed.is_empty());
        assert_eq!(pruned.synced.members.len(), 3, "{:?}", pruned.synced.members);
        assert!(container.join("napi/Cargo.toml").is_file());
    }
}
