//! The generated-source fingerprint (#337).
//!
//! # What it answers
//!
//! *"Were these two files generated together?"* — nothing more. It is a change
//! detector over the source ForgeDB emitted for one (app, package) pair, so a
//! delivered native artifact and the shim beside it can each carry the value and
//! refuse to run when they disagree.
//!
//! It is deliberately **not** the CLI's version. A CLI upgrade that changes
//! nothing about the emitted source must invalidate nothing, or the error stops
//! being read — and the error is the entire mechanism.
//!
//! # What it covers, and what it cannot
//!
//! One fingerprint per (app, package): the app's generated `core` package plus
//! that package's own directory, **manifests included** — a substrate pin change
//! alters the compiled artifact while leaving every `.rs` byte identical, so a
//! hash over sources alone would call a genuinely different artifact unchanged.
//!
//! It does not cover `Cargo.lock` (project-wide, and a `= "0.3"` pin that
//! resolved 0.3.1 and 0.3.2 fingerprints identically), the compiler, the profile
//! or the target triple. It is not a provenance or integrity mechanism: anything
//! that can write the artifact can write the constant.
//!
//! # Why the framing has a length prefix
//!
//! Concatenating `path` and `bytes` makes `("a", "bc")` and `("ab", "c")` hash
//! alike. The separator alone does not fix it either, since a path or a body may
//! contain the separator byte. The length of the body is what makes the encoding
//! injective, and [`compute`]'s own test asserts the collision is gone rather
//! than trusting the argument.

use std::path::Path;

/// One (relative path, bytes) pair, exactly as it will be written to disk.
///
/// `bytes` is `&str` rather than `&[u8]` because every file ForgeDB generates is
/// UTF-8 text; taking the rendered `String` is what makes the hash cover the
/// bytes that actually land rather than a re-derivation of them.
pub struct Entry<'a> {
    pub path: String,
    pub bytes: &'a str,
}

/// The generated file that carries the value, excluded from its own input **by
/// name** — otherwise the definition is circular (epic #337 requirement 2).
///
/// Package-relative. [`compute`] excludes any entry whose path ends with it, so
/// the exclusion survives the `<package-dir>/` prefix the caller namespaces
/// entries with.
pub const FINGERPRINT_FILE: &str = "src/fingerprint.rs";

/// FNV-1a over a canonical, injectively framed rendering of `entries`.
///
/// **Canonical order is by `path`**, so the value cannot depend on the order the
/// emitter happened to plan its files in, nor on a directory read order.
///
/// Framing per entry: `path \0 len(bytes) \0 bytes`, with `len` in decimal.
///
/// The digest is [`crate::cache::fnv1a_hex`] — the same one the cache's member
/// hash uses, pinned by that module's golden vectors. `DefaultHasher` is not
/// stable across Rust releases and `cargo install` builds with the user's own
/// toolchain, so a std hash here would change the value under a shim that is
/// already committed.
pub fn compute(entries: &[Entry<'_>]) -> String {
    let mut kept: Vec<&Entry<'_>> = entries
        .iter()
        .filter(|e| !is_fingerprint_file(&e.path))
        .collect();
    kept.sort_by(|a, b| a.path.cmp(&b.path));

    let mut framed = Vec::new();
    for entry in kept {
        framed.extend_from_slice(entry.path.as_bytes());
        framed.push(0);
        framed.extend_from_slice(entry.bytes.len().to_string().as_bytes());
        framed.push(0);
        framed.extend_from_slice(entry.bytes.as_bytes());
    }
    crate::cache::fnv1a_hex(&framed)
}

/// Is this entry the fingerprint file itself?
///
/// Compared as PATH COMPONENTS, not as a string suffix: a plain
/// `ends_with(FINGERPRINT_FILE)` would also swallow a hypothetical
/// `.../not_src/fingerprint.rs`, and silently dropping a real generated file
/// from the input is the one failure mode of this function that nothing
/// downstream can see.
fn is_fingerprint_file(path: &str) -> bool {
    let mut want = Path::new(FINGERPRINT_FILE).components().rev();
    let mut got = Path::new(path).components().rev();
    loop {
        match (want.next(), got.next()) {
            (None, _) => return true,
            (Some(_), None) => return false,
            (Some(w), Some(g)) if w == g => {}
            _ => return false,
        }
    }
}

/// The emitted `src/fingerprint.rs`.
///
/// A file of its own rather than a line in `lib.rs`, because it has to be
/// excluded from the hash input and a line cannot be excluded by name.
pub fn fingerprint_rs(value: &str) -> String {
    format!(
        "// Generated by ForgeDB (#337). DO NOT EDIT.\n\
         //\n\
         // The fingerprint of the source this package was generated from: the app's\n\
         // `core` package plus this package's own directory, manifests included, and\n\
         // this file excluded from its own input.\n\
         //\n\
         // The consumer-facing shim beside the delivered artifact carries the same\n\
         // value and refuses to load when the two disagree. It is a change detector,\n\
         // not a version and not a signature.\n\
         pub const FINGERPRINT: &str = \"{value}\";\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_fingerprint_file_is_recognised_by_components_not_by_suffix() {
        assert!(is_fingerprint_file("napi/src/fingerprint.rs"));
        assert!(is_fingerprint_file("src/fingerprint.rs"));
        // A suffix match would call this the fingerprint file and drop a real
        // generated file out of the input.
        assert!(!is_fingerprint_file("napi/not_src/fingerprint.rs"));
        assert!(!is_fingerprint_file("napi/src/fingerprint.rs.bak"));
        assert!(!is_fingerprint_file("napi/src/lib.rs"));
    }
}
